fonttools/fonttools

Lib/fontTools/ttLib/tables/_h_e_a_d.py

These used to be converted to 0.

Regard very low datetimes as unix timestamps

---

Lib/fontTools/ttLib/sfnt.py

As suggested in a comment by @behdad inside the sfnt module's source code,
> the checksum for woff is not working correctly
The calculation is broken in WOFF1 because it's using the compressed `length` and the `offset` values from the WOFF directory entries, instead of using the `origLength` and the corresponding  `origOffset` from the original SFNT font.
The head table's checksum adjustment value of a WOFF font should refer not to the WOFF font itself, but to the input SFNT font.
This patch fixes that.
Now, if you compare the `checkSumAdjustment` of the input SFNT font with that of the resulting WOFF, they should finally match -- of course provided that the table data keeps the same order in the two fonts (i.e. using same `reorderTable` value for both).
Cheers,
C.

[sfnt] fix WOFF checksum adjustment calculation

---

Lib/fontTools/subset.py

The Python style (outside of Google) is four spaces for indentation.
After this change, pylint still has complaints about this file,
but these formatting changes will probably improve the health
metrics of landscape.io. Personally, I couldn't care less about
whitespace, but it is hard to spot actual problems in a sea
of lint warnings.

Change whitespace in subset.py to conform with Python style guide

---

Lib/fontTools/ttLib/tables/O_S_2f_2.py

this addresses a [request](https://github.com/behdad/fonttools/issues/255) by @lemzwerg to recalculate the `fsFirstCharIndex` and `fsLastCharIndex` of OS/2 table while reassembling a font.
I added a method to the OS/2 table class, which is called upon compiling that table. It simply gathers all codes specified in cmap subtables (3, 0) or (3, 1) and takes the min/max among these.
Should this be the default behaviour when compiling the OS/2 table (like in the current patch), or it should be controlled through some sort of option?

[OS/2] update fsFirstCharIndex and fsLastCharIndex upon compile

---

Lib/fontTools/ttLib/sfnt.py

Fixes https://github.com/behdad/fonttools/issues/239

[sfnt] raise TTLibError if there aren't enough bytes to unpack header

---

Lib/fontTools/ttx.py

Fixes https://github.com/behdad/fonttools/issues/45

[ttx] 'touch' output file to avoid race condition in choosing file names

---

Lib/fontTools/merge.py
setup.py

This is an attempt to fix issue https://github.com/behdad/fonttools/issues/290.
It uses a trick found [here](http://stackoverflow.com/a/2240549) which monkeypatches the py_compile.compile function used by distutils, so that it will raise an exception instead of a warning on any errors found while bytecompiling the modules.
With this the `make all` command will properly fail.

[setup.py] monkeypatch py_compile to halt compilation on syntax errors

---

Lib/fontTools/ttLib/tables/_f_p_g_m.py
Lib/fontTools/ttLib/tables/ttProgram.py

Fixes https://github.com/behdad/fonttools/issues/301

[ttProgram] add missing __len__ method to Program class

---

Lib/fontTools/ttLib/__init__.py

Fixes https://github.com/behdad/fonttools/issues/302

[TTFont] wrap input file in a temporary stream to allow overwriting

---

Lib/fontTools/ttx.py

This adds a `--flavor` option similar to the one available in pyftsubset, which takes either "woff" or "woff2".
I also made the handling of the argument parser errors more consistent.

[ttx] add --flavor option to compile to "woff" or "woff2"

---

Lib/fontTools/pens/transformPen.py
Lib/fontTools/pens/ttGlyphPen.py
Lib/fontTools/pens/ttGlyphPen_test.py
Lib/fontTools/ttLib/testdata/TestTTFComplex-Regular.ttx

This adds tests with the existing TTX test data, and some simple unit tests. It also fixes issues with the pen itself! Tests are nice.

TTGlyphPen tests

---

Lib/fontTools/ttLib/sfnt.py

Fixes https://github.com/behdad/fonttools/issues/408

[sfnt] make SFNTReader.tables an OrderedDict sorted by table offset

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py
Lib/fontTools/feaLib/testdata/GPOS_1.fea
Lib/fontTools/feaLib/testdata/GPOS_1.ttx

[feaLib] make Device Table from device tuples

---

setup.py

Seems that setup.py wasn't installing this.

Add t1Lib to packages

---

.travis.yml
requirements.txt

use faster, container-based Travis infrastructure

---

Lib/fontTools/pens/boundsPen.py
Lib/fontTools/pens/boundsPen_test.py

see discussion:
https://github.com/behdad/fonttools/pull/450
https://github.com/typemytype/booleanOperations/pull/20
cc @adrientetar @behdad

add "ignoreSinglePoints" argument to bounds pen

---

Lib/fontTools/unicode.py

As suggested by Adam @twardoch in https://github.com/behdad/fonttools/issues/83#issuecomment-139052095

[unicode] attempt to import `unicodedata2` backport module

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py

as discussed in https://github.com/typesupply/compositor/pull/10

_n_a_m_e: add toStr method to NameRecord

---

Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py

This is a minor change, but I'm not sure if this is the best place for it.

[feaLib] Accept empty statements in parser

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/subset_test.py
Lib/fontTools/subset/testdata/TestMATH-Regular.ttx
Lib/fontTools/subset/testdata/expect_keep_math.ttx

Support subsetting MATH table, including adding glyph from math variant records to the final subset.
CC @fred-wang.

Add support for subsetting MATH table

---

Lib/fontTools/ttLib/__init__.py

This partly addresses issue #482.
cc @behdad @justvanrossum

[ttLib] don't load whole input file in memory if 'lazy' is True

---

Lib/fontTools/ttLib/tables/O_S_2f_2.py

Fixes https://github.com/behdad/fonttools/issues/497

[O_S_2f_2] skip updateFirstAndLastCharIndex if cmap table class is DefaultTable

---

Lib/fontTools/ttLib/tables/otBase.py

Change log level of 'Attempting to fix OTLOffsetOverflowError' from warning to debug to close #499

otBase.py log level adjustment

---

Snippets/README
Snippets/README.md

Snippets/README -> README.md, link to other utils

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/testdata/name.fea
Lib/fontTools/feaLib/testdata/name.ttx
Lib/fontTools/feaLib/testdata/spec9e.fea
Lib/fontTools/feaLib/testdata/spec9e.ttx

Needs some tests, but I though to get feedback first since this is my first try with feaLib code.

[feaLib] Support name table

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/testdata/size.fea
Lib/fontTools/feaLib/testdata/size.ttx
Lib/fontTools/feaLib/testdata/size2.fea
Lib/fontTools/feaLib/testdata/size2.ttx
Lib/fontTools/feaLib/testdata/spec8b.fea
Lib/fontTools/feaLib/testdata/spec8b.ttx
Lib/fontTools/feaLib/testdata/spec8c.fea
Lib/fontTools/feaLib/testdata/spec8c.ttx

Does not handle featureNames for cvXX features, but it shouldn’t be hard
for someone to extend the code to support them if inclined to do so.

[feaLib] Support stylistic set featureNames and size feature

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/testdata/spec9a.fea
Lib/fontTools/feaLib/testdata/spec9a.ttx

Just the parts documented a currently implemented by Adobe’s
implementation.

[feaLib] Support BASE table

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/lexer_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py

Untested. Closes #443.
r? @brawer

feaLib: support string input

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/lexer_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py

as discussed in https://github.com/behdad/fonttools/issues/443#issuecomment-199252850 and following comments

[feaLib] take in a path or a file-like object

---

Lib/fontTools/varLib/designspace_test.py
Lib/fontTools/varLib/testdata/VarLibTest.designspace

I wrote this just to understand what the code does, but it might be useful as a test case.

[varLib] Unit test for loading .designspace files

---

Lib/fontTools/ttLib/tables/C_F_F_.py
Lib/fontTools/ttLib/tables/_f_v_a_r.py
Lib/fontTools/ttLib/tables/_m_e_t_a.py

Follow up to [Behdad's comment](https://github.com/behdad/fonttools/pull/586#issuecomment-213257969).

don't hardcode the table tags, rely on ttLib.getClassTag instead

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/ttLib/woff2_test.py

I learnt about it from [1] and seems like a nice thing to use.
1. https://github.com/behdad/fonttools/pull/586#issuecomment-213285350

Use ttLib.newTable when possible

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py
Lib/fontTools/feaLib/testdata/bug504.fea
Lib/fontTools/feaLib/testdata/bug504.ttx
Lib/fontTools/otlLib/builder.py
Lib/fontTools/otlLib/builder_test.py

glyph class as list and tuple instead of set and frozenset

---

Lib/fontTools/pens/areaPen.py
Lib/fontTools/pens/perimeterPen.py

see https://github.com/behdad/fonttools/issues/617#issuecomment-225029592

Area and Perimeter pens

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/testdata/spec4h1.ttx
Lib/fontTools/feaLib/testdata/spec4h2.fea
Lib/fontTools/feaLib/testdata/spec4h2.ttx

@brawer
Should fix https://github.com/behdad/fonttools/issues/613

[feaLib] Fix exclude_dflt handling

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/testdata/language_required.fea

@brawer
Following up on https://github.com/behdad/fonttools/pull/623#issuecomment-227644699

[feaLib] Don't set language when script is unset

---

Lib/fontTools/mtiLib/__init__.py

Add cmap handling to mtiLib

---

Lib/fontTools/pens/pointInsidePen_test.py

See https://github.com/behdad/fonttools/issues/621#issuecomment-226389782

Two more tests for pointInsidePen

---

Lib/fontTools/pens/pointInsidePen_test.py

Example that fails latest PointInsidePen

---

Lib/fontTools/pens/qtPen.py

qtPen: use native quads impl

---

Lib/fontTools/ttLib/tables/C_P_A_L_.py
Lib/fontTools/ttLib/tables/C_P_A_L_test.py

Just an improvement and an addition to the XML output of the CPAL table.

[CPAL] XML enhancements

---

Lib/fontTools/voltLib/ast.py
Lib/fontTools/voltLib/lexer.py
Lib/fontTools/voltLib/lexer_test.py
Lib/fontTools/voltLib/parser.py
Lib/fontTools/voltLib/parser_test.py

This add fontTools.voltLib which much like feaLib parses OTL definitions but from VOLT files.
I haven’t had time to implement building yet, so merging can let others help.

voltLib: parsing VOLT files

---

Lib/fontTools/pens/ttGlyphPen_test.py

ttGlyphPen_test: add more tests for removal of extra move/end points

---

.travis.yml
.travis/after_success.sh

And also fix PyPI deployment following the change in the repository name.

[travis] also deploy to Github Releases on tags

---

NEWS

please let me know if I forgot something, thanks.

update changelog for 3.2.0

---

Lib/fontTools/varLib/__init__.py

Per discussion in https://github.com/fonttools/fonttools/issues/705, added a quick and dirty --buildHVAR commandline switch to build the HVAR on TTFs (for those of us testing on other platforms than FreeType), with default off.

Add commandline switch to build HVAR

---

Lib/fontTools/ttLib/tables/O_S_2f_2.py

https://twitter.com/ken_lunde/status/796564061206913024
https://www.microsoft.com/typography/otspec/errata.htm

Fix "Private Use (plane 15)" range

---

.appveyor.yml

appveyor: latest setuptools fixed

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/subset_test.py
Lib/fontTools/subset/testdata/TestTTF-Regular_non_BMP_char.ttx

[subset] workaround for "narrow" py2 builds and --text= option

---

Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser_test.py

Loading features from file objects have been supported for a while
already.

[feaLib][test] No need to create temporary file

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py

I hope Martin doesn't mind if I PEP8-ify his patch ;)

minor style/whitespace fixes to appease flake8 linter

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py
Lib/fontTools/feaLib/testdata/GSUB_6.fea
Lib/fontTools/feaLib/testdata/GSUB_8.fea
Lib/fontTools/feaLib/testdata/name.fea
Lib/fontTools/feaLib/testdata/spec5f_ii_2.fea
Lib/fontTools/feaLib/testdata/spec5f_ii_3.fea
Lib/fontTools/feaLib/testdata/spec5f_ii_4.fea
Lib/fontTools/feaLib/testdata/spec5fi3.fea
Lib/fontTools/feaLib/testdata/spec8a.fea
Lib/fontTools/feaLib/testdata/spec8b.fea
Lib/fontTools/feaLib/testdata/spec8c.fea
Lib/fontTools/feaLib/testdata/spec9e.fea

@mhosken please take a look, thanks

Fix merge conflict with PR778

---

Lib/fontTools/ttLib/tables/M_V_A_R_test.py

Based on a Selawik test MVAR table from https://github.com/fonttools/fonttools/issues/689#issuecomment-268146882.

Add MVAR tests

---

Lib/fontTools/ttLib/tables/S_T_A_T_test.py

There were only decompile_toXML tests. This adds compile_fromXML tests.

STAT: test_compile_* tests

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/data/spec9e.fea
Tests/feaLib/lexer_test.py
Tests/feaLib/parser_test.py

https://github.com/fonttools/fonttools/issues/780

[feaLib]Escape nameid strings when writing feature files

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/GPOS_1.fea
Tests/feaLib/data/spec6h_iii_1.fea
Tests/feaLib/parser_test.py

Fixes https://github.com/fonttools/fonttools/issues/848.

Distinguish value records format A from format B with zero values

---

Tests/feaLib/builder_test.py
Tests/feaLib/data/bug633.fea
Tests/feaLib/data/bug633.ttx

https://github.com/fonttools/fonttools/issues/633

[feaLib] Add test case for class-based pair kerning with zero values

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/bug514.fea
Tests/feaLib/data/bug514.ttx

Fixes https://github.com/fonttools/fonttools/issues/514.

[feaLib] Merge SinglePos chain targets

---

Lib/fontTools/merge.py
Tests/merge_test.py

Reference #859 
Still open to other ideas.

Change gasp merge logic to 'first'

---

Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/varLib/builder.py
Tests/varLib/data/BuildTest.ttx
Tests/varLib/varLib_test.py

[varLib.builder] Fix roundtripping XML

---

Tests/varLib/interpolatable_test.py
setup.py
test-requirements.txt
tox.ini

@anthrotype this test requires an additional package. Is this how to set it up?

[varLib tests] Test for interpolatable.py

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/parser_test.py

https://github.com/fonttools/fonttools/pull/879#discussion_r104947968
https://github.com/fonttools/fonttools/issues/829

[feaLib] Simplify parser API by removing the `ignore_comments` option

---

Lib/fontTools/cffLib.py
Lib/fontTools/misc/psCharStrings.py

A late patch from @readroberts.

[CFF2] Support ‘maxstack’

---

Lib/fontTools/pens/wxPen.py

pens: add a wx pen

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/_n_a_m_e.py
NEWS.rst
Tests/ttLib/tables/_n_a_m_e_test.py

Fixes https://github.com/fonttools/fonttools/issues/921.

[name] Add helper for building multi-lingual names

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

https://github.com/fonttools/fonttools/issues/931

[name] Fix platform ID for names whose language code is in `ltag` table

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

Fixes https://github.com/fonttools/fonttools/issues/931.

[name] Fix issues with name.addMultilingualName()

---

Lib/fontTools/pens/t2CharStringPen.py
Tests/pens/t2CharStringPen_test.py

These changes will reduce the CFF table a bit.

[t2CharStringPen] Add support for more path operators

---

Lib/fontTools/ttLib/tables/_f_v_a_r.py
NEWS.rst
Tests/subset/data/expect_keep_gvar.ttx
Tests/subset/data/expect_keep_gvar_notdef_outline.ttx
Tests/ttLib/tables/_f_v_a_r_test.py
Tests/varLib/data/test_results/Build.ttx
Tests/varLib/data/test_results/Build3.ttx
Tests/varLib/data/test_results/BuildMain.ttx

Fixes https://github.com/fonttools/fonttools/issues/932.

[fvar] Expose flags in XML

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/mutator.py

Sort glyphs by component depth before processing (#945)

---

Lib/fontTools/varLib/interpolate_layout.py

See https://github.com/fonttools/fonttools/issues/950#issuecomment-303641054

[varLib.interpolate_layout] Allow disabling avar mapping

---

Lib/fontTools/varLib/__init__.py

Just moved the assert per Behdad's request https://github.com/fonttools/fonttools/pull/987#pullrequestreview-45392115.

Move assert outside of if at the bottom of _add_MVAR() per Behdad.

---

Lib/fontTools/ttx.py

Confusion reported at https://groups.google.com/forum/#!topic/fonttools/7ocZWHbsCLw

ttx.py Clarify help text

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/Build3.ttx

I think this is ready to be merged.  Test is failing because expected output needs to be updated.  I like to hear how it performs for people.  It's enabled by default in fontmake.

Varlib iup optimal

---

Lib/fontTools/varLib/__init__.py

[varLib] Initialize the avar segment map with required default entries

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/tables/_h_e_a_d.py
Lib/fontTools/ttLib/tables/_h_h_e_a.py
Lib/fontTools/ttLib/tables/_v_h_e_a.py
Tests/cffLib/cffLib_test.py
Tests/misc/psCharStrings_test.py
Tests/ttLib/tables/_h_h_e_a_test.py
Tests/ttLib/tables/_v_h_e_a_test.py
Tests/ttLib/tables/data/_h_h_e_a_recalc_OTF.ttx
Tests/ttLib/tables/data/_h_h_e_a_recalc_TTF.ttx
Tests/ttLib/tables/data/_h_h_e_a_recalc_empty.ttx
Tests/ttLib/tables/data/_v_h_e_a_recalc_OTF.ttx
Tests/ttLib/tables/data/_v_h_e_a_recalc_TTF.ttx
Tests/ttLib/tables/data/_v_h_e_a_recalc_empty.ttx

CFF bounds recalculation

---

Lib/fontTools/ttLib/tables/otConverters.py
Tests/ttLib/tables/_o_p_b_d_test.py

Fixes https://github.com/fonttools/fonttools/issues/1031.

[AAT] Fix decompilation of AppleChancery and other AAT fonts

---

Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_g_c_i_d.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otData.py
README.rst
Tests/ttLib/tables/_g_c_i_d_test.py

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6gcid.html
https://github.com/fonttools/fonttools/issues/178

[AAT] Support the `gcid` table for Glyph-to-CID mapping

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/__init__.py
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master0.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master1.ttx
Tests/varLib/data/test_results/BuildMain.ttx
Tests/varLib/data/test_results/InterpolateLayoutMain.ttx
Tests/varLib/data/test_results/Mutator.ttx

Merging TT hinting

---

Lib/fontTools/pens/svgPen.py

Copied and slightly adapted from:
https://github.com/typesupply/ufo2svg/blob/master/Lib/ufo2svg/svgPathPen.py

Add SVGPen

---

Lib/fontTools/ttLib/tables/F__e_a_t.py
Lib/fontTools/ttLib/tables/S__i_l_f.py
Tests/ttLib/tables/data/graphite/graphite_tests.ttx.Feat
Tests/ttLib/tables/data/graphite/graphite_tests.ttx.Silf

This patch fixes a few minor but significant bugs in the Graphite table support to ensure clean round tripping via ttx.

Fix small graphite round trip bugs

---

Lib/fontTools/misc/bezierTools.py
Lib/fontTools/pens/perimeterPen.py

As discussed in https://github.com/robofab-developers/fontPens/pull/5.

Move arc length calculations from pens.perimeterPen to misc.bezierTools

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/misc/loggingTools.py
Tests/feaLib/builder_test.py

emit warning if enum pos rules overridden by preceding single pair

---

Lib/fontTools/ttLib/ttCollection.py
Lib/fontTools/ttLib/ttFont.py

revert closeStream to try fix failing pypy tests

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

(this also will come in handy for the stuff i'm working on in ufo2ft)

[feaLib] allow to build from pre-parsed ast.FeatureFile object

---

Tests/ttx/ttx_test.py

[ttx_test] Test for split tables (-s) option

---

Lib/fontTools/feaLib/lexer.py
Tests/feaLib/lexer_test.py

In the IncludedFeaNotFound error, pass on the filename token as
it was included in the include statement, so that a client can do their
thing (e.g. issue a warning to suggest the user to write the path
relative to the UFO itself, instead of relative to the feautures.fea
which is inside a UFO).
Also, resolve includes relative to current working directory when the IncludingLexer' filename is None because it originates from an in-memory stream.
And add an explicit test for the case when the included path is absolute.

 [feaLib.lexer] pass included filename token to IncludedFeaNotFound

---

Lib/fontTools/pens/ttGlyphPen.py
NEWS.rst
Tests/feaLib/lexer_test.py
Tests/pens/ttGlyphPen_test.py

this is a follow up from @moyogo's PR #1204 (after a private conversation).
Fixes #1200

Fixups on top of PR #1204

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/varLib_test.py

Allow to customize the location of the interpolatable master ttfs relative to the designspace source filenames.
Takes a template string containing special placeholders that are parametrized with the value of each source file name:
- `{fullname}`: the absolute source file name;
- `{basename}`: the source file name without its directory;
- `{stem}` is the basename without the file extension;
- `{ext}` is the source file extension;
- `{dirname}` is the directory of the absolute source file name.
The default value remains the current one: i.e. `master_ttf_interpolatable/{stem}.ttf`

[varLib] add a --master-finder command line option 

---

Doc/source/designspaceLib/readme.rst

See https://github.com/fonttools/fonttools/issues/1243

designspaceLib: This adds conditionsets to the rule element.

---

Doc/source/designspaceLib/readme.rst
Lib/fontTools/designspaceLib/__init__.py
Tests/designspaceLib/data/test.designspace
Tests/designspaceLib/designspace_test.py

this is incomplete, I push it here so we can work together with @LettError 
the reader still needs to be updated to support the new conditionset element, while also allow to read previous format (condition elements without a conditionset).

WIP: implement conditionSets in designspaceLib.RuleDescriptor 

---

Lib/fontTools/cffLib/__init__.py

same as PR #1211 by @readroberts, rebased on latest master

rebase #1211

---

Lib/fontTools/varLib/mutator.py
Tests/varLib/data/test_results/Mutator.ttx
Tests/varLib/data/test_results/Mutator_IUP-instance.ttx

WIP [mutator] set usWeightClass, usWidthClass and italicAngle

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/PairPosSubtable.fea
Tests/feaLib/data/PairPosSubtable.ttx

Fixes https://github.com/fonttools/fonttools/issues/1279

support explicit "subtable" breaks in kerning lookups

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/data/PairPosSubtable.fea
Tests/feaLib/data/PairPosSubtable.ttx

The PairPos subtable break was being forced after each 'pos' statement following a 'subtable' statement, it should only be forced the time.

Fix subtable break

---

README.rst

I hope this doesn't seem pedantic. I'm starting to investigate using fonttools, and noticed some typos.

Minor README tweaks

---

Lib/fontTools/merge.py

desubroutinizing with Subsetter
No compreffor. No final compression (may happen after, outside merge)

[merge] CFF tables

---

Lib/fontTools/ufoLib/__init__.py

Change UFOLib creator

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/FeatureVars.designspace

Fix normalization error when condition’s minimum/maximum are missing in designspace, update test too

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/data/test.otf.ttx
Tests/fontBuilder/data/test_var.ttf.ttx
Tests/fontBuilder/fontBuilder_test.py

- some doc strings
- new setupHorizontalMetrics and setupVerticalMetrics methods
- test for variations (but: the variation support is very minimal and low level, I need to figure out how varLib could be involved here)

FontBuilder improvements

---

Lib/fontTools/varLib/featureVars.py
Tests/varLib/data/test_results/FeatureVars.ttx

Somehow we've been writing the wrong value for `FeatureTableSubstitution.Version`.

[varLib.featureVars] Fix FeatureTableSubstitution.Version

---

Lib/fontTools/misc/dictTools.py
Lib/fontTools/misc/intTools.py
Lib/fontTools/varLib/featureVars.py
Tests/varLib/data/test_results/FeatureVars.ttx
Tests/varLib/featureVars_test.py

Motivated by https://github.com/fonttools/fonttools/issues/1370

[varLib] Far faster featureVars

---

Lib/fontTools/ttLib/tables/_k_e_r_n.py
Tests/ttLib/tables/_k_e_r_n_test.py

The "length" value of kern table subtable format 0 is ignored since some fonts (like OpenSans and Calibri) have a subtable larger than its value.
Fixes #314.

Ignore the length of kern table sutable format 0

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/cffLib/cff2mergePen.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/subset/cff.py
Lib/fontTools/varLib/mutator.py

Address issue 'CFF2 code cleanup #1392'

CFF2 code cleanup

---

Lib/fontTools/ttLib/tables/ttProgram.py

[ttLib] Use raw strings for regex patterns.

---

Tests/varLib/featureVars_test.py

[varLib.featureVars] tests for #1400

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/fontBuilder/data/test.otf.ttx
Tests/fontBuilder/data/test.ttf.ttx
Tests/fontBuilder/data/test_var.ttf.ttx
Tests/ttLib/tables/_n_a_m_e_test.py

[name] make addMultilingualNames() add mac names by default

---

Tests/ttLib/tables/_c_m_a_p_test.py
Tests/ttLib/tables/data/_c_m_a_p_format_14.ttx

[ttLib] adding a test for cmap format 14 (unicode variation sequences)

---

Lib/fontTools/ttLib/tables/_c_m_a_p.py
Tests/fontBuilder/data/test_uvs.ttf.ttx
Tests/ttLib/tables/_c_m_a_p_test.py
Tests/ttLib/tables/data/_c_m_a_p_format_14.ttx
Tests/ttLib/tables/data/_c_m_a_p_format_14_bw_compat.ttx
Tests/ttLib/tables/data/aots/cmap14_font1.ttx.cmap

[ttLib] cmap format 14 cleanup

---

Lib/fontTools/ttLib/tables/_h_m_t_x.py
Tests/ttLib/tables/_h_m_t_x_test.py

when no horizontal/vertical header table is present, we can assume numberOfHMetrics == maxp.numGlyphs.
This allows to compile/decompile incomplete (i.e. technically invalid) OpenType binary fonts that only containing head, maxp, hmtx, loca and glyf (or CFF), that is the bare minimum to temporarily store glyph outline and metrics data for use as sparse/intermediate master TTFs to build variable fonts with varLib.
See https://github.com/googlei18n/ufo2ft/issues/308

{v,h}mtx: allow to compile/decompile even without {v,h}hhea table

---

Lib/fontTools/ttx.py
Tests/ttx/ttx_test.py

[ttx] add --no-recalc-timestamp option to keep original head.modified

---

Doc/source/designspaceLib/readme.rst
Lib/fontTools/designspaceLib/__init__.py

Closes https://github.com/fonttools/fonttools/issues/1417.

[designspaceLib] Remove InstanceDescriptor.mutedGlyphNames

---

Lib/fontTools/voltLib/ast.py
Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

[voltLib] Fix parsing glyph groups

---

Lib/fontTools/feaLib/__main__.py

[feaLib] Add 'tables' option to __main__.py

---

Lib/fontTools/svgLib/path/__init__.py
Lib/fontTools/svgLib/path/shapes.py
Tests/svgLib/path/shapes_test.py

continuation of #1500, but from a shared branch on the upstream repo

[svgLib] add support for importing shapes into paths

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

For consistency with other substitution statements.

[feaLib] Add forceChain to MultipleSubstStatement

---

Lib/fontTools/subset/__init__.py

This PR fixes issue #1516.
It looks like a simple copy & paste & forgot-to-edit bug.
Fix is simple & straightforward too.

Fix issue #1516: subset VVAR

---

Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/varLib/plot.py
Tests/designspaceLib/designspace_test.py

[designspaceLib] use axis maps in DesignSpaceDocument.normalizeLocation

---

Lib/fontTools/varLib/plot.py

currently, varLib.plot only takes designspaces containing 2 axes, and plots them in 3D (z axis being scalar value).
It can be useful to visualize single-axis designspace using 2D plots

varLib.plot: support 2D plots with only 1 variation axis

---

Lib/fontTools/encodings/codecs.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/misc/encodingTools.py
Lib/fontTools/misc/timeTools.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/cff.py
Lib/fontTools/ttLib/tables/E_B_L_C_.py
Lib/fontTools/ttLib/tables/_h_e_a_d.py
Lib/fontTools/ttLib/tables/otBase.py

The forwards still work, but I thought it'd be better to update them to the current repo.

updated inline github issue URLs

---

Lib/fontTools/misc/xmlWriter.py
Tests/feaLib/data/GPOS_1_zero.fea
Tests/feaLib/data/GPOS_2.fea
Tests/feaLib/data/bug453.fea
Tests/feaLib/data/bug463.fea
Tests/feaLib/data/bug501.fea
Tests/feaLib/data/bug502.fea
Tests/feaLib/data/bug504.fea
Tests/feaLib/data/bug505.fea
Tests/feaLib/data/bug506.fea
Tests/feaLib/data/bug568.fea
Tests/feaLib/parser_test.py
Tests/misc/xmlWriter_test.py
Tests/subset/subset_test.py
Tests/ttLib/data/TestOTF-Regular.otx
Tests/ttLib/data/TestTTF-Regular.ttx
Tests/ttLib/tables/TupleVariation_test.py
Tests/ttLib/tables/_n_a_m_e_test.py
Tests/ttLib/tables/otTables_test.py
Tests/ttx/data/TestOTF.ttx
Tests/ttx/data/TestTTF.ttx

more updated issue URLs

---

Doc/source/designspaceLib/readme.rst

UFO specification discussion: https://github.com/unified-font-object/ufo-spec/issues/68
UFO specification PR: https://github.com/unified-font-object/ufo-spec/pull/84
ufo2ft PR: https://github.com/googlei18n/ufo2ft/pull/318

[designspaceLib] Document proposed public.skipExportGlyphs lib key

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

Fixes https://github.com/fonttools/fonttools/issues/1538

[feaLib] Handle lookupflag 0 and lookupflag wothout a value

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/data/test_var.otf.ttx
Tests/fontBuilder/fontBuilder_test.py

Before this change all OTFs wound up with 'post' table format 3

[fontBuilder] Enable making CFF2 fonts with 'post' table format 2

---

Lib/fontTools/varLib/instancer.py
Tests/varLib/instancer_test.py

The function now takes a VarStore instance, the fvar axes and a partial location, and returns an array of delta-sets to be applied to the default instance.
The algorithm is now more similar to the one used for instantiating the tuple variation store.
Tests are coming soon.

refactor instantiateItemVariationStore for better test-ability

---

Lib/fontTools/ttLib/tables/S__i_l_f.py

OOps. sorry. This one is even tested. Sigh.

Fix unmasked bug from previous typo fix

---

Lib/fontTools/subset/cff.py
Tests/subset/data/test_cntrmask_CFF.desub.ttx
Tests/subset/data/test_cntrmask_CFF.ttx
Tests/subset/subset_test.py

Fixes issue '[subset] AssertionError when using --desubroutinize #1590'

Fix bug in subsetting T2 CharStrings from CFF font, issue 1590

---

Lib/fontTools/varLib/instancer.py

This allows to drop an axis (aka "L1" partial instancing) without knowing the axis' actual default value from fvar table. One can simply call `instantiateVariableFont` function with a `None` value for a particual axis (i.e. `axis_limits={'wght': None}`); the `None` value is replaced by the axis default value as per fvar table.
The same can be done from the console script as well. The special string literal 'None' is parsed as the Python `None` object. E.g.:
```
$ fonttools varLib.instancer MyFont-VF.ttf wght=None
```

instancer: make 'None' mean to drop an axis, or pinning at default

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/expect_math_partial.ttx
Tests/subset/data/test_math_partial.ttx
Tests/subset/subset_test.py

Both `MathGlyphInfo` and `MathVariants` can be None, so check for that first before trying to access their methods.

[subset] Gracefully handle partial MATH table

---

.appveyor.yml
.travis.yml
tox.ini

https://github.com/fonttools/fonttools/issues/765#issuecomment-468650240

travis/appveyor: no longer run tests on python2.7

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

[ttLib] fix UnboundLocalError for empty loca/glyph tables

---

Lib/fontTools/ttLib/tables/S__i_l_l.py

Fix Sill table output to pass OTS

---

Lib/fontTools/varLib/cff.py
Lib/fontTools/varLib/instancer.py

@readroberts please check the cff.py change.

Fix minor type errors found with pytype

---

Lib/fontTools/ttLib/tables/_h_h_e_a.py
Tests/ttLib/tables/_h_h_e_a_test.py

[ttLib] Add aliases for renamed entries in hhea table

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

We can currently get and set names but we don't have a method to remove them. I've written similar code in several throwaway scripts before so I think it warrants its own method.

[name] add removeName method to table__n_a_m_e

---

Lib/fontTools/ttLib/tables/S__i_l_f.py

Minor fix to Silf table compilation and decompilation regarding strings and bytes and all things python3.

py3 fixup Silf corner case where script is actually used

---

Lib/fontTools/misc/loggingTools.py
Lib/fontTools/misc/macRes.py
Lib/fontTools/misc/plistlib.py
Lib/fontTools/misc/psLib.py
Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/_h_d_m_x.py
Lib/fontTools/ttLib/tables/_t_r_a_k.py
Tests/misc/plistlib_test.py

Happens to help with mypy checking.

Remove some Python 2 era import gaming

---

Lib/fontTools/pens/pointPen.py

[pens] Improve error message if pen.moveTo() is omitted.

---

Lib/fontTools/varLib/__init__.py
NEWS.rst

After I spent a few minutes debugging this for a designer.

Legible error message for axis mapping duplicate check

---

Snippets/svg2glif.py

- Remove unused `ufoLib` package
- FontTools => fontTools

fix requirements in svg2glif.py

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/data/test_var.ttf.ttx
Tests/fontBuilder/fontBuilder_test.py

like the existing addOpenTypeFeatures method, it simply forwards to featureVars.addFeatureVariations

fontBuilder: add FontBuilder.addFeatureVariations method

---

Lib/fontTools/unicodedata/__init__.py
NEWS.rst

Information taken from https://docs.google.com/spreadsheets/d/1Y90M0Ie3MUJ6UVCRDOypOtijlMDLNNyyLk36T6iMu0o.

Update RTL_SCRIPTS for Unicode 11 and 12

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

Fixes https://github.com/fonttools/fonttools/issues/1709
/cc @garretrieger @qxliu76

[subset] Optimize SinglePos lookup format when all values are same

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

This is like #1767 but for multiple substitutions.

[feaLib] Do not fail on duplicate multiple substitutions

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/colorLib/errors.py
Lib/fontTools/fontBuilder.py
Lib/fontTools/ttLib/tables/C_P_A_L_.py
Tests/colorLib/builder_test.py
Tests/ttLib/tables/C_P_A_L_test.py

for now this just adds a `buildCOLR` and `buildCPAL`, e.g. so we can use it in ufo2ft here https://github.com/googlefonts/ufo2ft/pull/359

colorLib: add buildCOLR and buildCPAL

---

Lib/fontTools/feaLib/error.py
Tests/feaLib/lexer_test.py

Also, minor f-string refactor.

Add a proper message to IncludedFeaNotFound

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/merger.py
Tests/varLib/data/TestBASE.designspace
Tests/varLib/data/master_base_test/TestBASE.0.ttx
Tests/varLib/data/master_base_test/TestBASE.900.ttx
Tests/varLib/data/test_results/TestBASE.ttx
Tests/varLib/varLib_test.py

Currently nothing really supports BASE table much less variable BASE table, but tests with the latest uharfbuzz seem to give the intended results.

Add variable support for BASE table 1.1

---

.readthedocs.yml

Fixes Read the Docs configuration file yaml formatting following #1333 merge

Read the Docs configuration file fix

---

README.rst

@chrissimpkins 
An 18 month PR certainly belongs on the acknowledgements!
I guess that index.rst will be auto updated with the build process.
Thanks for your hard work and patience 😄

chore(): update acknowledgements

---

Doc/docs-requirements.txt
Doc/source/index.rst
Doc/source/misc/etree.rst
Doc/source/misc/index.rst
Doc/source/misc/intTools.rst
Doc/source/pens/index.rst
Doc/source/pens/reportLabPen.rst
Doc/source/ttLib/tables.rst

Documentation cleanup and fixes.  Includes updates on the home page so that the documentation is consistent/current with the repository README

Add missing module documentation, fix table module imports, add home page internal library links

---

Lib/fontTools/subset/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/1881

[subset] FeatureVariations subsetting is wrong

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

https://github.com/fonttools/fonttools/issues/1881#issuecomment-620719882

subset: remove FeatureVariations, downgrade GSUB/GPOS to version 1 when empty

---

Lib/fontTools/merge.py
Lib/fontTools/ttLib/tables/E_B_L_C_.py
Lib/fontTools/varLib/merger.py

https://help.semmle.com/wiki/display/PYTHON/Suspicious+unused+loop+iteration+variable

Use _ to denoted unused loop variable

---

Lib/fontTools/merge.py
Tests/merge_test.py

I push a failing test first to repro #1865, then will follow up with the actual fix

[merge] Fix merging different versions of OS/2 table

---

Lib/fontTools/ttLib/sfnt.py
Tests/ttLib/sfnt_test.py
Tests/varLib/varLib_test.py

Fixes https://github.com/fonttools/fonttools/issues/1962

sfnt: add __getstate__ and __setstate__ to SFNTReader to make it pickelable

---

Lib/fontTools/afmLib.py

It writes into the current working dir on test runs.

[afmLib] Do not write doctest file to disk

---

Lib/fontTools/feaLib/__main__.py
Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/error.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/location.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/otlLib/builder.py
Lib/fontTools/otlLib/error.py
Lib/fontTools/otlLib/maxContextCalc.py

Clone #2022 to see if tests run this time...

Reformat feaLib and otlLib 

---

Lib/fontTools/varLib/varStore.py

[varLib] Small bugfix: test for 0xFFFF, not 0xFFF

---

Lib/fontTools/feaLib/builder.py

Only stash lookup location if buildLookups_ has cooperated

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/ttLib/tables/otData.py
Lib/fontTools/ttLib/tables/otTables.py
Tests/colorLib/builder_test.py
Tests/ttLib/tables/C_O_L_R_test.py

Update for format changes in https://github.com/googlefonts/colr-gradients-spec/pull/113

Update to latest COLR v1 (PaintRotate, PaintSkew)

---

Lib/fontTools/pens/basePen.py
Lib/fontTools/pens/hashPointPen.py

Closes https://github.com/fonttools/fonttools/issues/2144.

Add MissingComponentError for pens

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/delete_glyph.fea
Tests/feaLib/data/delete_glyph.ttx

Support "sub A by NULL;" as described in https://github.com/adobe-type-tools/afdko/issues/1234 and implemented in AFDKO as https://github.com/adobe-type-tools/afdko/pull/1251

[feaLib] Allow deleting glyphs

---

Lib/fontTools/pens/basePen.py
Lib/fontTools/pens/pointPen.py
Tests/pens/basePen_test.py
Tests/pens/pointPen_test.py

Revert ABC changes to Pens, fixes #2198, could supersede #2199.

Revert ABC changes to Pens, fixes #2198

---

Doc/source/varLib/index.rst

varLib uses a lot of technical terms in sometimes unfamiliar ways, which can only be understood correctly if you're Behdad. ;-) After a conversation with him this morning where he explained the system to me, I've tried to document my understanding of what those terms mean.

Add definitions for varLib-specific terms

---

Lib/fontTools/misc/bezierTools.py
Lib/fontTools/misc/vector.py
Tests/misc/bezierTools_test.py
Tests/misc/vector_test.py

This PR will have unlikely have a big negative impact on performance, and I think the gained clarity/simplicity should be worth it.
I don't insist on this PR, I just wanted to see what it looks like if Vector is used instead of (x, y) tuples.

Use Vector in some places where it improves the clarity of the code

---

Lib/fontTools/varLib/models.py

See #2207
- Separate computing delta weights
- Split off box-splitting/support code to separate function

Refactor VariationModel

---

Lib/fontTools/varLib/errors.py
Lib/fontTools/varLib/merger.py

Currently error messages from `varLib.merge` are... probably meaningful if you're behdad, but not otherwise. This patch makes `varLib.merge` explain itself better when things go wrong.
Without the patch:
```
fontTools.varLib.errors.VarLibMergeError: ((2, [2, 1, 2, 2]), 'int', '.FeatureCount', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')
```
With the patch:
```
fontTools.varLib.errors.VarLibMergeError:
Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation:
.table.FeatureList.FeatureCount
The problem is likely to be in Simple Two Axis Bold:
Expected to see .FeatureCount==2, instead saw 1
```

Explain merge errors in designer-friendly terms

---

Lib/fontTools/otlLib/builder.py

When trying to use otlLib to build some lookups I found the documentation wasn't quite accurate.

Correct otlLib documentation

---

Lib/fontTools/ttLib/ttFont.py

In `TTFont.save()`: create the file on disk only after compilation to tmp stream succeeded. This fixes #536.

[ttLib] TTFont.save: create file on disk as late as possible

---

Lib/fontTools/ttLib/ttFont.py

- don't do major work in an exception handler
- factor reading table from file into separate method
This would possibly have made the error in #2250 a little more obvious.

[ttLib] Refactored TTFont.__getitem__ somewhat

---

Lib/fontTools/misc/py23.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_c_v_a_r.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/_g_v_a_r.py
Lib/fontTools/varLib/__init__.py
Tests/ttLib/tables/TupleVariation_test.py
Tests/ttLib/tables/_g_l_y_f_test.py

This optimizes and simplifies GlyphCoordinates.
I see 30% speedup in total time of loading master ttfs, building gvar, and saving.

Faster glyph coordinates

---

Lib/fontTools/ttLib/tables/otBase.py
Tests/ttLib/tables/M_V_A_R_test.py

Include record size adjustment.

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/bug2276.fea
Tests/feaLib/data/bug2276.ttx

mean to fix https://github.com/fonttools/fonttools/issues/2276
still trying to reproduce

fix AttributeError while generating aalt feature with empty lookup

---

Lib/fontTools/varLib/merger.py

Fixes https://github.com/googlefonts/fontmake/issues/766

VarLibMergeError.stack is a list of str, not a str

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

As requested, here is the pull request.
Best
Eigi

#2289 fix for typo in typo in ttLib.tables._g_l_y_f.py

---

Lib/fontTools/varLib/models.py

* axisPoints is not used outside the sort function
* Avoid unnecessary intermediary variables
* Index was never used
* Another unused enumeration
* Reformat with black
* Remove else-after-return

Small refactor (and reformat) varLib.models

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

Fixes #2295 
I borrowed @Eigi's test, I hope he doesn't mind ;)

 g_l_y_f: fix undefined name 'topSideBearing'

---

Lib/fontTools/varLib/errors.py
Lib/fontTools/varLib/merger.py

a lot of places instead pass in the 'self' parameter, incorrectly assuming that is a Merger.
This is meant to fix 'AttributeError: 'dict' object has no attribute 'ttfs'' as reported in https://github.com/googlefonts/fontmake/issues/766#issuecomment-836576341
there's still some places where I'm not sure what the right thing to do is

VarLibMergeError first parameter must be a Merger object

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/subset/__init__.py
Tests/colorLib/builder_test.py
Tests/subset/subset_test.py

Thanks @qxliu76 for reporting this bug!
I first add a failing test to repro the issue, then follow up with the fix

[subset/COLR] fix error when subsetting mixed COLR v0/v1 leaves no v0 records

---

README.rst

to reduce the bus factor -- or maybe I should call it the 'new baby factor'

README: add instructions on how to make a release

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

Fixes https://github.com/fonttools/fonttools/issues/2324

[subset] keep empty 'size' but drop empty 'ssXX' features

---

Lib/fontTools/misc/intTools.py

Fixes https://github.com/fonttools/fonttools/issues/2331

Consolidate bit_count / popCount methods

---

Lib/fontTools/pens/ttGlyphPen.py
Tests/pens/ttGlyphPen_test.py

[TTGlyphPen] Fix NotImplementedError with open contours

---

Lib/fontTools/misc/transform.py
Tests/misc/transform_test.py

Adds a transformVector and transformVectors methods to the Transform class. Useful for things like https://github.com/googlefonts/ufo2ft/pull/515

add Transform.transformVector method

---

Lib/fontTools/otlLib/builder.py
Tests/otlLib/builder_test.py

[otlLib] Remove duplicates when building coverage

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/BungeeColor-Regular.ttx
Tests/subset/subset_test.py

Fixes #2461 
.. or will fix after I push the actual fix. For now it's just a test that fails with struct.error.

subset/COLR: fix struct.error while subsetting Bungee COLR

---

Lib/fontTools/feaLib/__main__.py

[feaLib] Fail with error code when build fails

---

Lib/fontTools/merge.py
Tests/merge/data/CFFFont_expected.ttx

Fixes https://github.com/fonttools/fonttools/issues/2475

Merge tamil grantha

---

Lib/fontTools/unicodedata/__init__.py
Tests/unicodedata_test.py

same as https://github.com/harfbuzz/harfbuzz/blob/3.2.0/src/hb-common.cc#L514-L613

unicodedata: update the script direction list to Unicode 14.0

---

Lib/fontTools/unicodedata/OTTags.py
Lib/fontTools/unicodedata/__init__.py
Tests/unicodedata_test.py

see https://github.com/googlefonts/ufo2ft/issues/575#issuecomment-1009962836

unicodedata: alias 'jamo' script tag to 'hang'

---

Lib/fontTools/ttLib/ttFont.py
Tests/ttLib/ttFont_test.py

see https://github.com/fonttools/fonttools/issues/2060#issuecomment-1063932428

Also update glyf's glyphOrder when calling TTFont.setGlyphOrder()

---

Lib/fontTools/cffLib/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/1848

[cff] Remove GlobalState

---

Lib/fontTools/cffLib/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/1847

[cffLib] Fix calls to TopDictIndex()

---

.gitignore
Doc/source/config.rst
Doc/source/index.rst
Doc/source/misc/configTools.rst
Doc/source/misc/index.rst
Lib/fontTools/config/__init__.py
Lib/fontTools/misc/configTools.py
Lib/fontTools/otlLib/builder.py
Lib/fontTools/otlLib/optimize/__init__.py
Lib/fontTools/otlLib/optimize/gpos.py
Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/varLib/merger.py
Tests/config_test.py
Tests/misc/configTools_test.py
Tests/otlLib/optimize_test.py

Add config module as per #2349

---

Lib/fontTools/misc/psCharStrings.py

The very recently merged PR #2577 fixes the direct issue of #2455 and the surface issue in close-to-duplicate #1899 but the problem remains for any code inheriting from or using `T2OutlineExtractor` outside of the `T2CharString` context. The way things are left anyone making other use of `T2OutlineExtractor` also needs to add an `endPath()` call after calling `execute()` -- an undocumented and unusual requirement -- to work correctly with CFF2.
Other questions aside, from a basic object encapsulation standpoint it seems better to handle the issue from within T2OutlineExtractor (which is the level at which `closePath()` starts to be supported) rather than outside of it. 
This PR represents one approach, already discussed a bit in #1899 . I won't pretend this fills me with engineering joy …

Handle implicit CFF2 closepath within T2OutlineExtractor

---

Lib/fontTools/fontBuilder.py
Lib/fontTools/merge/__init__.py
Lib/fontTools/merge/tables.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/O_S_2f_2.py
Tests/merge/data/CFFFont_expected.ttx

Fixes #2538, supersedes #2590 
/cc @aaronbell

[OS/2 / merge] unify recalcXAvgCharWidth method and use it for merger, subsetter, etc.

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

I first push a failing test to reproduce #2602, then follow up with a fix

[subset] Fix subsetting SinglePosFormat2 with ValueFormat=0

---

Lib/fontTools/designspaceLib/statNames.py
Lib/fontTools/designspaceLib/types.py
Tests/designspaceLib/data/test_v5.designspace
Tests/designspaceLib/designspace_v5_test.py
Tests/designspaceLib/statNames_test.py
Tests/varLib/stat_test.py

Found while working on https://github.com/googlefonts/ufo2ft/pull/598.

[designspaceLib] Add some polish to the v5 paths

---

Lib/fontTools/subset/__init__.py

Corresponding to HarfBuzz commits:
https://github.com/harfbuzz/harfbuzz/commit/40193adbfcd4e33fa1fde2fa61b3bcca3548fd05
https://github.com/harfbuzz/harfbuzz/commit/40d7d56e53035e66db5a76a15be3fedd3f9f11cf

[subset] Update default feature tags

---

Lib/fontTools/designspaceLib/__init__.py

Fixes #2631 (comment from @LettError)

[designspaceLib] Add new classes to __all__

---

Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/designspaceLib/split.py
Lib/fontTools/designspaceLib/types.py

...to allow custom classes that don't inherit the default descriptors.
Fixes #2631

[designspaceLib] Check for descriptor types with hasattr()

---

Lib/fontTools/varLib/featureVars.py

Improved version of #2650. See also #2653 for details

Add check for missing glyphs to featureVars

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/instancer/__init__.py
Lib/fontTools/varLib/varStore.py
Tests/varLib/instancer/instancer_test.py
Tests/varLib/varStore_test.py

Feels a bit fragile but I think I got it right.

[varLib.varStore] Support NO_VARIATION_INDEX

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/data/STATInstancerTest.ttx
Tests/varLib/instancer/instancer_test.py

Tackles https://github.com/fonttools/fonttools/issues/2613.
Needs tests.

Set RIBBI bits when cutting instances

---

Lib/fontTools/designspaceLib/statNames.py
Tests/designspaceLib/data/DS5BreakTest.designspace
Tests/designspaceLib/statNames_test.py

See GitHub issue: https://github.com/googlefonts/ufo2ft/issues/630

[designspaceLib] Don't make up bad PS names when no STAT data

---

Lib/fontTools/varLib/errors.py

This fixes #2688.
I don't know this code, so I'm not sure if there's a different underlying problem, but at least this PR fixes the symptoms and gives a usable error message.

[varLib.merge] Fix for error during error reporting

---

Lib/fontTools/feaLib/builder.py

[feaLib] Add missing required FeatureLibError argument

---

Lib/fontTools/varLib/errors.py
Lib/fontTools/varLib/merger.py

Fixes https://github.com/fonttools/fonttools/issues/2712

[varLib.merge] fix NameError: 'NotANone'

---

Doc/source/designspaceLib/xml.rst

Add note about support for specific values

---

Lib/fontTools/varLib/interpolatable.py

Open designspace as well as glyphs files in varLib.interpolatable module.

Interpolatable opener

---

Lib/fontTools/varLib/__init__.py

I think this was an oversight?

[varlib.build_many] Pass on colr_layer_reuse

---

Lib/fontTools/varLib/instancer/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/2733

[instancer] Fix bug in _instantiateFeatureVariations()

---

Lib/fontTools/varLib/instancer/__init__.py

I think the proposed logic is cleaner.

[instancer] Simplify a couple of things

---

Lib/fontTools/varLib/iup.py

Cf. https://github.com/fonttools/fonttools/issues/2264

[varLib.iup] Document IUP algorithm

---

Lib/fontTools/cffLib/specializer.py
Lib/fontTools/varLib/cff.py

Fixes https://github.com/fonttools/fonttools/issues/1975

[cffLib.specializer] Fix generalizer blend

---

Lib/fontTools/subset/cff.py
Tests/subset/data/expect_no_notdef_outline_cid.ttx
Tests/subset/data/expect_notdef_width_cid.ttx

Fixes https://github.com/fonttools/fonttools/issues/139

[subset/CFF] Remove FDSelect workaround from 2014

---

Lib/fontTools/ttLib/ttGlyphSet.py
Tests/ttLib/ttGlyphSet_test.py

[ttGlyphSet] Inherit ttVarGlyphSet from ttGlyphSet

---

Lib/fontTools/subset/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/2769
I don't know how no one noticed this before or how it worked before.

[subset] Fix subsetting of variable fonts

---

Doc/source/designspaceLib/scripting.rst

Update docs for the removal in 3.27.0

checkAxis and checkDefault were removed, but not from doc

---

Lib/fontTools/ttLib/tables/_g_v_a_r.py

This is an alternative to for #2779

Use UserDict for lazy gar variations dict

---

Lib/fontTools/ttLib/ttGlyphSet.py

It's a new module, it's already been run through Black, but kept the tabs for easier review in #2784. Now convert tabs to spaces.

[ttVarGlyphSet] Convert tabs to spaces

---

Lib/fontTools/feaLib/variableScalar.py

This further speeds up variableScalar, by making the cache key construction more straightforward.

Speed up cache key construction

---

Doc/source/designspaceLib/xml.rst

[designspaceLib] Document XML field <labels ordering="1">

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/instancer/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/1480

[varLib / instancer] Remove DSIG table from font

---

Lib/fontTools/varLib/featureVars.py
Tests/varLib/data/test_results/FeatureVars_rclt.ttx

Fixes https://github.com/fonttools/fonttools/issues/2140
Fixes https://github.com/googlefonts/fontmake/issues/950

[varLib/featureVars] Insert rvrn lookups at beginning

---

Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/sfnt.py

Just opens font files from commandline.

[ttLib] Add main to ttFont and ttCollection

---

Doc/source/designspaceLib/python.rst
Doc/source/designspaceLib/xml.rst

[designspaceLib] Small doc fixes

---

Doc/source/developer.rst
Doc/source/index.rst
Lib/fontTools/misc/plistlib/__init__.py
NEWS.rst
README.rst
Tests/ttLib/data/TestOTF-Regular.otx
Tests/ttLib/data/TestTTF-Regular.ttx
Tests/ttx/data/TestOTF.ttx
Tests/ttx/data/TestTTF.ttx

This PR will update the existing references of branch name master to branch name main.

Update references of branch name from master to main

---

Lib/fontTools/unicodedata/OTTags.py
Lib/fontTools/unicodedata/__init__.py
Tests/unicodedata_test.py

Fixes https://github.com/fonttools/fonttools/issues/1737

[unicodedata] map Zmth<->math in ot_tag_{to,from}_script

---

Lib/fontTools/designspaceLib/__init__.py
Tests/designspaceLib/designspace_test.py

I find myself doing this often enough that I decided to upstream it :)

[designspaceLib] Add DS.getAxisByTag and refactor getAxis

---

Lib/fontTools/pens/ttGlyphPen.py
Tests/pens/ttGlyphPen_test.py

Fixes https://github.com/fonttools/fonttools/issues/2913

[ttGlyphPen] Add outputImpliedClosingLine argument

---

Lib/fontTools/varLib/instancer/__init__.py
Lib/fontTools/varLib/instancer/names.py
Tests/varLib/instancer/instancer_test.py

Fixes https://github.com/fonttools/fonttools/issues/2959
A bit crude but I think I got it right.
Should add a test.

[instancer] Limit axis ranges to that of fvar

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Tests/feaLib/data/bug512.ttx

Fixes https://github.com/fonttools/fonttools/issues/2150 (see the discussion there).

[feaLib] Further merge inline single substitutions

---

Lib/fontTools/fontBuilder.py

Passed to addOpenTypeFeaturesFromString().

[fontBuilder] Add debug to addOpenTypeFeatures

---

Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ttx.py
Tests/ttx/ttx_test.py

Fixes https://github.com/fonttools/fonttools/issues/3019

[ttx] support reading font/xml file from standard input as '-'

---

Lib/fontTools/config/__init__.py
Lib/fontTools/otlLib/builder.py
Tests/varLib/data/test_results/InterpolateLayoutGPOS_7_diff.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_7_same.ttx
Tests/varLib/interpolate_layout_test.py

See the inline comment and option documentation

[otlib] Add a config option to write GPOS 7 lookups

---

Lib/fontTools/varLib/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/3045

[varLib] don't skip buildVFStatTable from DSv5 with 'STAT' info

---

Lib/fontTools/merge/layout.py
Lib/fontTools/merge/tables.py
Tests/merge/data/CFFFont_expected.ttx

Fixes https://github.com/fonttools/fonttools/issues/3069

[merge] Handle differing default/nominalWidthX in CFF

---

Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/__main__.py
Tests/ttLib/main_test.py

Fixes https://github.com/fonttools/fonttools/issues/17
/cc @behdad @rsms

add missing __main__.py file to ttLib package, plus some tests

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py
Tests/ttLib/tables/data/_g_l_y_f_instructions.ttx

Fix missing composite instructions in ttx

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

[feaLib] Allow empty aalt features 

---

Lib/fontTools/varLib/merger.py
Tests/varLib/merger_test.py
requirements.txt

Fixes https://github.com/fonttools/fonttools/issues/3111

[varLib/merger] Fix merging of SinglePos with pos=0

---

Lib/fontTools/misc/xmlReader.py
Tests/ttx/data/roundtrip_DSIG_split_at_XML_parse_buffer_size.ttx
Tests/ttx/ttx_test.py

Fixes https://github.com/fonttools/fonttools/issues/2614
First I add a test as reproducer and then follow up with the fix

xmlReader: join consecutive text data that had been cut by buffered xml parser

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

Remove empty sets and fixup Lookup.MarkFilteringSet to use the new indices.

[subset] Prune GDEF.MarkGlyphSetsDef

---

Lib/fontTools/subset/__init__.py

See https://github.com/fonttools/fonttools/pull/3114#pullrequestreview-1437266522

[subset] Make sure GDEF is processed before GSUB and GPOS

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/ttGlyphSet_test.py

Fixes https://github.com/fonttools/fonttools/issues/3189

[cubic-glyf] Fix drawPoints() contour ending with cubic offCurve

---

Lib/fontTools/misc/psCharStrings.py

According to [the CFF spec](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf), there is a three-byte integer format identical to the one in Type 2 CharStrings, so `encodeIntCFF` should support it.

Return three-byte operands from `encodeIntCFF`

---

Lib/fontTools/varLib/merger.py
Tests/varLib/merger_test.py

- A failing test for #3247
- Fix up NULL entry/exit records on merge, fixes #3247

Allow for merging of NULL anchors

---

Lib/fontTools/varLib/avar.py

Fixes https://github.com/fonttools/fonttools/issues/3275

[varLib.avar] New module to compile avar from .designspace file

---

Lib/fontTools/varLib/instancer/solver.py
Tests/varLib/instancer/solver_test.py

Fixes https://github.com/fonttools/fonttools/issues/3291

[instancer.solver] Fix case where axisDef < lower and upper < axisMax

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/NotoSansCJKjp-Regular.subset.ttx
Tests/subset/subset_test.py

see https://github.com/harfbuzz/harfbuzz/issues/4451
/cc @garretrieger @kojiishi

[subset] keep East Asian spacing vhal, halt, chws, vchw by default

---

Lib/fontTools/varLib/varStore.py
Tests/varLib/varStore_test.py

By creating a new major for each 65535.
I'll think about how to add test...

[varStore] Handle >65535 items per encoding

---

Doc/source/designspaceLib/xml.rst

Related: https://github.com/linebender/norad/issues/327

designspaceLib: Accept empty condition sets

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/instancer_test.py

Fixes https://github.com/fonttools/fonttools/issues/3322
cc @garretrieger @qxliu76

[instancer] Allow relaxed limits syntax

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/data/test_results/PartialInstancerTest2-VF-instance-100,100.ttx
Tests/varLib/instancer/data/test_results/PartialInstancerTest2-VF-instance-100,62.5.ttx
Tests/varLib/instancer/data/test_results/PartialInstancerTest2-VF-instance-400,100.ttx
Tests/varLib/instancer/data/test_results/PartialInstancerTest2-VF-instance-400,62.5.ttx
Tests/varLib/instancer/data/test_results/PartialInstancerTest2-VF-instance-900,100.ttx
Tests/varLib/instancer/data/test_results/PartialInstancerTest2-VF-instance-900,62.5.ttx

Recalc avgcharwidth after instancing

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/O_S_2f_2.py
Tests/ttLib/tables/O_S_2f_2_test.py

Fix os2 cp ranges error

---

Tests/misc/symfont_test.py
requirements.txt

[requirements] Add sympy

---

Lib/fontTools/varLib/interpolatable.py
Lib/fontTools/varLib/interpolatablePlot.py

This forms a minimum-spanning-tree over the master locations and compare two masters connected in the resulting tree. This reduces false-positives. Previously we were comparing each master to the first/base master.

Interpolatable mst

---

Lib/fontTools/varLib/interpolatable.py

Some moving code to functions.

Interpolatable refactor

---

Lib/fontTools/pens/recordingPen.py

Fixes https://github.com/fonttools/fonttools/issues/3342

[RecordPen] Add draw() and drawPoints() as alias to replay()

---

Lib/fontTools/misc/bezierTools.py
Tests/misc/bezierTools_test.py

- Replace linelike intersections with line-curve/line-line tests, fixes #3352
- Tests for #3352

linelike intersections

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/varLib_test.py

Fixes https://github.com/fonttools/fonttools/issues/3357

[featureVars] expose public method to addGSUBFeatureVariations to an existing VF

---

Lib/fontTools/pens/recordingPen.py
Lib/fontTools/ttLib/ttGlyphSet.py
Lib/fontTools/varLib/interpolatable.py
Lib/fontTools/varLib/interpolatableHelpers.py
Lib/fontTools/varLib/interpolatablePlot.py
Tests/ttLib/ttGlyphSet_test.py

Fixes https://github.com/fonttools/fonttools/issues/3361

Move LerpGlyphSet and lerp_recordings to more prominent places

---

Lib/fontTools/varLib/models.py
Tests/varLib/models_test.py

Undocumented and untested, I know.

[varLib.models] Add getMasterScalars

---

Lib/fontTools/varLib/interpolatable.py

Fixes https://github.com/fonttools/fonttools/issues/3383

[interpolatable] ensure parent directory for various output paths

---

Lib/fontTools/varLib/merger.py
Lib/fontTools/varLib/models.py
Tests/varLib/models_test.py

Faster than the alternative way to calculate them.

[varLib.models] Add interpolateFromValuesAndScalars()

---

Lib/fontTools/varLib/interpolatable.py
Lib/fontTools/varLib/interpolatablePlot.py

Fixes https://github.com/fonttools/fonttools/issues/3390
Untested.

[interpolatable] Support .glyphspackage

---

Lib/fontTools/otlLib/builder.py

Avoids ltag warning similar to: ae31d056051a28c39bc60fa2b827bc14efcef287

[otlLib] Pass ttFont to name.addName in buildStatTable

---

Tests/svgLib/path/path_test.py
requirements.txt
setup.py

Fixes https://github.com/fonttools/fonttools/issues/3418

don't restrict lxml<5, and run tests with latest 5.1.0

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Lib/fontTools/ttLib/tables/otTables.py
Tests/feaLib/data/spec4h1.ttx
Tests/feaLib/data/spec5d1.fea
Tests/feaLib/data/spec5d1.ttx
Tests/mtiLib/data/mti/gsubligature.ttx.GSUB
Tests/otlLib/builder_test.py

[feaLib] keep declaration order of ligatures within ligature set

---

Lib/fontTools/varLib/instancer/__init__.py

Fix tolerance value. Previously boolean value is passed to tolerance which is of float type.

fix bug in instancer iup optimization

---

Doc/source/designspaceLib/xml.rst
Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/designspaceLib/__main__.py
Lib/fontTools/subset/__init__.py
Tests/designspaceLib/data/test_avar2.designspace
Tests/designspaceLib/designspace_test.py

Adds a roundtripper, and fixes https://github.com/fonttools/fonttools/issues/3435

Designspace lib improvements

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/data/GSUB_5_formats.ttx
Tests/feaLib/data/GSUB_6_formats.ttx
Tests/feaLib/data/spec5f_ii_3.ttx

Fixes https://github.com/fonttools/fonttools/issues/2934
/cc @cmyr

[otlLib] choose most compact contextual lookup format

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/instancer_test.py

[instancer] drop explicit no-op axes from TupleVariations

---

Lib/fontTools/varLib/interpolatableHelpers.py

Ensure that scipy/numpy output is JSON-serializable

---

Lib/fontTools/varLib/cff.py

[varLib.cff] Restore and deprecate convertCFFtoCFF2

---

Lib/fontTools/ttLib/removeOverlaps.py

[ttLib.removeOverlaps] Support CFF table

---

Lib/fontTools/varLib/instancer/__init__.py

This reverts commit 969d09dcafd3669753e30060ccca7e5fd4c356cd. Fixes #3544.

Revert "[instancer] Fix name decision-making"

---

Lib/fontTools/ttLib/tables/_a_v_a_r.py

Fixes https://github.com/fonttools/fonttools/issues/3546

[avar] Fix assertion

---

Lib/fontTools/varLib/interpolatable.py
Lib/fontTools/varLib/interpolatableHelpers.py

Fixes https://github.com/fonttools/fonttools/issues/3597
Hummm. Only manually tested.

[varLib.interpolatable] Support discrete axes in .designspace

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/avar.py
Lib/fontTools/varLib/models.py
Tests/varLib/avar_test.py

https://github.com/Lorp/fencer/issues/25

[varLib.avar] Reconstruct mappings from binary

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

Set to True by default. Can be turned to False on the table.

[glyf] Add optimizeSize option

---

Lib/fontTools/cffLib/CFF2ToCFF.py
Lib/fontTools/cffLib/CFFToCFF2.py
Lib/fontTools/cffLib/transforms.py

So far in `CFFToCFF2`. Hoping to find what's so broken with `CFF2ToCFF` as well.

CFF convertors more fixes

---

Lib/fontTools/cffLib/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/3673

[`CFF2`] Lift `uint16 VariationStore.length` limitation

---

NEWS.rst

From https://github.com/fonttools/fonttools/pulls?q=is%3Apr+is%3Aclosed+closed%3A%3E2024-09-24

Update news.rst for next release

---

Lib/fontTools/misc/transform.py

Spotted by Cosimo. I convinced myself he is right, since a and b are zero in that branch.

[DecomposedTransform] Document and implement always skewY == 0

---

Lib/fontTools/__init__.py
NEWS.rst
setup.cfg
setup.py

I seem to have run the version bump on a branch not main :(

Bump version to 4.55.2.dev0

---

Doc/source/afmLib.rst
Doc/source/agl.rst
Doc/source/conf.py
Doc/source/config.rst
Doc/source/index.rst
Doc/source/merge.rst
Doc/source/mtiLib.rst
Doc/source/qu2cu/cli.rst
Doc/source/qu2cu/index.rst
Doc/source/t1Lib.rst
Doc/source/tfmLib.rst
Doc/source/ttx.rst
Doc/source/unicode.rst

This is part of refactoring the doc system to realign the different layouts found in different packages and make them consistent.
Small change to the overall config, plus updates to several of the single-page modules as test cases.

[Docs] update Sphinx config

---

Lib/fontTools/designspaceLib/__init__.py

Fixes https://github.com/fonttools/fonttools/issues/3710

Allow axisOrdering to be set to zero

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/duplicate_language_stmt.fea
Tests/feaLib/data/duplicate_language_stmt.ttx

And accumulate all of the declared lookups into the appropriate feature.
- fixes #3748

[feaLib] Allow duplicate script/language statements

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/otData.py
Tests/ttLib/tables/otTables_test.py

The "" marker is used when a custom converter expects a list. For DeltaValues, we expect a list as a single value, not a list to be enumerated in XML. So, None is appropriate here. Cryptic, I know...
Fixes https://github.com/fonttools/fonttools/pull/3757

[otData] Fix DeltaValue repeat value

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/spec9a2.fea
Tests/feaLib/data/spec9a2.ttx

Nobody told me this was missing!

[fealib] Support *Base.MinMax tables

---

Lib/fontTools/config/__init__.py
Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/__main__.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/_g_v_a_r.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/ttx.py
Tests/ttx/ttx_test.py

Use it for compiling faster-to-load glyf/gvar/VARC.

[config] Add OPTIMIZE_FONT_SPEED

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/spec9a2.fea

Fixes https://github.com/fonttools/fonttools/pull/3783#discussion_r1973878772

Allow comments inside BASE table MinMax statements

---

Doc/source/ufoLib/converters.rst
Doc/source/ufoLib/errors.rst
Doc/source/ufoLib/etree.rst
Doc/source/ufoLib/filenames.rst
Doc/source/ufoLib/glifLib.rst
Doc/source/ufoLib/index.rst
Doc/source/ufoLib/kerning.rst
Doc/source/ufoLib/plistlib.rst
Doc/source/ufoLib/pointpen.rst
Doc/source/ufoLib/utils.rst
Doc/source/ufoLib/validators.rst
Lib/fontTools/ufoLib/__init__.py
Lib/fontTools/ufoLib/converters.py
Lib/fontTools/ufoLib/errors.py
Lib/fontTools/ufoLib/etree.py
Lib/fontTools/ufoLib/filenames.py
Lib/fontTools/ufoLib/glifLib.py
Lib/fontTools/ufoLib/kerning.py
Lib/fontTools/ufoLib/utils.py

Changes to ufoLib documentation.

[Docs] ufoLib documentation

---

README.rst

This Pull Request fixes a typographical error in the README.md file.
Corrected "Acknowledgements" to "Acknowledgments" in the README.md file.
Corrected "licence" to "license" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.

Remove typo

---

Doc/source/designspaceLib/xml.rst
Lib/fontTools/designspaceLib/statNames.py

Clarify user expectations for getStatNames

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/CursivePosSubtable.fea
Tests/feaLib/data/CursivePosSubtable.ttx
Tests/feaLib/data/MarkBasePosSubtable.fea
Tests/feaLib/data/MarkBasePosSubtable.ttx

Add support for subtable statements to cursive and mark to base lookups.

[feaLib] Support subtable statements in more lookups

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/MarkLigPosSubtable.fea
Tests/feaLib/data/MarkLigPosSubtable.ttx
Tests/feaLib/data/MarkMarkPosSubtable.fea
Tests/feaLib/data/MarkMarkPosSubtable.ttx

[feaLib] Support subtable breaks in MarkToLigPos and MarkToMarkPos lookups

---

Lib/fontTools/varLib/instancer/__init__.py

Also add a TODO for a bug in that code.
Fixes https://github.com/fonttools/fonttools/issues/3827

[instantiate/cff2] Fix vsindex of Private dicts when instantiating

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

This matches AFDKO, and fontc will match this.

[feaLib] Error on conflicting ligature rules

---

Lib/fontTools/unicodedata/__init__.py
Tests/unicodedata_test.py

Fixes https://github.com/googlefonts/fontmake/issues/1152
https://github.com/harfbuzz/harfbuzz/blob/50debc3720f248e029cef8c2a5b822b4f2407ec0/src/hb-common.cc#L631-L632

[unicodedata] Add Garay script to RTL_SCRIPTS

---

Lib/fontTools/misc/sstruct.py

Micro optimization sstruct

---

Lib/fontTools/ttLib/sfnt.py
Lib/fontTools/ttLib/tables/S__i_l_f.py
Lib/fontTools/ttLib/tables/T_S_I__1.py
Lib/fontTools/ttLib/tables/T_S_I__5.py
Lib/fontTools/ttLib/tables/_c_m_a_p.py
Lib/fontTools/ttLib/tables/_c_v_t.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/_h_d_m_x.py
Lib/fontTools/ttLib/tables/_l_o_c_a.py
Lib/fontTools/ttLib/tables/_p_o_s_t.py
Lib/fontTools/ttLib/tables/otBase.py
Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/ttLib/tables/sbixStrike.py
Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ttLib/woff2.py

Micro optimizations in ttLib

---

Lib/fontTools/cffLib/CFF2ToCFF.py
Lib/fontTools/cffLib/transforms.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/varLib/instancer/__init__.py

Improve CFF2ToCFF a bit.
Doesn't touch CFFToCFF2 yet. That's much more broken. https://github.com/fonttools/fonttools/issues/3521

Cff2cff improvements

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

See https://github.com/harfbuzz/harfbuzz/issues/5499 and the corresponding HarfBuzz PR https://github.com/harfbuzz/harfbuzz/pull/5502

[subset] Fix shaping behaviour when pruning empty mark sets

---

Lib/fontTools/ttLib/tables/_p_o_s_t.py
Tests/ttLib/tables/_p_o_s_t_test.py

See https://github.com/fonttools/fonttools/pull/3809/files#r2314221887

Speed up post.build_psNameMapping

---

Lib/fontTools/subset/__init__.py

Subsetting sometimes creates duplicate features, remove them during post processing. See also https://github.com/harfbuzz/harfbuzz/pull/5494

[subset] remove duplicate features

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/TestBASE.ttx
Tests/subset/data/expect_BASE.ttx
Tests/subset/subset_test.py

I don't have push access to the repo, but I've rebased #1866 without conflicts so hopefully we can get this merged 🙏

Pass BASE table through subsetter by default
