Lib/fontTools/ttLib/tables/_n_a_m_e.py

I got this error:
File "C:\Python34\Lib\site-packages\FontTools\fontTools\ttLib\tables\_n_a_m_e.py", line 64, in compile
stringData = stringData + name.string
TypeError: can't concat bytes to str
`py23.bytesjoin` should fix it.
Cheers,
Cosimo

[_n_a_m_e] fix "can't concat bytes to str" error in python 3

---

Lib/fontTools/ttLib/tables/_p_o_s_t.py

I am not strong with font tables but this commit is a try to fix small bug and catch case when accessing array item out of range

Handle the exception of IndexError when list item access is out of range

---

Lib/fontTools/misc/macCreatorType.py

the function "getMacCreatorAndType" contains a workaround to address a bug in `GetCreatorAndType` function from the `MacOS` module.
On the Intel platform with 'little endian' byte order, the function would return strings in reverse order.
A comment in fontTools source code links to a bug report made by Just himself on the Python issue tracker (http://bugs.python.org/issue1594). They say the bug was fixed in a later python revision (this was 2009!).
I found out that the bug is still there until Python version 2.6.9, but it was finally fixed with Python 2.7.0 (I had to install both and test them on my mac).
The current patch will limit the workaround to Python versions less than 2.7 (i.e. basically Python 2.6.x, since earlier versions are no longer supported either).
The patch seem to fix …

[macCreatorType] return correct creator/type on Python 2.7

---

Lib/fontTools/misc/macCreatorType.py

I know nowadays one no longer needs to set the creator and type on a mac, but because we already fixed the "getting" part, we may as well fix the "setting" one...

[macCreatorType] disable workaround in py27 for setting as well getting

---

Lib/fontTools/misc/py23.py

I drop this here in case anybody may be interested.
As you know, when working with non-BMP unicode characters on a Python 2 which was built with UCS-2 Unicode support (i.e. the so called "narrow" builds), then the built-in `unichr` and the corresponding `ord` functions are limited to the range(0x10000). This is the case of most Python 2 configurations, including the OS X system Python and the Windows installer from Python.org.
This is quite annoying, given that Python 3 is always configured with UCS-4 support.
The py23 compatibility layer inside the misc sub-package could be the right place to add two simple workarounds which extends the unichr and byteord range to the full Unicode (0x110000), even on narrow Python 2 builds.
For example, think about looking up the built-in unicodedata …

[py23] simulate "wide" unichr and ord on "narrow" UCS2-only Python 2

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

there's a little typo in the warning message which prints the number of glyphs which are assigned a dummy glyph name.

[glyf] fixed 'noname'

---

Lib/fontTools/inspect.py
Lib/fontTools/merge.py
Lib/fontTools/subset.py
Lib/fontTools/ttx.py
setup.py

This patch addresses issue https://github.com/behdad/fonttools/issues/272
If setuptools raises an ImportError, then it falls back to the old distutils method.
I modified the four scripts so that they can work as setuptools 'console_scripts', in which the main function takes no arguments.
I also added an empty identifier "" in the 'packages' argument of setup function, otherwise the 
standalone sstruct.py and xmlWriter.py module -- which we have put back at the root of Lib for legacy -- would not be correctly installed.
I also removed py2exe since that is made redundant by the setuptools 'console_scripts' approach. This in fact will automagically create Windows executables (.exe) for each script using the specified entry point (I think this is really cool!).
Finally, I removed the custom …

[setup.py] use setuptools if available, or fall back to distutils

---

Lib/fontTools/ttx.py

This addresses https://github.com/behdad/fonttools/issues/82
I just added a 'long' option named "--unicodedata". The short "-u" doesn't make much sense, I think...

[ttx] add "--unicodedata" option for custom UnicodeData.txt

---

Lib/fontTools/misc/xmlWriter_test.py
Lib/fontTools/ttLib/tables/_l_t_a_g_test.py

@brawer the explicit "\n" newline separator was making some of the unittests fail on Windows, where python uses "\r\n" instead. I replaced them with `os.linesep`.
cheers,
C.

fix xmlWriter and _l_t_a_g tests failing on Windows because of \r\n

---

Lib/fontTools/ttLib/tables/_g_v_a_r.py
Lib/fontTools/ttLib/tables/_g_v_a_r_test.py

After round-tripping through TTX, the font rendering of MacOS X 10.9.5 can display
Skia.ttf, BuffaloGalRegular.ttf and JamRegular.ttf just fine including glyph variations.
Screen shot:

[GX] Support 'gvar' table

---

Lib/fontTools/misc/encodingTools.py
Lib/fontTools/misc/timeTools.py
Lib/fontTools/ttx.py

This was discussed some time ago both on the [mailing list](https://groups.google.com/forum/#!searchin/fonttools/modified/fonttools/Q4X9wDz8YLA/tfnTWwjTlawJ
) and here https://github.com/behdad/fonttools/issues/46.
With this patch, the default behavior would be that ttx uses the TTX file modified timestamp as the OpenType font's `head.modified` value.
Optionally, one can also have the timestamp recalculated based on the current time (though I don't see why one would like to do that...)
Since "-t" is taken, I used another long option, "--recalc-timestamp", i.e. the same used in pyftsubset.
Please, let me know if think the TTX file modification time shouldn't be the default.
Thanks.
C.

[ttx] use TTX mtime for 'modified' (default), optionally "--recalc-timestamp"

---

Doc/documentation.html
Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_a_v_a_r.py
Lib/fontTools/ttLib/tables/_a_v_a_r_test.py

When using TTX to inject a distorting ‘avar’ table into Skia.ttf:
<segment axis="wdth">
<mapping from="-1.0" to="-1.0"/>
<mapping from="-0.1" to="-1.0"/>
<mapping from="0" to="0"/>
<mapping from="0.1" to="1.0"/>
<mapping from="1.0" to="1.0"/>
</segment>
MacOS X renders a range of widths as one would expect:

[GX] Support 'avar' table

---

Lib/fontTools/ttx.py

after https://github.com/behdad/fonttools/pull/279, ttx was creating an empty file every time one listed the  table directory.

[ttx] don't create output file if action is 'ttList'

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Lib/fontTools/ttLib/tables/_n_a_m_e_test.py

Useful for generating XML comments when tables refer to name IDs.
For example, XML for a named instance in an ‘fvar’ table is easier
to read when it says  in addition to nameID="258".

Helper function to find a debug string for a name

---

Lib/fontTools/ttLib/tables/E_B_D_T_.py

Fixes https://github.com/behdad/fonttools/issues/295, by getting the `dirname()` of the output TTX file.

[E_B_D_T_] make 'bitmaps' directory in the same location as output TTX file

---

Lib/fontTools/ttLib/tables/_a_v_a_r.py
Lib/fontTools/ttLib/tables/_a_v_a_r_test.py
Lib/fontTools/ttLib/tables/_f_v_a_r.py
Lib/fontTools/ttLib/tables/_f_v_a_r_test.py
Lib/fontTools/ttLib/tables/_g_v_a_r.py
Lib/fontTools/ttLib/tables/otData.py

In the previous table-driven implementation, client code had to
know the internals of the ‘fvar’ structure for correctly adding
variation axes to a font. In the new implementation, clients
do not have to futz around with binary offsets (which makes it
more likely that tools build correct fonts).

[GX] Make it easier to construct ‘fvar’ tables from code

---

Lib/fontTools/ttLib/tables/_m_e_t_a.py
Lib/fontTools/ttLib/tables/_m_e_t_a_test.py

Because I could not find any fonts with “dlng” (design languages) or
“slng” (supported languages) sub-tables, these are not implemented yet.
We could easily implement them according to spec, but it is unclear
to what extent the spec is matching reality.

Implement Apple’s “meta” table

---

Lib/fontTools/cffLib.py
Lib/fontTools/misc/xmlWriter.py

[cffLib] Fix encoding of Notice and Copyright values in XML on Python 2

---

Lib/fontTools/misc/xmlReader.py

If no "encoding" argument is provided to Python 3 `open` built-in function, the default platform's encoding will be used when decoding bytes to unicode. On Windows, this is usually `cp1252`.
So, we need to explicitly open xml files for reading with UTF-8 encoding (the xmlWriter always writes UTF-8 by default).
We can use the `io.open` function, which is a backport of Python 3 default file interface, and has therefore an `encoding` argument which can be used to decode the file's bytes into unicode strings.
The input of expat's xml parser, in turn, should consist of bytes, so we encode unicode strings to UTF-8 before passing them to the parser.
This should fix the first issue reported here: https://github.com/behdad/fonttools/issues/323

Xml reader utf8

---

Lib/fontTools/misc/fixedTools.py
Lib/fontTools/misc/fixedTools_test.py

on python 3, the `round(1.0)` returns `1` (integer), whereas on python 2 it returns `1.0` (float).

[fixedTools] make sure fixedToFloat function returns float on both python 2 and 3

---

Lib/fontTools/misc/xmlReader.py
Lib/fontTools/misc/xmlReader_test.py

In commit 6b4567f, I submitted a patch to fix a `UnicodeDecodeError` raised by xmlReader on Windows Python 3 (https://github.com/behdad/fonttools/issues/323). I had xmlReader open files (still in "text" mode) with UTF-8 encoding, to prevent Windows from implicitly opening files using the locale cp1252 encoding.
However, the expat XML parser seems to require bytestrings as input. I you feed unicode strings, these will be implicitly converted to bytes using 'ascii' encoding. So in commit fe76598, I ended up re-encoding to UTF-8 the unicode strings as read from the file, before passing them to the parser.
I think it would be simpler and cleaner if we just open the file as `rb`, so we read in bytes and feed those directly to the expat parser. The latter will take care of applying the correct …

[xmlReader] open file for reading bytes (and revert two previous commits...)

---

Lib/fontTools/misc/xmlReader_test.py
Lib/fontTools/misc/xmlWriter.py
Lib/fontTools/misc/xmlWriter_test.py

by explicitly escaping any carriage returns `\r` that occurr within XML element tags, we make sure that TTX can roundtrip name records containing Windows-style line endings (`\r\n`).
If we don't escape carriage returns, these will get automatically normalised into Unix-style line endings `\n` by the expat XML parser.
See https://github.com/behdad/fonttools/issues/318.

[xmlWriter] escape carriage returns '\r' using XML character entity '&13#;'

---

Lib/fontTools/misc/psLib.py
Lib/fontTools/misc/py23.py
Lib/fontTools/misc/xmlWriter_test.py
Lib/fontTools/pens/pointInsidePen_test.py
Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/macUtils.py
Lib/fontTools/ttLib/tables/C_F_F_.py
Lib/fontTools/ttLib/tables/S_V_G_.py
Lib/fontTools/ttLib/tables/_a_v_a_r_test.py
Lib/fontTools/ttLib/tables/_f_v_a_r_test.py
Lib/fontTools/ttLib/tables/_g_v_a_r_test.py
Lib/fontTools/ttLib/tables/_l_t_a_g_test.py
Lib/fontTools/ttLib/tables/_m_e_t_a_test.py
Lib/fontTools/ttLib/tables/_n_a_m_e_test.py

This fixes issue #328, whereby an exception is raised when running `traceback.print_exc` function.
The error occurs because the `file` argument is expecting a stream of `str` objects: on Python 2, this must be a stream of *bytes*, whereas on Python 3 it must be a stream of *unicode* strings.
Currently we are using the name `StringIO` to mean an in-memory stream of bytes on both python versions. 
This patch redefines the import statements inside `py23` so that, on both 2 and 3:
- the name `BytesIO` will unambiguously mean a stream of bytes;
- the name `UnicodeIO` means a stream of unicodes.
Finally, the name `StringIO` is declined in a version-specific sense: that is, as a stream of **bytes** on Python 2 and a stream of **unicodes** on Python 3. 
So we give streams a similar treatment as …

[py23] disambiguate bytes vs unicode in-memory streams

---

Lib/fontTools/ttLib/tables/_v_h_e_a.py

unlike with the `hhea` table, for the corresponding `vhea` table the `recalcBBoxes` attribute of TTFont was not checked, and the vertical bounds were always recalculated.
Fixes #336.

[_v_h_e_a] don't recalc vertical bounds if recalcBBoxes == False

---

Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/sfnt.py

I believe the current behaviour of `reorderTables` argument in `TTFont.save` function is wrong, or at least is a bit misleading.
It's clear what `reorderTables=True` means: i.e. set the table order to the one recommended by the OpenType specification.
However, when one sets `reorderTables=False`, one may wish that the "original" input font's table order would be kept upon saving. However, that's not the case because the input font's table order as stored in the SFNTReader entries `offset` attribute is simply ignored. Actually, the final order is just random. It basically is whatever order fonttools finds more convenient when recompiling the tables: i.e. based on whether a table has been loaded, and whether it's compilation depends on some other table being compiled first.
OK, I know the …

change behaviour of reorderTables: allow True, None and False

---

.travis.yml

I use pip `--global-option` to run distutils `build_ext` command with a custom `--libraries=stdc++` argument when compiling brotli for pypy3.
This should fix the issue with importing the brotli module in pypy3, which in turn makes it skip the woff2 tests: https://github.com/behdad/fonttools/issues/339
Finger crossed...

[travis] compile Brotli using `build_ext --libraries=stdc++` on pypy3

---

Lib/fontTools/ttx.py

This slightly modifies the way invalid options are handled, to make it more consistent and avoid repetition.
Currently there are several print statements followed by sys.exit; with this patch, I raise `getopt.GetoptError`, catch the exception only once inside `main`, and print the error message to stderr (followed by the `usage()` string).

[ttx] raise GetoptError and print messages to sys.stderr

---

Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/tables/_c_m_a_p.py
Lib/fontTools/ttLib/tables/_c_m_a_p_test.py
Lib/fontTools/ttLib/woff2.py
Lib/fontTools/ttLib/woff2_test.py

When a font supplies no glyph names in its 'post' table, fontTools
builds synthetic glyph names by reversing the 'cmap' table.
After this change, the library looks at all 'cmap' subtables for
Unicode, irrespective of format or platform. For example, glyph #4
in NotoSansOldItalic-Regular.ttf gets now named "u10300" instead of
"glyph00004".
Moved the code for building a reversed 'cmap' table into the cmap class,
for easier testing.

Support non-BMP characters for synthetic glyph names

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/testdata/GSUB_3.ttx
Lib/fontTools/feaLib/testdata/language_required.ttx
Lib/fontTools/feaLib/testdata/spec4h1.ttx
Lib/fontTools/feaLib/testdata/spec5d1.ttx
Lib/fontTools/feaLib/testdata/spec5d2.ttx

Resolves https://github.com/brawer/fonttools/commit/df740092d990e441550bf33fcd8bd15f5ae3dbc9#commitcomment-13138084

[feaLib] Use fontTools wrapper class for otTable's GSUB/GPOS tables

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/testdata/GSUB_3.ttx
Lib/fontTools/feaLib/testdata/language_required.ttx
Lib/fontTools/feaLib/testdata/spec4h1.ttx
Lib/fontTools/feaLib/testdata/spec5d1.ttx
Lib/fontTools/feaLib/testdata/spec5d2.ttx
Lib/fontTools/ttLib/tables/otConverters.py

the `feaLib.builder.Builder.makeTable` is missing one level in the structure of OpenType layout tables.
`table.LookupList.Lookup` in GSUB is being built as a list of lookup *subtables* (e.g. `LigatureSubst`, `AlternateSubst`, etc.). Instead, it should be a list of `Lookup` objects, each having a `SubTable` attribute containing the list of subtables, as well as `LookupType`, `LookupFlag`, `SubTableCount`, etc.
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/otData.py#L88
@brawer this PR is just to show the issue with code, feel free to close this and fix it the way you like.
Thanks for the good work!

[feaLib] make LookupList.Lookup into a list of Lookup objects, not subtables

---

Lib/fontTools/ttLib/tables/_l_t_a_g.py
Lib/fontTools/ttLib/tables/_l_t_a_g_test.py

Before this change, TTX (when running in Python 2.7) would fail
to compile a font if the input contained an `ltag` section.
With Python 3, it worked perfectly fine even before this change.
Resolves https://github.com/behdad/fonttools/issues/357

Build ltag table also with Python 2.7

---

Lib/fontTools/subset.py
Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/ttLib/tables/otTables_test.py

Resolves https://github.com/behdad/fonttools/issues/355
For making sure that `pyftsubset` still works after this change,
I have done the following steps:
* invoked Adobe's `makeotf` tool to build a custom font with a
MultipleSubst lookup. This lookup decomposes two two ligatures,
`c_t` and `f_f_i`, into their respective components.
* invoked the `pyftsubset` tool to produce a subset font with just
the `c_t` ligature;
* checked with `ttx` that the newly produced subset font contains
the requested `c_t` ligature and its components `c` and `t`,
but does not contain not any of `f_f_i`, `f`, or `i`.

[otTables] Simplify API for MultipleSubst

---

README.md

for some reasons, this was removed in https://github.com/behdad/fonttools/pull/359
/cc @davelab6 @miguelsousa @benkiel

[README] reintroduce a "History" paragraph

---

Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/ttLib/tables/otTables_test.py

Fix a backwards compatibility problem introduced by https://github.com/behdad/fonttools/commit/1356a6775b174853e893484c737a9ee0bcf6d0fd (pull request https://github.com/behdad/fonttools/pull/364), where new versions of FontTools would not be able to process `<MultipleSubst>` elements in TTX files generated by older FontTools releases.
Resolves https://github.com/behdad/fonttools/issues/355.

Support TTX format for `MultipleSubst` of FontTools 3.0 and earlier

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/misc/testTools_test.py
Lib/fontTools/ttLib/tables/otTables_test.py

This should make the unit tests more readable, and it also prevents
failures where a changed fromXML() implementation fails to ignore
interspersed whitespace. This has recently caused some developer
nuisance; see https://github.com/behdad/fonttools/pull/367.
Instead of having a custom parser implementation, it would be nicer
to call the actual XMLReader. However, XMLReader has a deeply built-in
assumption that it is processing an entire TTX file. Changing this
assumption would certainly be possible, but it would need a re-write
of the XMLReader code; having a custom parser just for unit tests
seems less involved.

[otTables] Use XML snippets for testing fromXML() methods

---

.travis.yml

Python 3.5.0 was released a few days ago, and Travis already added support for it.
Let's see if it works...

[Travis] also test against newly released Python 3.5.0

---

Lib/fontTools/ttLib/tables/ttProgram.py

When dumping glyf table to XML with `disassembleInstructions`, if an exception is raised while decompiling one of its glyph programs, the whole process aborts.
With this patch, the disassembling will continue despite the exception, and the faulty glyph's bytecode will be dumped as hex string instead of assembly, preceded by the full exception traceback as an XML comment.
Fixes https://github.com/behdad/fonttools/issues/347

[ttProgram] if can't disassemble bytecode, warn and dump toXML as it is

---

Lib/fontTools/subset.py

The current argument parser in subset.py must strip out spaces in values, in order to allow specifying comma- or whitespace-separated lists (for example, cf. [line 2289](https://github.com/behdad/fonttools/blob/master/Lib/fontTools/subset.py#L2289))
Because of that, users cannot correctly specify table tags whose length is less than 4 by enclosing the space in quotes.
For example, 'SVG ' table will be alwyas dropped even if I pass `--drop-tables-='SVG '` and `--no-subset-tables+='SVG '`.
As a workaround, this patch removes the spaces from the 'SVG ' and 'cvt ' tags in the constant lists of the `Options` class, and it only tests that `tag.strip()` is contained in those list.
Of course, this also means `--drop-tables-='SVG '` is now the same as `--drop-tables-='SVG'` as far as the subsetter …

[subset] fix issue with tags containing spaces (e.g. "SVG ", "cvt ")

---

Lib/fontTools/ttLib/tables/_m_e_t_a.py
Lib/fontTools/ttLib/tables/_m_e_t_a_test.py

According to https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6meta.html
'dlng' design languages and 'slng' supported languages are comma-separated or comma-space-separated "augmented" BCP 47 language tags.
```xml
<hexdata tag="dlng">
4c61746e 2c477265 6b2c4379 726c2c41
726d6e2c 48656272 2c417261 622c5468
6169
</hexdata>
```
can be displayed as
```xml
<text tag="dlng">
Latn,Grek,Cyrl,Armn,Hebr,Arab,Thai
</text>
```

meta table: 'dlng' and 'slng' data is text

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Lib/fontTools/ttLib/tables/_n_a_m_e_test.py

The method takes a unicode `string`, `nameID`, `platformID`, `platEncID` and `langID`.
If the given name record already exists, its string is modified in place.
If it doesn't exist, a new record is created with the specified IDs and string.
As suggest by @brawer in https://github.com/anthrotype/fonttools/commit/380104c2288200aec1a7173162a3b3cfb29fc8f2#commitcomment-13534159

[name] add setName method to table__n_a_m_e

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_t_r_a_k.py
Lib/fontTools/ttLib/tables/_t_r_a_k_test.py
MetaTools/buildTableList.py
README.md

The internal structure of the new `table__t_r_a_k` looks like this: 
```python
table.__dict__ = {
'version': 1.0,
'format': 0,
'horizData': TrackData({
-1.0: TrackTableEntry(
{9.0: -10, 10.0: -30, 19.0: -63, 12.0: -60, 18.0: -63}, nameIndex=275),
0.0: TrackTableEntry(
{9.0: 15, 10.0: 0, 19.0: -25, 12.0: -5, 18.0: -25}, nameIndex=303),
1.0: TrackTableEntry(
{9.0: 140, 10.0: 130, 19.0: 115, 12.0: 125, 18.0: 115}, nameIndex=276)
}),
'vertData': TrackData()
}
```
Both `TrackData` and `TrackTableEntry` objects behave like dictionaries. They are nested inside each other, like a two-dimensional mapping: e.g., `table.horizData[-1.0][12.0] == -60`
Please let me know what you think,
Thanks.
/cc @jenskutilek @behdad @twardoch @moyogo @brawer 
Cf. https://github.com/behdad/fonttools/issues/375

[trak] add AAT 'trak' table support

---

Lib/fontTools/misc/psLib.py
Lib/fontTools/t1Lib.py

This is only a temporary fix to revert a change which broke support for parsing Type1 fonts in Robofont. It turns out the whole t1Lib and psLib are not working with python3 because of other issues (as usual, unicode vs bytes), so they will need more than simply renaming StringIO to BytesIO...

[psLib] revert to using StringIO.StringIO; temporarily drop support for Python3

---

Lib/fontTools/ttLib/tables/_p_o_s_t.py

the third (2015) edition of ISO/IEC 14496-22 "Open Font Format" increased
the limit from 32767 to 65535 (and thus eliminated the reserved numbers).
(`array.array` will take care of raising the right `OverflowError` exception
so we don't need any further checking.)
Fixes https://github.com/behdad/fonttools/issues/348

[_p_o_s_t] remove max indices "reserved for future use"

---

Lib/fontTools/misc/macCreatorType.py

in version 0.6.4 as installed on OS X 10.10's built-in python2.7 (inside lib/extras), `xattr.getxattr` function raises `KeyError` whenever it cannot get the requested extended attribute. In the latest version, as available from PyPI (0.7.8), `xattr.getxattr` raises `IOError` instead. So we need to catch both.
Fixes issue in https://github.com/googlei18n/nototools/issues/113

[macCreatorType] fix KeyError raised by old version of xattr module

---

Lib/fontTools/misc/py23.py

When one does `from fontTools.misc.py23 import *`, everything seems to work fine.
However, linters will complain when one uses the asterisk to import all names from a module, since they can't detect when names are left undefined -- asterisks are greedy and will eat all names!
If one avoids the asterik and attempts to import explicitly, like in `from fontTools.misc.py23 import basestring`, the problem then is that, if `py23` does not re-define the name -- e.g. under python2 `basestring` or `unicode` are built-ins -- then the import statement raises `ImportError`.
The same happens for the `unichr` function on a "wide" Python 2 build (i.e. on in which `sys.maxunicode == 0x10FFFF`).
Now, to work around this, we need to re-assign those built-ins to their very same names. This may look silly, …

[py23] fix ImportError when trying to import names when already defined

---

setup.py

Broken since 29d7edf76f9ca888d120f2018e08e2b337ba7cf8.

Fix setup.py to install fontTools.subset

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/subset_test.py
Lib/fontTools/subset/testdata/TestCLR-Regular.ttx
Lib/fontTools/subset/testdata/expect_keep_colr.ttx

Add support for subsetting COLR table.
The CPAL table does not need subsetting, but unused palettes should be
pruned, this is not implemented however as it depends on COLR table,
which in turn will not be updated after pruning CPAL.

[subset] Support subsetting MS color tables

---

Lib/fontTools/ttLib/tables/V_D_M_X_.py

VDMX groups are dictionaries, hence unsorted. Here I normalize the XML output by sorting them by key (yPelHeight), and also use tuples instead of keyword args so that yPelHeight always appears first in each record.
It's a minor change that won't break the previous API.

[V_D_M_X_] sort records by yPelHeight when writing toXML

---

Lib/fontTools/feaLib/builder_test.py

There are two functions called `test_alternateSubst()` in feaLib/builder_test.py.
The second `test_alternateSubst()` should be called `test_multipleSubst()`.

feaLib: misnamed function in builder_test.py

---

Lib/fontTools/misc/xmlReader.py
Lib/fontTools/misc/xmlReader_test.py
Lib/fontTools/ttLib/__init__.py

`XMLReader` can now read from open files or stream objects, similar to `XMLWriter`.
If input is a path name, the file is closed automatically as the read completes (this is to keep the current behaviour).
However, when input is an already open file or file-like object (e.g. "-" is interpreted as standard input), then the object is kept open, unless the user explicitly closes it with `reader.close()`.
I also fixed a typo (`setlabel` -> `setLabel`) in a method call to `ProgressPrinter`. I wonder how many people are still using the progress bar API nowadays...
Fixes #404.

make XMLReader accept file objects

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

Fixes https://github.com/behdad/fonttools/issues/410.
Also, deletes empty `self.data` lingering around after decompile.
cf. https://github.com/behdad/fonttools/commit/ecbe8f2c37021605672af3c9d4f6b0f6e73df592#commitcomment-14464893

_g_l_y_f: expand glyphs inside `compile` if recalcBBoxes==True

---

Lib/fontTools/ttx.py

so that you don't need to do `-t "CFF "` anymore.
Fixes https://github.com/behdad/fonttools/issues/265

ttx: pad tags with space if length is less than 4

---

.appveyor.yml
run-tests.sh

Currently we only run tests on Ubuntu Linux via Travis.
I'd like to also run the tests on Windows Python, since there are sometimes differences in the implementations (e.g. newlines, binary vs text, etc.).
This adds a `.appveyor.yml` to set up the Appveyor CI.
I'm not sure if I can enable the project myself or @behdad needs to do it on his side.
Anyway, here's the link to the current build running from my fork:
https://ci.appveyor.com/project/anthrotype/fonttools/build/1.0.29
(fingers crossed)

add Appveyor support

---

.travis.yml
.travis/install.sh
.travis/run.sh
Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/tables/_t_r_a_k.py
tox.ini

This is to enable testing on OS X Python with Travis, alongside Linux.
Unfortunately the Python runtime is not yet available on Travis for OS X environment (cf. https://github.com/travis-ci/travis-ci/issues/2312).
Therefore, I had to use [pyenv](https://github.com/yyuu/pyenv) to downlaod and install the various Pythons (3.3, 3.4, 3.5 and pypy) which are not already installed on OS X. For 2.7 I test both the default system Python 2.7.5 that comes with OS X 10.9 (the default Travis OS X machine), and the Python 2.7.10 which is pre-installed on El Capitan.
For setting up the virtual environment, downloading the requirements and running the tests I use [tox](https://tox.readthedocs.org/en/latest/). This integrates nicely with [pytest](https://pytest.org/), which in turn can discover and run …

Travis multi-os setup

---

Lib/fontTools/misc/macRes.py

on 32-bit Python, BytesIO's `read` or `seek` methods can raise OverflowError if the integer passed as an argument exceeds `PY_SSIZE_T_MAX` (i.e. 214748364, cf. `from _testcapi import PY_SSIZE_T_MAX`).
Fixes https://github.com/behdad/fonttools/issues/436

macRes: fix OverflowError while reading resource on 32-bit Python

---

setup.py

The 'xml.parsers.expat' module has been a part of Python's Standard Library since version 2.0. Link: https://docs.python.org/2/library/pyexpat.html#module-xml.parsers.expat . FontTools requires Python 2.7, or Python 3.3 or later. Checking for the existence of this module is not necessary anymore.

Remove obsolete code - 'xml.parsers.expat' is part of Python's stdlib

---

Lib/fontTools/misc/timeTools.py

This is meant to normalise the output of the built-in `time.asctime()` across different platforms and Python versions.
In Python 3.x, the day of the month is right-justified, whereas on Windows Python 2.7 it is padded with zeros.
The reason is that, in the `timemodule.c` on CPython 2.x, they invoke the built-in C runtime's `asctime` function (which is implemented differently on Unix and Windows). In CPython 3.x they have defined a custom `_asctime` function to work around this.
Note that we cannot use `time.strftime` to format the time tuple, since that returns a locale dependent string, wheres here we are trying to replicate the default `asctime` behaviour, which is locale independent.
Fixes https://github.com/behdad/fonttools/issues/455

timeTools: define platform-independent 'asctime' function

---

setup.py

Without otlLib in the setup file it gives the error 
```python
ImportError: No module named otlLib
```
when using defcon library.

Added otlLib

---

Lib/fontTools/misc/py23.py
Lib/fontTools/misc/py23_test.py
run-tests.sh

In this patch, I define an `open` function in py23.py which wraps around the `io.open` function.
In Python 2, `io.open` is a backport of Python 3's `open`. This is much better than the built-in python2 `open`. (In Python 3, `io.open` is simply an alias of its built-in `open` function).
Using `io.open` will enable us, for example, to use the `encoding` argument without needing to call `codecs.open`, or re-opening the standard I/O streams in binary mode, so that we can pipe binary data through them.
```python
binary_stdin = open(sys.stdin.fileno(), mode='rb', closefd=False)
binary_stdout = open(sys.stdout.fileno(), mode='wb', closefd=False)
```
The problem is, the statement above would work fine with the vanilla `io.open` function on Python 3, as well as on Python 2 on the "unix" platform. …

[py23] add wrapper for io.open

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/O_S_2f_2.py
Lib/fontTools/ttLib/tables/O_S_2f_2_test.py

this is the same as https://github.com/behdad/fonttools/pull/191
all the merge, rebase or cherry-pick would fail, so I was forced to redo the changes manually from a new branch.
From the previous thread, the consensus was that we would have this option always on in the subsetter, and maybe we could think about having it in ttLib later.
@behdad in the other PR about OS/2 fsFirstCharIndex, you suggested to use isUnicode() method of cmap subtables. I wonder if I should use that here as well. Currently I'm only checking platformID 3 and platEncID 1 and 10, because those are the only ones which are mentioned in the relevant [paragraph](http://www.microsoft.com/typography/otspec/os2.htm#ur) of OS/2 specification.

[subset] add option to prune unused ulUnicodeRange bits

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/sfnt.py
Lib/fontTools/ttx.py

Fixes #491.
The `zopfli` extension module which is required to use the new option can be installed with this pip command:
```
pip install -v git+https://github.com/anthrotype/py-zopfli#egg=zopfli
```
The official one currently available on PyPI uses an outdated copy of Zopfli source code and is not compatible with Python 3 nor with Windows.
While working on this, I noticed that pyftsubset's `canonical_order` default value was still set to `False`, whereas it should have been set to `None`.
The meaning of the related `reorderTables` argument of `TTFont.save` method in fact changed a while ago with commit 6ba67ab.
When `reorderTables` is set to False, the input font's original table order is "kept": which still means performing some sort of reordering. If one wishes to avoid any reordering …

add --with-zopfli option to pyftsubset and ttx

---

Lib/fontTools/misc/psCharStrings.py

Fixes https://github.com/behdad/fonttools/issues/492
using @HinTak's example:
```
107 53.400390625 166.19900512695312 hstem
174.60000610351562 163.80099487304688 vstem
338.3999938964844 142.8000030517578 rmoveto
0 21.600006103515625 -6.29998779296875 18.20001220703125 -12.600006103515625 14.79998779296875 -12.600006103515625 14.800003051757812 -18.100006103515625 7.4000091552734375 -23.5999755859375 0 -28.400009155273438 0 -22.199996948242188 -8.70001220703125 -16 -17.399993896484375 -16 -17.399993896484375 -8 -20.300003051757812 0 -23.199996948242188 0 -21.600006103515625 6.5 -18.599609375 13 -15.6005859375 13 -15.599609375 18.29998779296875 -7.7998046875 23.600006103515625 0 rrcurveto
28 0 21.899993896484375 9 15.800018310546875 18 15.79998779296875 18 7.899993896484375 …
```

[psCharStrings] use fixedToFloat to use the shortest decimal representation

---

Lib/fontTools/mtiLib/__init__.py

I think this was mistakenly left out of
b62f5509524a49101ab6f211f1c3b63458f52f5e

Replace one last call to debug() in mtiLib

---

Lib/fontTools/pens/ttGlyphPen.py

The glyf table will handle rounding when compiling, so this is
unnecessary.
Based on discussion at https://github.com/googlei18n/cu2qu/pull/19

[TTGlyphPen] Don't cast values to int

---

Lib/fontTools/pens/ttGlyphPen.py

Unlike simple glyphs (i.e. with contours) which must always have `instructionLength` field, the latter is optional in composite glyphs and depends on whether `WE_HAVE_INSTR` flag is set:
https://www.microsoft.com/typography/otspec/glyf.htm
In the previous code, the `TTGlyphPen` was adding an empty `program` attribute to all new glyphs, including composites, whereas it should only do it for simple glyphs.
For example, if you take Roboto-Regular.ttf from here:
https://github.com/google/roboto/releases/tag/v2.129
The font (unhinted) was compiled using the ttGlyphPen. It has 1434 composite glyphs. For each of them, a USHORT value for the number of instructions (0) is written, so the binary ttf is 2.868 KB greater than
what it should be.
/cc @jamesgk

[ttGlyphPen] only add empty ttProgram to simple glyphs, not to composites

---

Lib/fontTools/pens/ttGlyphPen_test.py
Lib/fontTools/ttLib/tables/DefaultTable.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/_t_r_a_k.py
Lib/fontTools/ttLib/tables/otBase.py
Lib/fontTools/ttLib/tables/ttProgram.py

`_g_l_y_f.Glyph` objects have handy `__eq__` and `__ne__` methods. However their `program` attribute did not, so it was using `object`'s default `id(self) == id(other)`, which returns False even when the content of two Program instances is the same.
So I added that.
While doing this I noticed that there are other classes in fonttools which similarly implement `__eq__` and `__ne__`, but they have a problem in that, `__ne__` is defined as `not self.__eq__(other)`, but when the `type(self) != type(other)`, then `__eq__` will (correctly) return `NotImplemented`, and thus `__ne__` will return `not NotImplemeted`, which is always False no matter what.
This can lead to illogic results like:
```python
>>> from fontTools.ttLib.tables.DefaultTable import DefaultTable
>>> t = DefaultTable('test') …
```

test for NotImplemented in __ne__; add __eq__ and __ne__ to ttProgram.Program

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/testdata/lookupflag.fea
Lib/fontTools/feaLib/testdata/lookupflag.ttx

According to the spec:
> The lookupflag attribute defaults to 0 at the start of a feature
> block.
>
> The lookupflag attribute stays the same until explicitly changed, until
> a lookup reference statement is encountered that changes it, until the
> script is changed, or until the end of the feature.
This is an attempt to fix this by resetting the lookupflag at the start
and end of feature/lookup blacks. I’m not sure if resetting it in lookup
blocks is correct (my reading of the spec suggests it is not), but one
needs to test this against makeotf and see how it behaves here.

Fix handling of default lookupflag

---

Lib/fontTools/feaLib/testdata/spec9e.fea
Lib/fontTools/feaLib/testdata/spec9e.ttx

Feature File Spec itself was fixed in https://github.com/adobe-type-tools/afdko/pull/110

[feaLib] Fix typo in testdata/spec9e.*

---

Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/testdata/name.fea

this the same as what makeotf currently does for nameIDs between 1 and 6.
http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.e
> Note that ids 1-6 (Family, Subfamily, Unique, Full, Version, and FontName) are reserved by the implementation and cannot be overridden; doing so will elicit a warning message and the record will be ignored.
I can see why makeotf would reserve those nameIDs, since they are auto-generated from the FontMenuNameDB file. However, in feaLib we could easily allow users to override those as well, if the spec did not explicitly forbid that...

[fealib] ignore nameIDs 1-6 in parser and issue a warning

---

.appveyor.yml
.appveyor/with-compiler.cmd
dev-requirements.txt
tox.ini

More info in the commit messages. In short, we were not actually testing the 64-bit Python 3.4, as tox was picking up the 32-bit interpreter... 😭

fix Appveyor Python 3.4 64-bit build

---

.coveragerc
.travis.yml
.travis/install.sh
.travis/run.sh
tox.ini

I really recommend that we use [coverage.py](http://coverage.readthedocs.org/en/coverage-4.0.3) to measure our test suite coverage. It's really cool.
We even have a badge on the homepage, so we'd better use it! :)
However that link leads nowhere... https://coveralls.io/r/behdad/fonttools
Perhaps @behdad created it in the past but then decided to close it?

run coverage.py on Travis and upload report to coveralls

---

Lib/fontTools/ttLib/tables/S_V_G_.py

Before, when compiling from XML, only `<colorPalettes></colorPalettes>` would be accepted.
Now, all of these pass compilation as well,
```xml
<colorPalettes>    </colorPalettes>
```
```xml
<colorPalettes />
```
```xml
<colorPalettes>
</colorPalettes>
```

[SVG] Better handling of empty <colorPalettes> element

---

.travis.yml
.travis/install.sh
.travis/run.sh
tox.ini

There are several issues with jython on the one end, and pip, virtualenv and tox, on the other.
Therefore, for now I just have Travis install the latest Jython 2.7.1 beta3 (the "stable" release 2.7.0 has even other problems), and run the `py.test` command from outside any virtualenv or tox.
Also, since 22 tests are failing, I decided to ignore the non-zero exit code from `py.test` command, so the Jython build will always pass... I know, it feels a bit like cheating, but at least we now can see what tests are failing, and we can work toward fixing them -- without anxieties ;)

add jython support for Travis CI (still experimental)

---

Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/lexer_test.py

fealib: allow newlines in string literals (and skip over them)

---

Lib/fontTools/ttLib/tables/S_V_G_.py

Something simple like this was failing:
```python
from fontTools import ttLib
fontFilePath = 'font-with-SVG-table.ttf'
font = ttLib.TTFont(fontFilePath)
print font['SVG ']
```
I took a clue from the [CFF table code](https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/C_F_F_.py#L10).

[SVG] correct __init__ method

---

Lib/fontTools/ttLib/tables/_s_b_i_x.py

Similar to #584.
In this case, making an **sbix** table from scratch required this `_s_b_i_x.table__s_b_i_x('sbix')`, which is redundant. With this change it's only necessary to do this `_s_b_i_x.table__s_b_i_x()`.

[sbix] correct __init__ method

---

Lib/fontTools/varLib/__init__.py

The C implementation of ElementTree is included in CPython since 2.5.
It's got the same API and is up to 20 times faster than the Python implementation.
We'd better use it.

varLib: use cElementTree if available to parse designspace

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

If they are not integers compiling the glyf table will fail.

Make sure component coordinates are integers

---

Lib/fontTools/misc/py23.py

On python 2, both `range` and `xrange` will be aliases of `xrange`. On Python 3, both `range` and `xrange` will be aliases of `range`.
So in both 2 and 3, either range or xrange will behave like the Python 3 version of range, i.e. as iterators.
comments?

py23: always use the iterator version of (x)range

---

Lib/fontTools/misc/loggingTools.py
Lib/fontTools/subset/subset_test.py

The change to use Python logging makes Google Fonts custom Logger for timing subsetting break. We can easily capture logging messages via a Handler but having only the final formatted message rather than the parts is inconvenient.
This seemed like the smallest change that would make server collection of aggregate timing easy again. We could alternately try to let Timer generally rely more on logger to do the formatting and thus avoid formatting messages that won't be written if the log isn't enabled at level.

Broadcast timing parts as well as final formatted message

---

Lib/fontTools/subset/__init__.py

I don’t know why this is happening, but I’m getting attribute error when
I build https://github.com/khaledhosny/mada with compreffor
optimisations on.

Check for file attribute before deleting it

---

Lib/fontTools/cffLib.py

Something like this was failing,
```python
from fontTools.ttLib import TTFont
font = TTFont()
font.importXML('myFont.ttx')
font.saveXML('myNewFont.ttx')
```

Fix xml-roundtripping of CFF fonts (name-keyed & cid-keyed)

---

Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/parser_test.py

This addresses issue #641.
in https://github.com/behdad/fonttools/commit/7eed24725f33c76d033e40888d865e13d47622c2, Sascha allowed the `include` statement to not be followed by a semicolon.
However, the symbol is not eaten up by the Lexer, but is passed on to the Parser, which barks at it because it does not expect a stray SYMBOL ";" at the top level of a feature file.
I tested with makeotf, and confirmed that it ignores any extra semicolons which appear in a feature file. I guess we can do the same.

[feaLib] ignore stray semicolons

---

requirements.txt

This should speed up the Travis and Appveyor builds, as we don't need to compile Brotli from source, at least on OSX and Windows.
Linux will still use the .tag.gz source distribution.

requirements.txt: download Brotli 0.4.0 pre-compiled wheel from Github Releases

---

.travis.yml
setup.cfg
setup.py

I tested this on my fork, using the test.pypi.org server and it works: 
https://testpypi.python.org/pypi/fonttools
Now it's super easy to tag a release and upload the sdist and wheel to PyPI:
```bash
$ git tag -a "3.1" -m "A new release, at last..."
$ git push behdad 3.1
```
Or if you like, you can go use Github to [create releases](https://help.github.com/articles/creating-releases/), after which Travis will see the new tag, and trigger a new build and deployment.
C'mon, let's do it!

[Travis] auto deploy to PyPI on tags

---

Snippets/dump_woff_metadata.py
Snippets/merge_woff_metadata.py

This is just to exemplify how one could use the `TTFont.flavorData` attribute to get/set the WOFF metadata, as @antonxheight asked in https://github.com/behdad/fonttools/issues/630
I'm not sure if something like this should/could be integrated in the main ttx script.

Snippets: add 'merge_woff_metadata.py' and 'dump_woff_metatada.py' scripts

---

Lib/fontTools/subset/__init__.py

Fixed encoding error in subset tool in Windows which system default codepage isn't 65001.
For Example: 
When windows default codepage is 936, the command like 'pyftsubset myfont.ttf --text-file=mytextfile.txt' will throw an exception.

Fixed encoding error in subset tool in Windows

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/testdata/multiple_feature_blocks.fea
Lib/fontTools/feaLib/testdata/multiple_feature_blocks.ttx

When a feature is defined in more than one block, the language statement exclude_dflt should not apply to all the dflt lookups but only those defined in the block of the language statement.
For example, feaLib doesn’t compile to following correctly. The latn TRK language system is completely dropped.
```
languagesystem DFLT dflt;
languagesystem latn dflt;
languagesystem latn TRK;
feature liga {
lookup liga_fl {
sub f l by f_l;
} liga_fl;
} liga;
feature liga {
lookup liga_fi {
sub f i by f_i;
} liga_fi;
script latn;
language TRK exclude_dflt;
} liga;
```
For AFDKO, this is equivalent to the following.
```
languagesystem DFLT dflt;
languagesystem latn dflt;
languagesystem latn TRK;
feature liga {
lookup liga_fl {
sub f l by f_l;
} liga_fl;
lookup liga_fi {
sub f i by f_i;
} liga_fi;
script …
```

feaLib: limit language statements to 1 feature block 

---

Lib/fontTools/misc/py23.py
Lib/fontTools/misc/py23_test.py

This is to address https://github.com/behdad/fonttools/issues/664.
It adds two new functions to the `py23` module: namely, `round2` and `round3`.
The former behaves like Python 2's built-in `round` function, wheres the latter like Python 3's.
I also added some of the tests from the CPython 2.7 test suite.
Please review, thanks.
/cc @moyogo

[py23] add round2 and round3 functions

---

Lib/fontTools/ttLib/tables/T_S_I__5.py

This is also what VTT does when one does "Prepare font..." and a character is not present in the character groups template file ("CharGrp.txt"): it gets assigned to the default "AnyGroup" group, or 0.
Note that the TSI1 and TSI3 tables do not raise when a glyph name is in the glyphOrder but is missing in their internal mapping; they instead write an empty entry.
This makes easier to merge TSI* tables from different fonts or from earlier revision of the same font containing only a subset of the glyphs.
/cc @moyogo

TSI5: set group to 0 (i.e. "AnyGroup") when compiling if glyph name is missing

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/subset_test.py

By default, the subsetter drops any table which it can't subset. This option will allow to keep those unknown tables nevertheless, without the user having to list them one by one in `--no-subset-tables=` which was currently the only way to accomplish that.
/cc @folengo

[subset] add --passthrough-tables option

---

Makefile
README.md
run-tests.sh
setup.cfg
setup.py
tox.ini

Follow up from https://github.com/fonttools/fonttools/commit/064932e2e6557852d311f901e3c798cca8e34174
Tests can now be run from a local checkout with the canonical `python setup.py test`. You can also use the `run-tests.sh` script or `make check`, so everyone is happy. :)
We use the pytest-runner plugin to bootstrap pytest when running `setup.py test`, without having to pip install it beforehand.

update Makefile; use pytest-runner; etc.

---

Lib/fontTools/cffLib.py
Lib/fontTools/subset/testdata/expect_keep_math.ttx
Lib/fontTools/subset/testdata/expect_no_notdef_outline_cid.ttx
Lib/fontTools/subset/testdata/expect_no_notdef_outline_otf.ttx
Lib/fontTools/ttLib/tables/C_F_F_test.py

When running my CFF2-capable cffLib.py  over the Adobe Type library, and comparing the CFF 1.0 output with the main-branch cffLib.py version, I found a few issues in the original code.  All simple fixes, fortunately.

Opentype gx

---

Lib/fontTools/feaLib/builder.py

This avoids the new warning `Table version value is a float: 1; fix code to use hex instead: 00010000`.
See https://github.com/googlei18n/fontmake/issues/149.

feaLib: fix code to use hex version instead of float

---

Lib/fontTools/ttLib/sfnt.py

... use global `ZLIB_COMPRESSION_LEVEL` instead
Fixes https://github.com/fonttools/fonttools/issues/686
cc @severinmeyer

sfnt.py: drop `WOFFDirectoryEntry.zlibCompressionLevel`

---

Lib/fontTools/pens/areaPen.py
Lib/fontTools/pens/areaPen_test.py

Sometimes an anchor is drawn as a moveTo followed by an endPath, for
that case it makes sense just to ignore and count the area as zero.
r? @anthrotype

Allow single-point open contours in area pen

---

Lib/fontTools/misc/loggingTools.py
Lib/fontTools/subset/subset_test.py
Lib/fontTools/ttLib/tables/_n_a_m_e.py
Lib/fontTools/ttLib/tables/_n_a_m_e_test.py
Lib/fontTools/varLib/__init__.py

This should fix https://github.com/fonttools/fonttools/issues/683
varLib now adds both Macintosh (platformID=1) and Windows (platformID=3) name records for axes names and instance styles, to work around an issue when loading OpenType Variable fonts on macOS.
I also fixed another str/bytes issue related to the `NameRecord.setName` method. This now accepts as input string both unicode or bytes, with the latter assumed to be already encoded with the specified (platformID, platEncID, langID) triplet.
Note that this is how the `string` attribute of `NameRecord` worked already: it takes either a unicode string (in which case, it attempts to encode it with the correct platform encoding upon compiling), or it takes a pre-encoded bytes string which is treated literally. It's the client's …

Fix varlib names

---

setup.py

This is of no use, it is undocumented and bound to be removed.
See https://bugs.python.org/issue901727 and https://bugs.python.org/issue27919.

Remove extra_path distribution kwarg

---

.travis.yml
.travis/install.sh

Travis CI has become too slow, especially for the osx environment.
It's not just for the recent outage -- https://www.traviscistatus.com/ --, but I think it's also because of its increasing popularity, and the fact that it's the only one free providing OS X environments.
Even Appveyor, which does one build at the time, is now faster than Travis!
So I think we need to clean up our Travis configuration and only run the most essential ones.
We don't need to test two Python 2.7 bugfix releases on OSX; one (whatever is the current Travis default) is enough.
Also, PyPy is quite niche and we can get away with only testing it on the Linux platform.

[Travis] try to speed up osx builds a bit

---

Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/subset_test.py
Lib/fontTools/subset/testdata/expect_desubroutinize_CFF.ttx
Lib/fontTools/subset/testdata/expect_drop_hints_CFF.ttx
Lib/fontTools/subset/testdata/expect_drop_hints_TTF.ttx
Lib/fontTools/subset/testdata/expect_drop_hints_desubroutinize_CFF.ttx

It seems that the horizontal advance of hinted charstrings gets lost when the CFF hinting is stripped with '--no-hinting' option, as it was noted by @miguelsousa in this comment:
https://github.com/behdad/fonttools/issues/343#issuecomment-156234918
The reason is `T2CharString` objects only get assigned a 'witdh' attribute after their 'draw' method is called.
The subsetter's `drop_hints` function attempts to insert the width back at the beginning of the de-hinted charstring's program, but can do that only if the charstring does have a 'width' attribute:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L1908
Hence, we must 'draw' the charstring (with a `NullPen`) before stripping the hints.
(I will add a quick test tomorrow.)

subset: must 'draw' charstrings to set 'width' attribute before calling 'drop_hints'

---

Lib/fontTools/feaLib/testdata/spec8b.ttx
Lib/fontTools/feaLib/testdata/spec8c.ttx
Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otConverters_test.py
Lib/fontTools/ttLib/tables/otData.py

When writing XML, this produces a comment with the English name.
If the name ID is missing from the name table, it logs a warning.

Add otConverters.NameID

---

Lib/fontTools/ttLib/tables/_h_m_t_x.py
Lib/fontTools/ttLib/tables/_h_m_t_x_test.py
Lib/fontTools/ttLib/tables/_v_m_t_x_test.py
MANIFEST.in
tox.ini

Print a warning on decompile if advance width (or height for vmtx) exceeds 0x7FFF (32767).
Upon compile, `struct.pack` will raise if the value is negative as it is out of range for the unsigned "H" format.
Fixes #645 
---
Apparently both FontLab Studio (both 5 and VI) and Robofont allow these negative advances to occur in a font. UFO spec either does not enforce the value to be positive. I wonder why this is the case. Glyphs like that are definitely broken, as you can see from the mega-huge width they take when loaded in FreeType, MS and Apple rasterizers.
/cc @twardoch @typemytype @typesupply

[_h_m_t_x] Read advanceWidth as unsigned short (uint16)

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/testdata/spec9d.ttx
Lib/fontTools/feaLib/testdata/spec9g.fea
Lib/fontTools/feaLib/testdata/spec9g.ttx
Lib/fontTools/misc/fixedTools.py
Lib/fontTools/ttLib/tables/_h_h_e_a.py
Lib/fontTools/ttLib/tables/_h_h_e_a_test.py
Lib/fontTools/ttLib/tables/_v_h_e_a.py
Lib/fontTools/ttLib/tables/_v_h_e_a_test.py
Lib/fontTools/ttLib/tables/otConverters.py

- Replace reserved0 by caretOffset in vhea, keep reserved1...reserved4 instead of reordering for legacy.
- Add vhea support to feaLib.
- Fix for *tableVersion in 'vhea' is confusing* #540 and keeps hhea in sync with vhea, tableVersion is now hex (with translation from float).
- Moved otConverters.Version logic to new fixedTools functions, use in vhea, hhea and otConverters.Version.
- Add tests for vhea and hhea, update feaLib tests to use hex table version.

Fix vhea, add vhea to feaLib, table version functions in fixedTools

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/misc/xmlWriter.py
Lib/fontTools/misc/xmlWriter_test.py
Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttx.py

When TTX files are under version control and are being modified across multiple platforms, it's good to be able to _not_ use the default `os.linesep`, currently used by `XMLWriter`, but instead specify one particular line ending for all different platforms (e.g. most likely, LF).
This PR adds a `newlinestr` keyword argument to `XMLWriter` constructor, as well as to `TTFont.saveXML` method.
It also adds a `--newline` option to `ttx` console script.
The default does not change (ie. we keep using the native line endings).
However, we may wish to revise this in the future and always write Unix-style line feeds, since the XML specification says XML processor have to normalize them as such anyway. See https://www.w3.org/TR/REC-xml/#sec-line-ends
BTW, lxml always writes `"\n"` as line endings …

[ttx/xmlWriter] allow to override OS-specific line endings 

---

Lib/fontTools/ttLib/tables/_h_m_t_x.py
Lib/fontTools/ttLib/tables/_h_m_t_x_test.py

I think we don't need to issue any warnings here, since we don't do that either when we round `glyf` coordinates.
Fixes #593

[hmtx/vmtx] Round float values to int

---

Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/feaLib/testdata/bug457.fea
Lib/fontTools/feaLib/testdata/bug457.ttx
NEWS

Backslash-prefixed glyph name can be used in a Feature file to distinguish them from identically-named keywords.
From section "2.f.i. Glyph name" of Adobe's Feature File Specification:
> An initial backslash serves to differentiate a glyph name from an identical keyword in the feature file language. For example, a glyph named "table" must be specified in the feature file as: \table
Thus, when we parse a glyph name that begins with a backslash, we need to ignore the first character.
Note that makeotf rejects feature files with glyph names that start with or contain backslashes escaped with another backslash.
```
feature liga {
sub \\glyphWithBackslash by A;
} liga;
```
This yields:
makeotfexe [FATAL] <Backslash-Regular> invalid token (text was "\") [features 2]
Fixes …

[feaLib] support backslash-escaped glyphs in FEA

---

Lib/fontTools/ttLib/tables/O_S_2f_2.py

This fixes commit 49ac9ba5cbc3931d6d4c052a1c2641c8bcde5b40.
See https://github.com/googlei18n/ufo2ft/issues/80

Fix "OS/2: fsSelection bits 0 and 5 should match head.macStyle bits 1 and 0"

---

Lib/fontTools/varLib/__init__.py

With this change, varLib will not export unused axes (i.e. axes with default==min==max). 
Currently, FontMake exports all 3 axes from Glyphs files, even if they aren't used (https://github.com/googlei18n/fontmake/issues/144).  Then, varLib would propagate these to the fvar table. While these don't do any harm per-se, it's inconvenient when trying to maintain hand-coded tables for which fontTools doesn't support (e.g. cvar, MVAR, STAT) with production values (i.e. their axisCount fields only reference the axes that are actually used, thus not being in synch with the value in fvar, gvar, HVAR and other tables that fontTools does build). 
It probably needs to be fixed upstream in fontmake, but this is a quick, tidy addition to varLib.

[varLib] Do not emit null axes in fvar (default==min==max)

---

Lib/fontTools/inspect.py

pyftinspect when run in python3 environment, it failed on Fedora 24 as pygtk is not python3 compatible. We need to port inspect.py file to use gobject-introspection but easy way I found is to use [pygtkcompat](https://wiki.gnome.org/Projects/PyGObject/PyGTKCompat) module. With this change we can run pyftinspect in both the python 2 and python 3 environment.
Please review this pull request and ask if needed any more changes.
Thanks.

Make inspect.py file compatible to run with python2 and python3

---

Lib/fontTools/misc/py23.py
Lib/fontTools/misc/py23_test.py

See https://github.com/fonttools/fonttools/issues/753
In addition to the optimizations suggested by Behdad and James, I also made so that round2 is only defined in Python 3, and round3 only in Python 2, with the other ones just pointing to the respective built-ins.
I also dropped support for the second argument, ndigits, having a `__index__` attribute, which is a bit niche, I think.
/cc @behdad @jamesgk

[py23] optimize round3 function

---

Lib/fontTools/misc/py23.py
Lib/fontTools/misc/py23_test.py

in normal circumstances, we get a huge speed improvement if we use the built-in Python 2 `round()` function for those values which we know will produce the same results as our slow implementation of Python 3 rounding (that uses the pure-python `decimal` module).
The latter will only be used when a number is half-way between the two multiples of 10 to the power `ndigits`, and the multiple towards zero is even.
When I check if the float number is "half-way" I can't simply take the `% 1 == .5`, because floating point math is funny. For that I use `math.isclose()` function (added in Python 3.5), for which I add a pure-python backport.
Checking that a float `isclose` is still faster than rounding it using the slow `Decimal` method.
@jamesgk @behdad

[py23] further optimizie round3 function

---

Lib/fontTools/misc/py23.py
Lib/fontTools/misc/py23_test.py

This round thing is killing me..
There's a problem with the built-in `round()` function on Python 3.5.
If one passes `None` as a second argument, and the first argument is a float, everything is ok 
```python
>>> round(1.0, None)
1
```
But if the first argument is an integer and you pass None as second argument, it raises:
```python
>>> round(1, None)
TypeError: 'NoneType' object cannot be interpreted as an integer
```
Now, this happens to be a known issue (https://bugs.python.org/issue27936) which has been fixed in Python 3.6.
Here, on Python3 below 3.6, I have to wrap the built-in round() so that when it gets None as second argument, it behaves as if one did not provide the second argument at all.
See also https://github.com/typesupply/fontMath/pull/37#issuecomment-264435328

[py23] fix inconsistency of built-in round on Python 3.5 if second argument is None

---

Lib/fontTools/cffLib.py

This fixes #740.
Commits https://github.com/fonttools/fonttools/commit/3063def35b7ad733bf584b45452f9ef8f6efbab4 and https://github.com/fonttools/fonttools/commit/5b47971 introduced a separate fontDictOperators list for FontDict, only listing those TopDict key/value pairs that are actually used in the FontDict context. It provided a fallback that TTX files containing such "useless" key/value pairs would not be rejected.
However, the code still rejected binary fonts that contained such values, even though it didn't before, and yes, such fonts exist. Also: such fonts are not broken per spec, they just contain some fields that otherwise no one ever looks at, so it's a little harsh to reject them.
This patch removes most of the special FontDict code, and uses everything from TopDict, *except* …

Fix for #740.

---

setup.py

With the new 3.3.0 release, I found that when you do "python setup.py build", you will see 
```
$ python2 setup.py build 
running build
running build_py
file Lib/sstruct.py (for module sstruct) not found
file Lib/xmlWriter.py (for module xmlWriter) not found
.....
```
This can be fixed by removing following line from setup.py
``` 
py_modules=['sstruct', 'xmlWriter'],
```
I think this is also related with #696

Remove py_modules sstruct and xmlWriter from setup.py for issue#696

---

Lib/fontTools/agl.py
Lib/fontTools/agl_test.py

Implements the mapping algorithm from the [Adobe Glyph List specification](
https://github.com/adobe-type-tools/agl-specification#2-the-mapping).
Currently, the implementation only recognizes glyph names from the
Adobe Glyph List for New Fonts (AGLFN), not the legacy AGL which is a
superset. If there is interest, it would be easy to support the legacy AGL
as well, preferrably in a follow-up change.
https://github.com/googlei18n/glyphsLib/issues/88#issuecomment-267408215

Map AGL glyph names to Unicode

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/misc/testTools_test.py
Lib/fontTools/otlLib/builder_test.py
Lib/fontTools/ttLib/tables/C_P_A_L_test.py
Lib/fontTools/ttLib/tables/M_V_A_R_test.py
Lib/fontTools/ttLib/tables/S_T_A_T_test.py
Lib/fontTools/ttLib/tables/_h_h_e_a_test.py
Lib/fontTools/ttLib/tables/_h_m_t_x_test.py
Lib/fontTools/ttLib/tables/_t_r_a_k_test.py
Lib/fontTools/ttLib/tables/_v_h_e_a_test.py
Lib/fontTools/ttLib/tables/otConverters_test.py

When writing unit tests for XML data, it is more convenient to compare list of lines, instead of a single string without newlines.
This helps identifying which lines in the diff printed on the console don't match the expected result.
So this makes `getXML()` returns a list of lines.
Similarly, the complementary function `parseXML()` now also accepts a list of
strings, as well as a single string, to allow reusing the same data for to/fromXML round-trip tests.
/cc @brawer @moyogo

[testTools] have getXML() return a list of lines

---

.travis.yml
.travis/before_deploy.sh
.travis/install.sh
.travis/run.sh
tox.ini

jython tests have been failing since day one, but no one was interested in fixing them.
https://github.com/fonttools/fonttools/issues/575
Also I hear google has now switched to CPython so I think we can drop Jython for good.
We shall replace the slot occupied by jython with Python 3.6, released the other day.

drop support for jython; add support for python3.6

---

.appveyor.yml
.codecov.yml
.coveragerc
.gitignore
.travis.yml
.travis/after_success.sh
.travis/install.sh
.travis/run.sh
README.md
tox.ini

This allows checking test coverage on all the supported python versions/platforms, instead of just python3.5 on Linux as it was before.
I also replaced Coveralls.io with Codecov.io, which seems to have a better UI and, unlike Coveralls, has built-in support for Appveyor.
I still have to tweak the notification settings, but I'll make sure it doesn't become too chatty.
Also, on OSX we now use homebrew python3 instead of compiling it from source, so we save a few minutes on the expensive Travis osx builds.
Finally, I decided to remove python3.4 from Appveyor; Windows people usually update to the latest version because, unlike Linux, python it's not pre-installed on the system. We still test 3.4 on Linux (hopefully for not too long).

run coverage on all python versions; upload combined data to codecov

---

Lib/fontTools/otlLib/builder.py

This fixes broken tests after 9e76d16, and should finally close https://github.com/fonttools/fonttools/issues/766
/cc @justvanrossum @behdad @brawer

[otlLib] only sort ClassDefBuilder input glyphs if they are unsorted

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder_test.py
Lib/fontTools/feaLib/testdata/markClass.fea

In `feaLib.ast.MarkClass` we check that a glyph is not defined more than once across multiple definitions of the same markClass.
However, as @mhosken pointed out in https://github.com/fonttools/fonttools/pull/794/files/3b79d51755dda83782dcf1b180f6098d38951539#r94622074, the code is looking for the glyph name in the wrong list.
The problem is that by fixing the code, the markClass.fea test case fails, as it does indeed contain a duplicate glyph definition for "acute".
I'm not sure whether this was intentional or not, so I'll leave it to Sascha to review.

[feaLib] fix check for redefined glyph between multiple markClass definitions

---

Lib/fontTools/pens/t2CharStringPen.py
Lib/fontTools/pens/t2CharStringPen_test.py

I went for the easy route, and simply added a `roundTolerance` argument to the `T2CharStringPen` as @behdad was discussing in #769.
I personally think that doing more clever things would be a bit beyond the scope of fontTools.
But I'm happy to be convinced otherwise ;)
PTAL, thanks

[t2CharStringPen] add "roundTolerance" option

---

Lib/fontTools/varLib/interpolate_layout.py
Lib/fontTools/varLib/merger.py

When reduce() receives an empty sequence, it raises TypeError, unless it is also given a third 'initializer' argument
ValueFormat values should default to 0, so we shall use that as initializer.
Also, the reduce() built-in is no longer available on Python 3.
It's still accessible for both py2 and py3 from functools.
Should fix https://github.com/googlei18n/fontmake/issues/241

[varLib.merger] set initializer for reduce() to handle empty sequences

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
NEWS.rst
Tests/feaLib/builder_test.py
Tests/feaLib/lexer_test.py
Tests/feaLib/parser_test.py

The OpenType Feature File Syntax has been changed to support dashes:
https://github.com/adobe-type-tools/afdko/issues/152
Resolves https://github.com/fonttools/fonttools/issues/559.
Needed for https://github.com/googlei18n/fontmake/issues/249.

Support glyph names with dashes

---

Lib/fontTools/feaLib/parser.py
NEWS.rst
Tests/feaLib/data/spec8b.fea
Tests/feaLib/data/spec8b.ttx
Tests/feaLib/parser_test.py

We now correctly handle nameid statements with surrogate pairs and
old-style macOS-encoded names (provided that fonttools supports the
specified encoding).
Resolves https://github.com/fonttools/fonttools/issues/842.

[feaLib] Make nameid parsing more robust

---

Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/subset/__init__.py
Tests/subset/data/Lobster.subset.ttx
Tests/subset/data/expect_desubroutinize_CFF.ttx
Tests/subset/data/expect_no_hinting_CFF.ttx
Tests/subset/data/expect_no_hinting_TTF.ttx
Tests/subset/data/expect_no_hinting_desubroutinize_CFF.ttx
Tests/subset/subset_test.py

After merging PR #606, we spotted an issue so we decided to revert while investigating.
PR #606 was meant to fix an issue with the subsetter's `--no-hinting` option, which makes it strip all the advance widths from CFF charstrings.
I tried to fix this by 'drawing' the charstring with a NullPen, which would force setting its `width` attribute.
However I discovered that, with the above mentioned patch, the `--no-hinting` option would now throw an error with some fonts -- but not with the (admittedly too simple) 'TestOTF-Regular.otf' which is why I didn't catch this while running the automated tests.
Basically some charstrings have their `private` attribute set to None, hence have no `nominalWidthX` or `defaultWidthX` and the `draw()` method can't compute their width.
Now, if _both_ …

[subset] [WIP] second attempt at fixing --no-hinting with CFF

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/NotdefWidthCID-Regular.ttx
Tests/subset/data/expect_notdef_width_cid.ttx
Tests/subset/subset_test.py

`font.FDSelect[i]` returns a GID, not an index of `font.FDArray`.
Before this commit `.notdef` might have wrong glyph width in CharStrings, if its `fdSelectIndex` is not 0 in the input font.

[subset] Set the correct glyph width for blank .notdef

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/ZeroValue_PairPos_horizontal.fea
Tests/feaLib/data/ZeroValue_PairPos_horizontal.ttx
Tests/feaLib/data/ZeroValue_PairPos_vertical.fea
Tests/feaLib/data/ZeroValue_PairPos_vertical.ttx

If a zero value appears in a SinglePos statement, feaLib continues to
produce ValueRecords of format 0. But if a zero value appears in a
PairPos statement inside a horizontal compilation context, feaLib now
produces ValueRecords of format 4. Likewise, if a zero value appears
in a PairPos statement inside a vertical compilation context, feaLib
now produces ValueRecords of format 8.
The OpenType Feature Syntax specification is completely silent about this,
but the new behavior matches that of makeotf.
https://github.com/fonttools/fonttools/issues/633

[feaLib] Compile zero values to different formats based on context

---

Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttx.py

it's implicitly required anyway, e.g. see ttx's `ttCompile`, maxp's `recalc`, OS/2 `compile`, etc.
/cc @justvanrossum

explicitly require 'head' table in TTFont.save()

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Tests/ttLib/tables/TupleVariation_test.py

Python 3 was raising 'struct.error: required argument is not an integer' and Python 2 was truncating when deltas are floats

TupleVariation: round deltas before encoding

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/designspace.py
Lib/fontTools/varLib/interpolate_layout.py

Here is a method to use the designspace <axes> element  to define the axis map, and preserve the axis order. If the <axes> element does not exist, still uses the standard_map, but with the order preserved.

varLib. Use designspace <axes> element to define the axisMap and order.

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/data/lookupflag.fea
Tests/feaLib/data/lookupflag.ttx

ufo2ft markFeatureWriter adds `UseMarkFilteringSet` statements in `mkmk` lookups (googlei18n/ufo2ft#57). Sometimes the glyph classes used to define these can contain duplicate glyphs.
Since feaLib parser by default treats glyph classes in feature file as tuples of string (with an inner order and possibly duplicates), the generated `Coverage` in `MarkGlyphSetsDef` (in `GDEF`) end up with unnecessary duplicate glyphs.
See https://github.com/googlei18n/glyphsLib/issues/89
This patch changes the feaLib builder so that it casts tuples to frozensets when collecting glyph classes that defines MarkGlyphSetsDef, as well as MarkAttachClassDef.
I checked makeotf, and this also does the same.
/cc @brawer @behdad

Ignore duplicates in MarkGlyphSetsDef and MarkAttachClassDef

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/designspace.py
Tests/varLib/designspace_test.py

mostly cosmetic, two changes deserve mention:
- if any of `axes`, `instances` or `sources` element is not present, the dictionary returned from `designspace.load` will not contain the respective key/value pair; an empty list means the element is defined but empty;
- what was previously called `masters` is now called `sources` for consistency with the designspace document specification.

[varLib/designspace] fixups

---

Tests/subset/data/TestCID-Regular.ttx
Tests/subset/data/TestCLR-Regular.ttx
Tests/subset/data/TestGVAR.ttx
Tests/subset/data/TestMATH-Regular.ttx
Tests/subset/data/TestOTF-Regular.ttx
Tests/subset/data/TestTTF-Regular.ttx
Tests/subset/data/google_color.ttx
Tests/ttLib/data/TestTTF-Regular.ttx

Some housekeeping as I just noticed these warnings.

[tests] Change `hhea` and `vhea` table version from float to hex to mute fontTools warnings

---

Tests/varLib/data/test_results/InterpolateLayoutGPOS_1_diff.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_1_diff2.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_1_same.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_spec_diff.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_spec_diff2.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_spec_same.ttx
Tests/varLib/interpolate_layout_test.py

The failures are due to XML round-tripping mismatches: `<Coverage Format="1">` vs. `<Coverage>`.
Cosimo, please do your magic. I believe the TTX result files are correct. Thanks!

[varLib.interpolate_layout] Tests for GPOS LookupType 1 and LookupType 2 specific pairs

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/lexer_test.py
Tests/feaLib/parser_test.py

This addresses issue #829. All comments end up on a line of their own and there are plenty of places where comments are still not allowed. But I hope this does support all the sensible places where people might put comments. The only ones of interest that may get missed are:
- Inside classes
- Within a rule
- Within lists of values for some tables
I.e. comments are only supported between statements.

Add support for comments to parser

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
NEWS.rst
Tests/feaLib/parser_test.py

The syntax tree representation now reflects the syntax of feature files.
Before this change, FeatureNames did not have their own `ast.Block`,
which had made the code quite messy.

[feaLib] Clean up syntax tree for FeatureNames

---

Lib/fontTools/cffLib.py
Lib/fontTools/misc/psCharStrings.py

After 2b2aca1, `DictCompiler` and `DictDecompiler`'s `arg_delta` method unconditionally attempts to get the first item to check if it's a list, but this fails with `IndexError` when the value is empty.
/cc @behdad @readroberts @miguelsousa 
```
Traceback (most recent call last):
[...]
File "/Users/cosimolupo/Documents/Github/ufo2ft/Lib/ufo2ft/otfPostProcessor.py", line 15, in __init__
otf.save(stream)
File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 219, in save
self._writeTable(tag, writer, done)
File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 658, in _writeTable
tabledata = self.getTableData(tag)
File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/__init__.py", line 669, in getTableData …
```

[cffLib/psCharStrings] fix IndexError with empty deltas

---

Lib/fontTools/ttLib/tables/otConverters.py
Tests/ttLib/tables/otConverters_test.py

Used by Apple Advanced Typography tables, for example `gcid`.
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6gcid.html
https://github.com/fonttools/fonttools/issues/178

[AAT] Add Char64 converter for 64-byte ASCII character strings

---

Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/varLib/merger.py
Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_class_diff.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_class_diff2.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_class_same.ttx
Tests/varLib/interpolate_layout_test.py

This is the follow-up of another PR #881 opened by @miguelsousa a few days ago.
Miguel added some tests for `varLib.interpolate_layout`, specifically for GPOS PairPos Format 2 subtables, but these were failing for a number of issues in `varLib.merger` module.
1) `IndexError` was being raised when aligning the first classes in PariPos Format 2, and one of the `ClassDef1` was empty (aad0d46)
2) An extra empty PairPos Format 1 was being inserted all the time, even if the fonts to merge/interpolate didn't have any Format 1 PairPos subtables (d83c2fb)
3) multiple reference to the same mutable `Class2Record` instance were being used and inadvertently modified (e6125b3)
4) the `Format` attribute of `ClassDef1` and `ClassDef2` was only set upon compilation (in the `otTables.ClassDef.preWrite` …

[varLib.merger] Fix interpolating PairPos Format 2

---

Lib/fontTools/misc/loggingTools.py
Lib/fontTools/misc/py23.py
Lib/fontTools/ttLib/tables/T_S_I__0.py
Lib/fontTools/ttLib/tables/T_S_I__1.py
Lib/fontTools/ttLib/tables/T_S_I__2.py
Lib/fontTools/ttLib/tables/T_S_I__3.py
Lib/fontTools/ttLib/tables/T_S_I__5.py
Tests/ttLib/tables/T_S_I__0_test.py
Tests/ttLib/tables/T_S_I__1_test.py

This patch rewrites the TSI1 table `decompile` method to work around an issue which I encountered while decompiling tables generated with the latest VTT 6.20.
Many thanks @be5invis for the hints found in his otfcc compiler ;)
Besides this also adds:
- a `match` method to the `loggingTools.CapturingLogHandler` (9528717);
- a backport for python 3's [`SimpleNamespace` class](https://docs.python.org/3/library/types.html#types.SimpleNamespace) (a844249)
both can be handy e.g. when writing tests.

[TSI*] Fix computation of the textLength of VTT private tables entries

---

Lib/fontTools/misc/loggingTools.py
Lib/fontTools/ttLib/tables/T_S_I__1.py
Tests/misc/loggingTools_test.py

This is useful to quickly add logging functionality to classes, and to reduce boilerplate.
It adds a `log` property to the class inheriting from it, which uses `logging.getLogger` to get a logging.Logger (sigleton) object named after `<module>.<class>` of `self`.

[loggingTools] added LogMixin class

---

Lib/fontTools/pens/filterPen.py
Lib/fontTools/pens/transformPen.py

The base `FilterPen` class is simply a pen that delegates the drawing to another one, which is passed as argument in the `__init__` method.
The existing `TransformPen` is an example of this class of pens.
The default implementation of `FilterPen` simply passes through the drawing commands to the sub-pen, without modifications.
One can subclass FilterPen and override any of its methods in order to manipulate the contours or components, before sending them to the other pen.

[pens] add filterPen module

---

Lib/fontTools/pens/basePen.py
Lib/fontTools/pens/recordingPen.py
Tests/pens/basePen_test.py
Tests/pens/recordingPen_test.py

This moves the `addComponent` method of BasePen into a separate `DecomposingPen` that can be mixed in with a RecordingPen to make a `DecomposingRecordingPen` class that records components decomposed, as simple contours.

[pens] add DecomposingPen and DecomposingRecordingPen

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

(within the same lookup)
See #453.
r? @brawer
cc @madig: this will throw a explicit error for the file you sent me instead of putting a KeyError down the line.

builder: throw when a mark is defined in multiple mark classes

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

This failing test is to show the issue #963.
The patch below fixes it.
I don't see problems with changing GlyphCoordinates to using doubles instead of floats, but I'd like to hear from others before committing the change in case I may be missing something.
```diff
diff --git a/Lib/fontTools/ttLib/tables/_g_l_y_f.py b/Lib/fontTools/ttLib/tables/_g_l_y_f.py
index 1e255506..b4586e39 100644
--- a/Lib/fontTools/ttLib/tables/_g_l_y_f.py
+++ b/Lib/fontTools/ttLib/tables/_g_l_y_f.py
@@ -1170,13 +1170,13 @@ class GlyphCoordinates(object):
return self._a
def isFloat(self):
-		return self._a.typecode == 'f'
+		return self._a.typecode == 'd'
def _ensureFloat(self):
if self.isFloat():
return
-		self._a = array.array("f", list(self._a))
+		self._a = array.array("d", list(self._a))
def _checkFloat(self, …
```

[_g_l_y_f] fix float precision loss in GlyphCoordinates

---

MANIFEST.in

Currently, running tests with the source distribution fails due to missing test font files.
This PR adds the missing files to the MANIFEST.in and fixes the issue.

Fix broken ttx tests

---

Lib/fontTools/mtiLib/__init__.py
Lib/fontTools/varLib/__init__.py

Not sure if warnings module was used intentionally here, but the messages looked odd compared to other FontTools messages.

Use logging module for a couple of warnings

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/mutator.py
Tests/ttLib/tables/_g_l_y_f_test.py
Tests/varLib/data/master_ttx_varfont_ttf/Mutator_IUP.ttx
Tests/varLib/data/test_results/Mutator_IUP-instance.ttx
Tests/varLib/mutator_test.py

I ended up redoing this on my own.  It's similar in functionality to Jens's work in https://github.com/fonttools/fonttools/pull/943
I haven't implemented the mutator part and will borrow from his code, but probably won't add those methods in GlyphCoordinates themselves but keep in varLib, and later move all IUP-related code into varLib.iup modules.
Tests should be ported from his branch as well.
I plan to implement full IUP optimization soon.  Maybe I work on that instead of the mutator part first.
WIP.

Varlib iup

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/data/GSUB_2.ttx
Tests/feaLib/data/GSUB_3.ttx
Tests/feaLib/data/spec5d1.ttx
Tests/feaLib/data/spec5d2.ttx

keep original lookup order and preserve the feature file's semantics
Fixes https://github.com/fonttools/fonttools/issues/448

[feaLib] don't de-duplicate lookups

---

Lib/fontTools/varLib/__init__.py

I've several typefaces that do not change any of the properties that MVAR tracks. These do not need an MVAR table, yet varLib was unconditionally emitting one. I just added an if to check that there are varying records, thus a reason to have an MVAR before storing it to the TTFont object.

Do not emit MVAR if there are no entries in the variation store

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/ttLib/tables/C_F_F_.py
Lib/fontTools/ttLib/tables/C_F_F__2.py
Tests/ttLib/tables/data/C_F_F__2.ttx

Remove specialized classes for CFF2: move logic into regular classes. To change a CFF table from CFF to CFF2, you now need only to set cff.major = 2, and move the Private Dict from the TopDict to a FontDict in an FDArray.
Removed global state: use instead a context class.

Cleanup work in cffLib.py

---

Snippets/fix-dflt-langsys.py

Such fonts violate the spec and OTS rejects them, this snippet should
help quickly fixing such fonts.

Add a snippet to remove LangSys from DFLT script

---

Lib/fontTools/varLib/merger.py

The ValueFormat of the ValueRecord in a SinglePos must be recalculated after merging, or the reference to the item store will be discarded when the font is compiled. Fixes #995.

Recalculate ValueFormat when merging SinglePos

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/ttLib/tables/C_F_F_.py
Lib/fontTools/ttLib/tables/C_F_F__2.py

As discussed in https://github.com/fonttools/fonttools/pull/968#issuecomment-309920007 and in private conversation with @behdad, here is an (admittedly huge) patch that should break the current deadlock, and allow us to keep backward compatibility with the old cffLib interface (so fontmake or robofont don't break).
* Removed `CFFContext`
* Added `isCFF2` argument to CFFFontSet.decompile/compile, used from respective ttLib classes
* Index classes get a `isCFF2` argument in constructor (used for decompiling); must be True/False if `file` argument is not None; it is stored as self._isCFF2 to support lazy loading
* Removed `TopDictData` class; reuse same `TopDictIndexCompiler` for both CFF and CFF2
* `CFFWriter` and all `*Compiler` classes get an `isCFF2` argument; defaults to the parent …

[cffLib/psCharStrings] remove cffCtx, pass down isCFF2

---

Lib/fontTools/ttLib/tables/otData.py

The 1.8.2 version of the OpenType spec adds AxisValueFormat 4 to the STAT table to support ranges. It also bumps the table rev to 1.2.
This pull request adds support for format 4 records.

Add AxisValueFormat4 for STAT table v1.2  from OT v1.8.2.

---

Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_o_p_b_d.py
Lib/fontTools/ttLib/tables/otData.py
README.rst
Tests/ttLib/tables/_o_p_b_d_test.py

Interestingly, this can handle the examples from the AAT specification
(which are part of the unit tests), and also most AAT fonts on my disk.
However, some other AAT fonts such as Apple Chancery cannot be decompiled.
The failure seems to be a general problem with how fonttools decompiles
AAT lookups of format 4, and unrelated to this present change.

[AAT] Support the `opbd` table with optical bounds

---

Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_b_s_l_n.py
Lib/fontTools/ttLib/tables/otBase.py
Lib/fontTools/ttLib/tables/otData.py
README.rst
Tests/ttLib/tables/_b_s_l_n_test.py

The AAT baseline table uses arrays whose length is constant instead of
getting encoded in the data. Extended otBase to support such arrays.

[AAT] Implement `bsln` baseline table

---

Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_m_o_r_t.py
Lib/fontTools/ttLib/tables/_m_o_r_x.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otData.py
Lib/fontTools/ttLib/tables/otTables.py
README.rst
Tests/ttLib/tables/_m_o_r_t_test.py
Tests/ttLib/tables/_m_o_r_x_test.py

Other metamorphosis types are not yet supported and will raise an error
upon decompilation. The TTX tool catches the error and continues to emit
a hexdump of the table contents, just as before this change.

[AAT] Support `mort` and `morx` tables with non-contextual substitutions

---

Lib/fontTools/ttLib/tables/__init__.py
Lib/fontTools/ttLib/tables/_a_n_k_r.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otData.py
README.rst
Tests/ttLib/tables/_a_n_k_r_test.py

The AAT `ankr` anchor point table is an auxiliary table for `kerx`,
used to store anchor overrides in case the glyph itself does not
supply the needed anchors as control points. Among the fonts that
come pre-installed with MacOS 10.12.6, `ankr` is used by a handful
of non-Latin fonts such as “Myanmar MN”, “Devanagari Sangam MN”,
and “Arial HB”.
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6ankr.html

[AAT] Implement anchor point table

---

Lib/fontTools/ttLib/tables/otConverters.py
Tests/ttLib/tables/_a_n_k_r_test.py
Tests/ttLib/tables/_b_s_l_n_test.py
Tests/ttLib/tables/_l_c_a_r_test.py
Tests/ttLib/tables/_m_o_r_t_test.py
Tests/ttLib/tables/_m_o_r_x_test.py
Tests/ttLib/tables/_o_p_b_d_test.py
Tests/ttLib/tables/_p_r_o_p_test.py

Before this change, the AAT lookups were alphabetically sorted by glyph name,
but it seems more natural to write XML in the usual glyph order. No changes to
the binary format (which already was in glyph order); this only affects how
XML output is produced.

[AAT] Write AATLookups to XML in glyph order

---

Snippets/svg2glif.py

this is just a little example for the new `SVGPath` class.
The script takes an svg file containing `<path>` elements and writes a UFO GLIF file from it, optionally with a name, advance width and height, unicode(s), and a transformation matrix.
(Note: this requires ufoLib)

[Snippets] add script to convert SVG outlines to UFO GLIF

---

Lib/fontTools/misc/timeTools.py
Tests/misc/timeTools_test.py

For reproducible builds, check the presence of SOURCE_DATE_EPOCH
environment variable and use it for the time stamp. This affects the
head.modified (and head.created in merge.py).
See https://reproducible-builds.org/specs/source-date-epoch/

Respect SOURCE_DATE_EPOCH for time stamp

---

Lib/fontTools/misc/arrayTools.py
Lib/fontTools/pens/filterPen.py
Lib/fontTools/pens/reverseContourPen.py
Tests/pens/reverseContourPen_test.py

A filter pen to reverse the contour winding direction, similar to ufoLib's `ReverseContourPointPen`, but using segment pen API, so we don't need to use the segment/point pen converters.

add ReverseContourPen

---

.travis.yml
.travis/before_install.sh

We use this helper script (https://github.com/praekeltfoundation/travis-pyenv) to install the latest [pyenv](https://github.com/pyenv/pyenv) and use that to compile and install Python 2.7.6 on linux.
Travis already have pyenv installed but is not always up to date, so we install it ourselves.
This will hopefully help us catch issues like #993 a bit earlier.
Note that this doesn't increase the overall Travis build time, as the osx builds still finish much later than the 6 linux builds combined, and adding another linux one doesn't change this.

run tests on Python 2.7.6 on Travis

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/varLib/__init__.py
Tests/ttLib/tables/TupleVariation_test.py
Tests/ttLib/tables/_c_v_a_r_test.py
Tests/ttLib/tables/_g_v_a_r_test.py

Related to issue https://github.com/fonttools/fonttools/issues/1001, this reactivates the sharing of point indices in TupleVariations if doing so saves file size.
It also fixes the bug leading to invalid gvar data described in the issue.

[varLib] Reactivate shared points logic, bugfixes

---

Lib/fontTools/pens/reverseContourPen.py
Tests/pens/reverseContourPen_test.py

Currently, for closed paths, we are always dropping a lineTo segment that follows moveTo, because after reversing the contour this lineTo becomes the last segment, and in the Pen protocol a closePath always implies a line to the fist point.
This is OK when in the original contour the move point and the following lineTo's oncurve point (which will become the last point after reversal) do not overlap.
However, if they do overlap, we end up dropping the duplicate point.
This cu2qu issue exemplifies the problem: googlei18n/cu2qu#51
(Note that cu2qu actually uses the `ReverseContourPointPen` wrapped by ufoLib's converter pens, but
fontTools' ReverseContourPen works the same)
Now, with this patch, the ReverseContourPen will emit the last lineTo when it is the same as moveTo, thus keeping the …

[reverseContourPen] don't imply closing lineTo if == moveTo

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

Before this change, the following glyph class:
@Vowels = [@Vowels.lc @Vowels.uc y Y];
Would be written back as:
@Vowels = [@Vowels.lc = [a e i o u]; @Vowels.uc = [A E I O U]; y Y];
Which is clearly invalid. It seems for `GlyphClass.asFea()` to work correctly here we should be using `GlyphClassName` not `GlyphClass` for the nested classes (similar to the code at the beginning of
`parse_glyphclass_()`).

[feaLib] Fix writing back nested glyph classes

---

Lib/fontTools/ttLib/tables/otConverters.py
Tests/ttLib/tables/_m_o_r_x_test.py

Before this change, we were emitting XML with numeric values for `morx`
coverage flags. Now, we emit XML that makes more sense to human readers.
XML files from previous versions of fonttools can still be parsed.

[morx] Emit more meaningful subtable flags

---

Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/tables/_c_m_a_p.py
Tests/ttLib/tables/_c_m_a_p_test.py

Often I just want to quickly access the best available cmap from a font, without being interested (or having to worry about) exactly which cmap subtables are in the font. I've used this functionality for while now in my own code as a separate function, and it's been so handy that I think it should just be in fonttools.

[ttLib] Add a convenience method to the cmap table to return the best available cmap

---

Lib/fontTools/ttLib/tables/_k_e_r_n.py
Tests/ttLib/tables/_k_e_r_n_test.py

- When compiling kern subtables for version=1.0 kern tables (AAT) the subtable header was written incorrectly: there is no `version` there, the length is a uint32 and there's an additional uint16 for `tupleIndex` (used for GX)
- Use the `coverage` low byte to select subtable "format", instead of the `version` field, only present in OT kern subtable header.
- `KernTable_format_0` now takes an `apple=False` argument, used to choose the different headers and whether to read/write `tupleIndex`.
- A new `tupleIndex` attribute is written out to TTX for Apple-style kern subtables. Old TTX files which lack that attribute will still be read (with a warning) and will default to 0 when recompiled or dumped with current fonttools.
Fixes #1089

fix compilation of AAT kern tables

---

Lib/fontTools/ttLib/tables/TupleVariation.py

… when testing whether to share points between tuples.
The old code tried to share either all points of a glyph or None. The new version uses the used points instead of all points. This shaved 108 bytes off a 500 bytes cvar table where always the same 2 of 133 CVTs are varied.

[varLib] Try a set of used points instead of all points

---

Lib/fontTools/misc/py23.py
Tests/misc/py23_test.py

I was prompted by another conversation to resuscitate something I had in my stash.
This adds py2.py3-compatible `redirect_stdout` and `redirect_stderr` context managers that can come handy in many situations.
https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout

[py23] Add backports for redirect_stdout/stderr context managers

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py
tox.ini

As @mhosken reported in #1096, feaLib currently handles incorrectly the case where a marked input
glyph sequence in a contextual chaining sub/pos rule is split into multiple runs, rather than being a single continuous run of `'` marked glyphs.
The consensus there was to raise a syntax error like makeotf instead of second-guessing and silently fixing it like fontforge does.

[feaLib] report error with multiple runs of marked ' glyphs

---

LICENSE.external

This will close #1116.
I decided to add it as another text file `LICENSE.external`. Please review if that's okay for you.
I also add Adobe AGL & AGLFN in the text because it looks nicer to put it together.

Add external license texts and disclaimers

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_c_v_a_r.py
Tests/ttLib/tables/_c_v_a_r_test.py

* Don't share points in cvar by default, font may fail to render properly in Chrome/WIndows (introduced in #1090)
* Adjust tests to test both shared and private points in cvar
TODO:
* Make `useSharedPoints` accessible to varLib (now only directly calling `cvar.compile()` or `TupleVariation.compileTupleVariationStore()` can take this argument)

Don't share points in cvar by default

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/expect_desubroutinize_CFF.ttx
Tests/subset/data/expect_no_hinting_desubroutinize_CFF.ttx
Tests/subset/data/expect_no_notdef_outline_cid.ttx
Tests/subset/data/expect_no_notdef_outline_otf.ttx
Tests/subset/data/expect_notdef_width_cid.ttx

Fixes #994 
According to @benkiel, when a CFF PrivateDict contains an empty SubrsIndex (one with no local subroutines), Windows rejects the font.
If the SubrsIndex is left empty by the subsetting operation, we delete it from the PrivateDict.

[subset] delete empty SubrsIndex after subsetting CFF

---

Lib/fontTools/misc/xmlReader.py
Lib/fontTools/ttLib/__init__.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttx.py
Tests/misc/xmlReader_test.py

The split-glyf-to-one-glyph-per-file feature is only partially implemented, as it was discussed here:
https://github.com/fonttools/fonttools/issues/153#issuecomment-346677171
The UFO3 glyph-to-filenames scheme needs to be implemented, and the semantic of -g (splitGlyphs) option needs to be changed to also imply -s (splitTables).
I need to cut a bugfix release today, but I don't want to ship this incomplete feature. I prefer to temporarily revert, tag a release from master branch, then push this to a separate branch so that @bamidei can complete his work when he gets the chance.

Temporarily revert PR #1035 bamidei/split_g_l_y_f_to_one_per_file

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

A multiple substitution may have a single destination, in which case it will look just like a single substitution. So if there are both multiple and single substitutions, upgrade all the single ones to multiple substitutions. Previously we would just give an error message in the builder and abort, which means certain valid OpenType lookups can’t be represented by feature files.
This is the same logic implemented by FontForge (actually the explanation above is almost copied verbatim from its source), makeotf does not do this AFAIK but I consider it a bug not a feature.
Fixes https://github.com/fonttools/fonttools/issues/612

[feaLib] Allow mixed single/multiple substitutions

---

MANIFEST.in

`*.afm` files are missing from MANIFEST.in causing `make check` to fail on pypi
releases. This PR adds the missing line.

`*.afm` files are missing from MANIFEST.in

---

Lib/fontTools/svgLib/path/parser.py
Tests/svgLib/path/parser_test.py

Implement the arc to curve points calculation using the original
svg.path library and use the curve points for the pen.
The Arc class and methods to parameterize and get curve points are
copied.
This makes the svg to glif conversion possible for any SVGs.
Follow up for 71e97b3e74f2cc8061dfd3ada6d436d7ff3173d1

svgLib: Add support for arcs in SVG path parser

---

Lib/fontTools/unicodedata/OTTags.py
Lib/fontTools/unicodedata/__init__.py
Tests/unicodedata_test.py

Fixes https://github.com/fonttools/fonttools/issues/1112
This implements the same logic found in harbfuzz [hb-ot-tag.cc](https://github.com/harfbuzz/harfbuzz/blob/461a605fdec3361a038d3715adf615353c4f91fa/src/hb-ot-tag.cc#L127) to convert between Unicode (or ISO 15924) script codes to [OpenType script tags](https://www.microsoft.com/typography/otspec/scripttags.htm).
/cc @twardoch

unicodedata: add ot_tags_from_script function

---

Lib/fontTools/ttLib/tables/otConverters.py
Tests/ttLib/tables/otConverters_test.py
Tests/varLib/data/test_results/InterpolateLayoutGPOS_size_feat_same.ttx

Fixes https://github.com/fonttools/fonttools/issues/1151

otConverters: don't write XML comment if NameID value is 0 == NULL

---

Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/lexer_test.py
Tests/feaLib/parser_test.py

* ~~Compute `end_location` as well as location to be able to get the original text of any statement/block~~

Add option to parse one feature file without resolving included files

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

Raise a meaningful error instead of raising on `assert len(new) == 0, new`.

feaLib.parser: raise meaningful error for substitution of multiple glyphs by multiple glyphs

---

Lib/fontTools/misc/textTools.py

go back to using `literal_eval`, as nobody does complex expressions in TTX files, and eval is evil.
Fixes https://github.com/fonttools/fonttools/issues/164

textTools: use ast.literal_eval for safeEval

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

This allows to build only some of the supported tables and ignore the others.
FYI, I need this for ufo2ft. 
(TL;DR I have to build the GSUB features before the GPOS ones, so I can use the subsetter's `closure_glyphs` logic to find all the glyphs that are "reachable", i.e. can be substituted from an initial list of characters, e.g. all the right-to-left glyphs, etc.)

[feaLib] add `tables` argument to only build some tables (e.g. GSUB)

---

.travis.yml

Travis CI has been experiencing maintainance problems with the macOS infrastructure, and in fact it has become too slow to be useable. It's better we temporarily enable `allow_failures` in combination with `fast_finish` for the OSX builds, so that the CI goes green as soon as the other builds have completed.
https://blog.travis-ci.com/2013-11-27-fast-finishing-builds

[travis] fast_finish + allow_failures for OSX builds

---

Lib/fontTools/varLib/__init__.py

The interpolatable TTFs used to generate the variable font may already contain a valid and more detailed STAT table.

varLib: don’t fail if STAT already in font

---

Lib/fontTools/ttx.py

...to accommodate sizes and offsets in the 10s of megabytes.
Or should it go one further even?

[ttx -l] Increase the width of the length and offset fields by one

---

Lib/fontTools/feaLib/error.py
Lib/fontTools/feaLib/lexer.py

subclass of FeatureLibError, only raised if IOError.errno == ENOENT (i.e. FileNotFoundError)
https://github.com/googlei18n/fontmake/issues/157#issuecomment-367380471
Will be useful in ufo2ft to detect when an included feature file doesn't exist and print a nicer error message explaining that includes must be relative to the UFO itself, and not relative to the embedded features.fea file.
https://github.com/unified-font-object/ufo-spec/issues/55

feaLib: add IncludedFeaNotFound error

---

Lib/fontTools/ttLib/ttFont.py

Issue report: #1188 
Closes #1188 
Recognized in fontTools version 3.22.0 (PyPI release) with Python 3.6.4 interpreter
Problem: Attempt to dump split OT tables with ttx leads to NameError.  This PR moves the xmlWriter import from within the public `saveXML` method to the top of the ttFont module.
Replicated and confirmed test failure with this test: 
https://github.com/chrissimpkins/fonttools/blob/88b0446d066ee72ad70eb41b382d184875c2fcbd/Tests/xmlwriter_test.py#L1-L14
and left this in a separate branch because I don't know how you are testing your ttx dumps in testing to contribute it here. Can confirm that it fails before this change and does not fail after the change.

[ttFont] fixes xmlWriter import error in _saveXML method with ttx split tables request

---

Lib/fontTools/cffLib/__init__.py

This PR is related to #1177.
As is discussed, parseEncoding0 may receive unexpected file position due to lazy-load of 'charset'.
So I save file position before calling parseEncoding0 and restore the position at the beginning of parseEncoding0.
Similar modification is applied to parseCharset0 because of symmetry. Actually it may not be needed since 'strings' which has possibility of lazy-load seems to be always loaded before calling parseCharset0.

[cffLib] save file position against lazy-load of charset

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
Lib/fontTools/voltLib/ast.py
Lib/fontTools/voltLib/parser.py
Tests/feaLib/builder_test.py

I want to change the ufo2ft featureWriters API so that they will manipulate `feaLib.ast.FeatureFile` objects, instead of outputting strings.
Currently, the location is a required positional argument, and it's always the first; in addition, all the constructor arguments are implemented as required positional arguments. 
This makes it cumbersome to create new ast elements from code, as one has to provide a `None` location as first argument, and then one has to pass all the default values for the subsequent positional arguments. The call becomes a very long, with lots of unnecessary `None`s. For example, compare these two (old and proposed) methods to create a new `ValueRecord` object (e.g. for use in a `PairPosStatement` or kerning):
```diff
- value = ast.ValueRecord(None, False,
- …
```

[fealib] set AST element's location=None by default

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/spec8d.fea
Tests/feaLib/data/spec8d.ttx
Tests/feaLib/parser_test.py

AFAICT this is working. The expected TTX was compared with what makeotf produces.
The test is failing because FEA round tripping produces equivalent instead of exactly matching statements. Not sure what's the best way to address it.
The `cvParameters` block has a series of rules —see the header of *spec8d.fea* file— which the current code does not enforce.

[feaLib] Support params in character variant features (cvXX)

---

Snippets/checksum.py

We needed a concise (i.e., not ttx dumps + text diffs) way to describe, maintain the state of, and compare compiled OpenType tables across builds. This was driven by the need to provide an approach for Linux packagers to confirm that their font compiles from source do not differ meaningfully (read that as affecting renders) from upstream builds as their build dependency versions across our entire build toolchain (and dependency of dependency of dependency chain...) diverge from our own by nature of the way that most Linux distros package and release software.
This script represents my attempt at a solution to this issue since direct SHA1 hashes of the binary files will always differ when build times differ, as will diffs of full ttx dumps from the font files, unless we force the …

[Snippets] SHA1 hash checksum list generation and testing script for font binaries and select OpenType table data

---

Lib/fontTools/misc/filenames.py
Lib/fontTools/misc/xmlReader.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ttx.py
Tests/misc/filenames_test.py
Tests/misc/xmlReader_test.py
Tests/ttx/ttx_test.py

I rebased @bamidei original PRs (https://github.com/fonttools/fonttools/pull/1035 and https://github.com/fonttools/fonttools/pull/1132) on the current master branch.
With this `ttx` gets a new `-g` option that will dump each glyph from the glyf table as an individual ttx file, in the same directory as the parent ttx file, and with the latter's filename plus an `_` and the glyph name (and the ".ttx" file extension). For simplicity, the `-g` (split glyphs) option also implies the `-s` (spit tables) option, i.e. can't use split glyphs only without also splitting the tables.
The separator between the `_g_l_y_f` table tag and the glyph names in the ttx file name was chosen to be "_" instead of ".",  so that the glyf table's ttx file (containing the index of individual glyph's ttx files) …

[ttx] add option to dump glyf table's glyphs as individual ttx 

---

Lib/fontTools/varLib/__init__.py

Added a command line flag to varLib, and parameter to varLib.build() to disable IUP optimization. This is handy for building fonts with / without IUP for debugging.

Add flag to disable IUP optimization

---

Lib/fontTools/ttLib/ttFont.py

This implements the [`__enter__` and `__exit__` context guard](https://www.python.org/dev/peps/pep-0343/) methods in the `TTFont` class. With this you can do something like
```python
from fontTools.ttLib import TTFont
with TTFont('/path/to/font.ttf') as font:
print(font.getGlyphNames())
```
and have the file auto closed when the block is exited. This seems pretty straight forward, but I'm happy for any feedback.

Add context guard to ttfont

---

Lib/fontTools/misc/py23.py

I'm not sure if it was intentional to make the Tag type so strict for Python 3, but it breaks when trying to compare the Tag to a None type. 
Even though a tag couldn't/shouldn't be set to None, the expectation is still that it would work like a string.

Fixes the eq comparison of the Tag object to work in a comparison with None type

---

Lib/fontTools/misc/psLib.py
Lib/fontTools/t1Lib/__init__.py

There are Type 1 fonts out there that use non-ascii characters in their copyright notice, and fonttools chokes on them. While I am not aware of how to determine the proper encoding, I'm happy with just guessing macroman. This doesn't change the default behavior.

allow an encoding to be specified when parsing a Type 1 font

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/BuildMain.ttx
Tests/varLib/data/test_results/Mutator.ttx

STAT 1.0 is deprecated
See https://github.com/googlei18n/fontmake/issues/417
also we should use the same nameIDs that were defined for the fvar, not add additional ones.

[varLib] make STAT 1.2, and reuse fvar nameIDs

---

Lib/fontTools/ttLib/tables/otTables.py

Log a warning instead of asserting, and allow decompiling ClassDef tables with invalid format.
Fixes https://github.com/fonttools/fonttools/issues/1235

Allow decompiling bad ClassDef tables with invalid format

---

Lib/fontTools/varLib/mutator.py
Tests/varLib/data/test_results/Mutator.ttx
Tests/varLib/data/test_results/Mutator_IUP-instance.ttx

Fixes https://github.com/fonttools/fonttools/issues/1227

[varLib.mutator] prune fvar nameIDs from instance's name table

---

Lib/fontTools/ttx.py
Tests/ttx/ttx_test.py
requirements.txt
tox.ini

This PR increases the test coverage of the source in the ttx module from 48% to 94%.  
It includes tests for the following:
- `ttx.Options` class
- `ttx.ttCompile` function
- `ttx.ttList` function
- `ttx.main` function
After discussion with @anthrotype, I added zopfli as a tox testing dependency (in the tox.ini settings file https://github.com/fonttools/fonttools/commit/cf5b31e9c66751c86084cb6604bbe9e156209717) to test ttx --> woff compiles using zopfli.  The requirements.txt file was not modified.
While the lines in ttCompile are executed, I did not add tests across all combinations of possible requests for the following:
https://github.com/fonttools/fonttools/blob/ceb41ec484b3aed5127962a3e2c2030a56d704e1/Lib/fontTools/ttx.py#L280-L283
Two minor issues were found during the testing:
1) …

Add ttx tests

---

Doc/source/designspaceLib/readme.rst
Doc/source/designspaceLib/scripting.rst
Lib/fontTools/designspaceLib/__init__.py
Tests/designspaceLib/designspace_test.py

* remove checkDefault, checkAxes and any kind of guessing about the axes. The default is the master located at the default value of all axes.
* add findDefault returns the sourceDescriptor for the default. 
* stray conditions are wrapped in a conditionset when reading.
* add some tests.

designspaceLib remove checkDefault, checkAxes

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/models.py
Tests/ttLib/tables/_g_l_y_f_test.py

Early on I pushed https://github.com/fonttools/fonttools/commit/0055f9414ca5094b0c9beb0176ac4998cdbbba70 to fix an OverflowError occurring while computing deltas in VariationModel.getDelta, when the values don't fit a signed short integer.
https://github.com/fonttools/fonttools/commit/0055f9414ca5094b0c9beb0176ac4998cdbbba70
However, I think a better fix is to change GlyphCoordinates so that whenever it is about to modify its inner array, it first checks that the value does not overflow, and if it does, upgrades it to an array of floats (doubles actually).
It might be a bit slower, but I think it's better than checking for overflow errors everywhere we use glyph coordinates.

Fix GlyphCoordinates overflow

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

The standard has been changed to allow any languages under the DFLT script. This patch removes the test and raised error that stops users from using languages other than dflt with the DFLT script.

Allow any languages under DFLT script

---

Lib/fontTools/misc/psCharStrings.py
Tests/misc/psCharStrings_test.py

Optimizes the charstring's bytecode by encoding as integers all float values that have no decimal portion. This optimization is expected to reduce the file size of CFF2 fonts that have intermediate masters.
Related to adobe-type-tools/afdko#444
Many thanks to @cjchapman for the help on the fixed point math.

Optimize the charstring's bytecode

---

Lib/fontTools/ttLib/tables/otTables.py
Tests/ttLib/tables/otTables_test.py

if an offset overflows within a MarkBasePos (GPOS lookup type 4), we attempt to split it by moving half of the mark classes to the new subtable.
Fixes https://github.com/googlei18n/fontmake/issues/450

atttempt to fix offset overflows in MarkBasePos subtables

---

Lib/fontTools/cffLib/specializer.py
Tests/cffLib/specializer_test.py

Fixes https://github.com/googlei18n/ufo2ft/issues/266.

[cffLib.specializer] Leave 1 stack free area for subroutinizer use

---

Lib/fontTools/ttLib/tables/T_S_I_C_.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otData.py

TSIC is a source table for Visual TrueType to maintain sources for the cvar variation table. Visual TrueType will generate this table to maintain the user intended CVT values as various point in variation space. This table is removed prior to shipping a font. Similar in concept to other TSI* tables already supported in fonttools.

TSIC table support a Visual TrueType source table

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/data/PairPosSubtable.fea

If Coverage is None then the subtable is a noop that does nothing and there is no point in building it. As a bonus, it makes OTS happy since it will reject subtables where coverageOffset is NULL (0), and the spec does not say whether this is allowed or not.

[feaLib] Skip noop class PairPos subtables

---

Lib/fontTools/subset/__init__.py

This change addresses an issue that pyftsubset --no-hinting on a CFF font does not drop three optional hinting dict keys from Private dict: ForceBold, LanguageGroup, and ExpansionFactor.
Before:
```
pyftsubset --no-hinting SourceHanSans-Regular.otf --unicodes=4E00 --output-file=out.otf ; tx -dcf out.otf |& grep LanguageGroup
1 LanguageGroup
```
After:
```
pyftsubset --no-hinting SourceHanSans-Regular.otf --unicodes=4E00 --output-file=out.otf ; tx -dcf out.otf |& grep LanguageGroup
```

[subset] --no-hinting to drop LanguageGroup etc

---

Lib/fontTools/subset/__init__.py

The subsetter was omitting the name IDs referenced by the STAT table, leaving a STAT table with invalid name IDs. I add these name IDs in the same methodology as fvar.

Include nameIDs referenced by STAT table

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/ttFont.py

See https://github.com/unified-font-object/ufo-spec/issues/74
Using Glyph.drawPoints() will make sure the point indices are not changed from the original. This is vital when the font has TrueType instructions which are based on point indices.

Add PointPen support to TT Glyph objects

---

Lib/fontTools/ufoLib/__init__.py
Lib/fontTools/ufoLib/glifLib.py

UFOWriter is already sharing some methods with UFOReader.
I think it would make sense to make it a subclass so that it extends the reader class with its additional writer-specific methods, effectively becoming a UFOReaderWriter.
This would allow, for example, to use the same UFOWriter instance for initializing a Font object, do stuff with it, and finally writing to it inplace.
Comments?

make UFOWriter a subclass of UFOReader, use mixins for shared methods

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/data/test.otf.ttx
Tests/fontBuilder/data/test.ttf.ttx
Tests/fontBuilder/fontBuilder_test.py

(I quickly demoed this at the FontTools meeting at Robothon in The Hague.)
This PR contains a new fontTools submodule called "fontBuilder", which contains a convenient wrapper class around TTFont called FontBuilder, making it a lot easier to create a working font from scratch with code. It supports TTF and OTF, and a little bit of variations.
Some features may be a little arbitrary, and possibly reflect what I needed the most at the time I wrote this.
I realize work may be needed before this can be accepted. It definitely needs some documentation/examples (at least in the module doc string).

[WIP] FontBuilder

---

Lib/fontTools/ttLib/sfnt.py
Lib/fontTools/ttLib/tables/F__e_a_t.py
Lib/fontTools/ttLib/tables/G__l_a_t.py
Lib/fontTools/ttLib/tables/S__i_l_f.py
Lib/fontTools/ttLib/tables/S__i_l_l.py
Lib/fontTools/ttLib/tables/grUtils.py
setup.py

This fixes a number of python3 issues affecting Graphite tables particularly regarding writing binary fonts.
The only issue outside of Graphite tables is that under python3 writing an sfnt resulted in a table length including the padding 0 bytes (to a 4 byte boundary) when it should not.

Fix python3 file writing issues and table compression

---

Lib/fontTools/varLib/featureVars.py

Fixed bug that tried to get an attr off a LangSysRecord rather than a LangSys. Fixes #1365
A test case would be nice, but I don't see a quick way to add this. Open for suggestions. To add this to the existing test requires adding some OT features to (some of the) ufos in the master_ufo folder.

[varLib] Fixing #1365: AttributeError in addFeatureVariations()

---

Lib/fontTools/mtiLib/__init__.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/t1Lib/__init__.py
Lib/fontTools/ttx.py
Lib/fontTools/unicode.py
MetaTools/buildTableList.py
MetaTools/roundTrip.py
Tests/designspaceLib/designspace_test.py

Hello,
This is a little patch to fix several file descriptor leaks first, and also to prefer the use of the `with` context manager when dealing with files to ensure file descriptors are always cleanly closed.
I tried to separate commits as much as possible. Let me know if it needs more work/rebase or if some changes are not acceptable as is :)
About the change in `unicode.py` I think this patch could be better:
```diff
diff --git a/Lib/fontTools/unicode.py b/Lib/fontTools/unicode.py
index 00e13bb6..ef3ed695 100644
--- a/Lib/fontTools/unicode.py
+++ b/Lib/fontTools/unicode.py
@@ -4,7 +4,6 @@ from fontTools.misc.py23 import *
def _makeunicodes(f):
import re
lines = iter(f.readlines())
-	f.close()
unicodes = {}
for line in lines:
if not line: continue
@@ -19,8 +18,11 @@ class …
```

Fix several ResourceWarning: unclosed file and some related improvement

---

Lib/fontTools/ttLib/tables/ttProgram.py
Lib/fontTools/varLib/mutator.py
Tests/varLib/data/master_ttx_getvar_ttf/Mutator_Getvar.ttx
Tests/varLib/data/test_results/Mutator_Getvar-instance.ttx
Tests/varLib/mutator_test.py

(1) Checks if bytecode of any glyph uses GETVARIATION opcode
(2) If true, adds an IDEF at the end of the fpgm table and modifies 2 attributes in maxp table.

Add IDEF for GETVARIATION opcode

---

README.rst

Fixes `tox` broken URL in README file

Fix tox url in README

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/subset/cff.py
Lib/fontTools/varLib/cff.py

varLib subset CFF2] Set PrivateDict nominal and default WidthX to None
Address issues raised in #1403
I do think setting the dummy CFF2 PrivateDict nominalWidthX and defaultWidthX to None, which leads to the charstring.width also being None, is a good idea. I originally set them to 0, which produces a charstring width of 0, in order to avoid problems with logic that assumes that the field is good for math. However, I now think that it is better to find errors around charstring type assumptions earlier than later.
"drop_hints()" is actually not wrong - I did look at this when making the changes. For CFF2 charstrings, self.width is always equal to self.private.defaultWidthX, so the width is never inserted. This is because in psCharstrings.py::T2WidthExtractor.popallWidth(), the test …

Clean cff2 3

---

Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/subset/cff.py

Fixed psCharstrings so that calc_bounds will run. I would guess no-one has tried to use a BoundsPen on a CFF2 VF before - thanks to Chris Chapman. It now returns a result only for the default instance.
Fixed bug in subsetting: removed assert that a Subr is not empty after subsetting or de-hinting. CFF2 Charstrings do not have terminal "return' op.

cff2 vf fixes. Make calc_bounds work, fix subsetting bug.

---

Lib/fontTools/misc/plistlib.py
Tests/misc/plistlib_test.py

This is needed to make ufoLib2's fontinfo guidelines and gasp records serialize correctly.

[plistlib] Treat Mapping objects as dicts

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/BuildMain.ttx

The Windows 10 Font preview can handle fonts with STAT version 1.2 but other applications do not and only display the default named instance.
For example the Windows\Fonts folder, Word or WordPad only show the default named instance when the STAT is version 1.2 but they display all the named instances when the STAT is version 1.1.
This was tested in Windows 10 Pro, Version 1803, build 17134.407.

Pin STAT to version 1.1

---

Lib/fontTools/cffLib/__init__.py

However, an AssertionError is raised further on, when dumping the test font.

[cffLib] fixing #1426

---

Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/ttLib/sfnt.py
Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/interpolate_layout.py
Tests/designspaceLib/designspace_test.py
Tests/varLib/varLib_test.py

with source descriptors containing pre-loaded TTFont instances
Continuation of https://github.com/fonttools/fonttools/pull/1416

[varLib] make `build` also accept DesignSpaceDocument objects

---

Tests/misc/psCharStrings_test.py

Adds test for misc.psCharStrings.encodeFloat that exposes a bug with "E+"
For a value like `9.876537e+24` the encodeFloat raises a KeyError exception.
This patch adds a test for `misc.psCharStrings.encodeFloat`
Note: I'm submitting a separate PR with an updated version of `encodeFloat` that passes the tests.
```
$ pytest Tests/misc/psCharStrings_test.py
...
Lib/fontTools/misc/psCharStrings.py:244: KeyError
==== short test summary info ====
FAIL Tests/misc/psCharStrings_test.py::T2CharStringTest::test_encodeFloat
==== 1 failed, 4 passed in 0.15 seconds ====
```

Adds test for misc.psCharStrings.encodeFloat that exposes a bug

---

Lib/fontTools/misc/psCharStrings.py
Tests/misc/psCharStrings_test.py

This patch:
- Adds a unit test for `misc.psCharStrings.encodeFloat`
- Fixes a bug in `encodeFloat` where a number like `1.23e+4` would raise a KeyError exception
- Fixes an issue where the produced data would be of too high precision for 32-bit parsers, like macOS. See https://github.com/googlei18n/ufo2ft/issues/306
This is a follow-up PR to this small proof-of-issue PR: https://github.com/fonttools/fonttools/pull/1429
A faster implementation of `encodeFloat` is available here separately: https://gist.github.com/rsms/efd5663749a9b66bc53be8f85becc9d2 — introducing this more efficient implementation caused test failures in ttLib/tables/C_F_F_test which seemed like too much changes for one PR.

Fixes bug in misc.psCharStrings.encodeFloat and adds test

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/fontBuilder_test.py

as of https://github.com/fonttools/fonttools/pull/1359, both sets of names are added by default. This allows users to optionally exclude Macintosh platform names (i.e. mac=False).

fontBuilder: add options to setupNameTable to disable Mac (or Win) names

---

Doc/source/designspaceLib/readme.rst
Doc/source/designspaceLib/scripting.rst
Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/mutator.py
Tests/varLib/data/Build.designspace
Tests/varLib/data/test_results/BuildMain.ttx

Now that addMultilingualName method also adds mac names by default (#1359), we can use it in
varLib instead of `addName`, thus enabling support for localized axes and named instances' names.
The language identifiers are expected to be minimized, i.e. not contain default script/region subtags -- until we implement the minimizeSubtags algorithm from ICU/CLDR (see discussion at #930).

[varLib] use addMultilingualName method to support localized axis and instance names

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/SparseMasters.designspace
Tests/varLib/data/master_ttx_interpolatable_ttf/SparseMasters-Bold.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/SparseMasters-Medium.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/SparseMasters-Regular.ttx
Tests/varLib/data/test_results/SparseMasters.ttx
Tests/varLib/varLib_test.py

When varLib.build receives "sparse" masters only containing a subset of the glyph outlines/metrics and minimal set of tables compared to the full base master font, we need a way to exclude the post.underlineThickness and post.underlinePosition values from being used to build the MVAR delta sets.
We need a post table (for truetype) if we want to use the glyph names only defined in there when we build gvar, HVAR, etc. from such sparse masters -- the glyph name is used as the key to group glyphs from different masters.
At the same time, a post table must have these two underline values defined to something.
Currently, varLib `_add_MVAR` function assumes that, if a given master contains a table (OS/2, hhea, post, etc), then all the MVAR-specific values in that table will be used when …

[varLib] ignore post.underline* from sparse masters when building MVAR

---

Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

When checking for duplicate anchors, the component number should be taken into account since the same anchors can be used for different components i.e. over ligatures.

[voltLib] Fix check for duplicate anchors

---

Lib/fontTools/subset/cff.py
Tests/subset/subset_test.py

Part of #1446
is it just setting the program to `["endchar"]` or am I missing something?

[subset] set emptied CFF charstrings to 'endchar' with --retain-gids

---

Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

The parser was still trying to read the next token even when the current token was END, but I think it should just stop reading here. When reading from `TSIV` table there can be null bytes at the end when would cause an exception in the lexer.

[voltLib] Don’t try to read past END

---

Lib/fontTools/misc/psCharStrings.py

This is an attempt to fix #1451 when dumping CFF2 table to ttx.
Instead of changing the signature of basically all the toXML/xmlWrite methods in cffLib to add an `isCFF2=False` parameter, what about we add a 'context' namespace attribute to XMLWriter that can hold misc data, such as whether 'isCFF2' the table we are dumping?

[cff2] fix AttributeError 'isCFF2' when dumping CFF2 with ttx

---

Lib/fontTools/misc/psCharStrings.py

A charstring is not guaranteed to end in an operator, so the final bytecodes 11 and 14 can be part of an encoded numeric value; so remove 'return' or 'endchar' at the program level instead of bytecode.
Fixes next issue from #1451

[cffLib] Fix for #1451

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/bug1459.fea
Tests/feaLib/data/bug1459.ttx
Tests/feaLib/parser_test.py

[feaLib] distinguish missing value and explicit '<NULL>' for PairPos2 format A

---

Lib/fontTools/voltLib/ast.py
Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

`PROCESS_MARKS` followed by a group name is used for `markAttachmentType` lookup flag, while followed by `MARK_GLYPH_SET` is used for `useMarkFilteringSet`. The code parsed both correctly but did not
distinguish between the two in the generated AST as it should since they compile to different lookup flags.

[voltLib] Distinguish different PROCESS_MARKS

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/parser_test.py

`ValueRecord` had a `makeString()` method that takes an optional `vertical` argument, but no code outside the tests sets this argument. Renamed it to `asFea()` and dropped the `vertical`, so that it consistent with the
rest of feaLib.ast classes. This also fixes `ValueRecordDefinition.asFea()` which was calling the not implemented `ValueRecord.asFea()`

[feaLib] Implement ValueRecord.asFea() 

---

Lib/fontTools/voltLib/ast.py
Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

This is a followup to commit 94633e9f46975c356ec3a2d21ed30768c2fa0cd5, where I mistakenly made it return an `Enum` but `parse_coverage_()` it not used only for `ENUM`s and in many (most?) places returning an `Enum` is wrong as you have a list of separate items that has to remain separate.

[voltLib] Return a tuple from parse_coverage_()

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/varLib_test.py

MVAR table generation currently blows up if you throw ufo2ft-2.7.0-style sparse masters (SFNT objects without an `OS/2` and other non-outline-related tables) into the mix.
The core issue seems to be that `VariationModel::getDeltas` assumes that are as many master values (values from an existing `OS/2` table) as there are `deltaWeights`. This assumption breaks because there are no master values from sparse masters, yet they have `deltaWeights`.
This blocks https://github.com/googlei18n/fontmake/pull/501.
Investigation ongoing.

[varLib] Fix MVAR generation for sparse masters

---

Lib/fontTools/feaLib/ast.py

When a `MarkClassDefinition` is inside a block, it gets double indentation compared to the rest of the block. It should ignore the `indent` argument like other similar statements.

[feaLib] Fix double indentation of markClass

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/ast_test.py

Add table names to the reserved keywords and make sure glyph names are always escaped written written back to feature files. This probably only affects AST tree that is created programmatically, not by parsing existing feature files.

[feaLib] Consistently escape glyph names

---

Lib/fontTools/varLib/__init__.py
NEWS.rst
Tests/varLib/varLib_test.py

This reverts commit ef1d4cd02d1e46f5dac3914f547a6e4275cf3077, which caused a crash in `interpolate_layout()` when `deepcopy`ing OTFs: https://travis-ci.org/googlei18n/fontmake/jobs/488967547#L843.
Amend code and tests while I work on a real fix.

Revert "load_masters: actually assign font attributes"

---

Lib/fontTools/varLib/__init__.py
Tests/cffLib/cffLib_test.py
Tests/varLib/interpolate_layout_test.py
Tests/varLib/varLib_test.py

Deepcopying a TTFont with a CFF table can result in an infinite recursion on Python 3 under certain circumstances.
@anthrotype found that CFFFontSet keeps a reference to the TTFont object that holds it to get at the glyph order at some point: https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/cffLib/__init__.py#L34. Maybe this messes with `deepcopy`.

WIP: Fix deepcopy-ing of CFFs

---

Lib/fontTools/cffLib/__init__.py

The dunder method doesn't seem to be doing anything other than providing an `in_cff2` attribute. Do that with a property instead of bending `__getattr__`.
This one confused me when I was working on https://github.com/fonttools/fonttools/pull/1488.

[cffLib] Replace `PrivateDict.__getattr__` with property for `in_cff2`

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/subset/cff.py

@readroberts PTAL
Fixes #1483
'remove_unused_subroutines' method expects a 'GlobalSubrs' attribute but the 'desubroutinize'
method deletes it. We don't have to call 'remove_unused_subroutines' at the end of 'desubroutinize'
method, we can just delete all the local subroutines, and clear the GlobalSubrsIndex.
Only call 'remove_unused_subroutines' method once, when we are not desubroutinizing.

[subset] Fix 'AttributeError: GlobalSubrs' with --desubroutinize option

---

Lib/fontTools/feaLib/lexer.py
Tests/feaLib/lexer_test.py

Matches AFDKO’s makeotf behaviour.

[feaLib] Allow hyphen in glyph class names

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

As explained here: https://github.com/fonttools/fonttools/issues/1468
If the ValueRecord comes after a suffix instead of directly after the affected glyphs then we still want to read it. Currently the ValueRecord is silently skipped, resulting in missing kerning. 
There's really no way to roundtrip with asFea() because from a compiled source we can't know that the original FDK code was written this way. That means if the original code is 
`position L' quoteright -150;`
then the asFea() output will become
`position L' -150 quoteright;`
I don't see any problem with this as this "special case" format is really just a convenience for FDK source and I assume most code is written the normal way. If not we probably would have run into this long ago.

Read special case of contextual positioning

---

Lib/fontTools/subset/cff.py
Tests/subset/data/expect_no_hinting_desubroutinize_CFF.ttx
Tests/subset/data/test_hinted_subrs_CFF.desub.ttx
Tests/subset/data/test_hinted_subrs_CFF.ttx
Tests/subset/subset_test.py

Fixes issue 1493
The  code was skipping executing a subroutine if it had already been desubroutinized. The initial set of vstemhm and hstemhm operators and values may be in a subroutine. If a charstring is being executed which calls such subroutines, they still need to be executed in order to count the number of hint values seen, so that the byte length of the hintmask can be calculated.
I fixed this bug by executing subroutines even if they have already been desubroutinized, as long  as  (we don't know yet if we are doing hintmasks) or ( we do need a hintmask, but have not yet seen it).

[subset CFF] Fix de-subroutinizing bug when subroutines contain hints

---

Lib/fontTools/feaLib/ast.py

Similar to 05329ed033ae0aa2451272a39ada9aad9f1f5ed7.

[feaLib] Fix double indentation of subtable

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/AlternateSubtable.fea
Tests/feaLib/data/AlternateSubtable.ttx
Tests/feaLib/data/ChainPosSubtable.fea
Tests/feaLib/data/ChainPosSubtable.ttx
Tests/feaLib/data/ChainSubstSubtable.fea
Tests/feaLib/data/ChainSubstSubtable.ttx
Tests/feaLib/data/LigatureSubtable.fea
Tests/feaLib/data/LigatureSubtable.ttx
Tests/feaLib/data/MultipleSubstSubtable.fea
Tests/feaLib/data/MultipleSubstSubtable.ttx
Tests/feaLib/data/SingleSubstSubtable.fea
Tests/feaLib/data/SingleSubstSubtable.ttx

Although AFDKO’s makeotf supports subtable breaks only in pair pos lookups, I believe that is an implementation limit that we don’t have to follow; all OpenType lookups has subtables and it should be possible to code that in the feature files.
This PR adds `subtable` statement support to many lookups, but not all of them; I added it to the lookups I had tests for or was easy enough to construct tests for.
This also make unsupported `subtable` a warning instead of an error, to follow makeotf.

[feaLib] Support subtable statement in more places

---

Lib/fontTools/ttLib/tables/C_O_L_R_.py
Lib/fontTools/ttLib/tables/V_O_R_G_.py
Lib/fontTools/ttLib/tables/_c_m_a_p.py
Lib/fontTools/ttLib/tables/otTables.py
Tests/ttLib/tables/_c_m_a_p_test.py

- changed some uses of list(map(...)) to list comprehensions and explicit loops, avoiding possibly large unneeded tmp lists
- replaced use of eval() with int()
- adding tests to verify all changes are covered
(There's still a lot of duplicate logic in various decompile methods, but that's for another time.)

[cmap,VORG,COLR,otTables] misc idiomatic updates

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Tests/ttLib/tables/TupleVariation_test.py
Tests/ttLib/tables/_g_v_a_r_test.py
Tests/varLib/data/test_results/SparseMasters.ttx

I think it makes it more legible if the peak value in a TupleVariation subtable is written _after_ the `min` and before the `max` value defining a given region, instead of alphabetically `max`, `min` and `value`.
The XMLWriter supports writing element attributes in an arbitrary order so let's use that.
TTX files from previous versions will continue to be parseable since attributes order is not significant in XML.

TupleVariation.toXML: sort attrs min/value/max in TTX dump

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/Build.ttx
Tests/varLib/data/test_results/BuildMain.ttx
Tests/varLib/data/test_results/SparseMasters.ttx

when 'vmtx' is present in a font, use that to compute the third and fourth 'phantom points'.
When not present, use the glyph bbox yMax and yMin coords.
NOTE that previously the bottomSideY was incorrectly set to `-glyph.yMin` (with a minus sign).
However, the minus is not needed when we use the bbox.
Positive vertical advance grows towards negative Y axis.
In the absence of vmtx, we default to using `yMax` as the y coordinate of the top origin and `yMax - yMin` as the vertical advance width; so the y coordinate of the advance height _point_ (bottomSideY) is `yMax - (yMax - yMin) => yMin`

varLib: use vmtx to compute phantom pts; fix the sign of bottomSideY

---

Lib/fontTools/designspaceLib/__init__.py
Tests/designspaceLib/data/test.designspace
Tests/designspaceLib/designspace_test.py

Consider axis mappings when determining the default source in a Designspace. The minimum/default/maximum values of an axis are always in user space while source and instance locations are always in design space. If a mapping exists for an axis, user and design space diverge.

designspaceLib, findDefault: consider axis mapping

---

Lib/fontTools/misc/py23.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

Raise TTLibError with the offending glyph name in the error message when a component (indirectly) references itself. Fixes #1545

[ttLib/glyf] Raise more specific error when encountering recursive components

---

Lib/fontTools/misc/arrayTools.py
Tests/misc/arrayTools_test.py

Somehow we forgot to replace `round` -> `otRound` in `arrayTools.calcIntBounds`.
This function is used by glyf table to compute the glyphs' bounding boxes.
We already use otRound (aka `int(math.floor(v + .5))`) to round glyph coordinates upon compiling glyf table. So, the use of python3's round in calcIntBounds was producing inconsistent roundings between the glyph coordinates and the glyph bbox (sometimes, i.e. only when the glyf table contains float coordinates, e.g. after instantiating with varLib.mutator).

arrayTools: calcIntBounds should use otRound, not round3

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/instancer.py
Tests/ttLib/tables/TupleVariation_test.py
Tests/varLib/instancer_test.py

This modifies `instantiateTupleVariationStore` function so that it merges TupleVariation tables that end up having the same axes 'tents' following partial instancing, by summing their deltas.
To do that, it needs to calculate the inferred deltas so it now takes two optional lists (origCoords and endPts) that are passed on to iup_delta function.
It also run iup_delta_optimize on the gvar deltas that are left after partial instancing and whose inferred deltas had to be interpolated (this can be optionally be disabled with `--no-optimize` CLI option).

[partial-instancer] merge overlapping tuple variations

---

Lib/fontTools/varLib/instancer.py
Lib/fontTools/varLib/varStore.py
Tests/varLib/data/PartialInstancerTest-VF.ttx
Tests/varLib/instancer_test.py

This is an alternative approach to #1577 
The first two commits are the same in this and the previous PR, they only diverge on the last commit.
The difference is that, instead of reimplementing the same logic twice for tuple and item variation stores, here I reduce the latter to the former using an adapter class, then run instantiateTupleVarStore and build a new Item VarStore from the result.

[partial-instancer] convert item to tuple varstore to reuse code

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/instancer.py
Lib/fontTools/varLib/merger.py
Lib/fontTools/varLib/mutator.py
Tests/varLib/instancer_test.py

this uses the same MutatorMerger class as is used in mutator module, slightly modified to optionally allow to keep VariationIndex tables when VarStore was only partially instanced.

[partial-instancer] support instantiating GDEF and GPOS

---

Lib/fontTools/ttLib/tables/S__i_l_f.py

FIx a single character typo in a call to sstruct.unpack

Fix typo in silf table

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/fontBuilder.py
Lib/fontTools/otlLib/maxContextCalc.py
Lib/fontTools/subset/__init__.py
Tests/fontBuilder/data/test.otf.ttx
Tests/fontBuilder/data/test.ttf.ttx
Tests/fontBuilder/data/test_var.otf.ttx
Tests/fontBuilder/data/test_var.ttf.ttx
Tests/fontBuilder/fontBuilder_test.py
Tests/otlLib/data/gpos_91.ttx
Tests/otlLib/data/gsub_51.ttx
Tests/otlLib/data/gsub_52.ttx
Tests/otlLib/data/gsub_71.ttx
Tests/otlLib/maxContextCalc_test.py
Tests/subset/subset_test.py

The value is only modified in the context of **fontBuilder** or **subset**. It will NOT be modified when using **ttx**.
`maxContextCalc.py` was copied from https://github.com/googlefonts/ufo2ft/blob/master/Lib/ufo2ft/maxContextCalc.py
Fixes #1191
Fixes #466

(Re)calculate OS/2.usMaxContext value

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/varLib/varStore.py
Tests/subset/data/TestHVVAR.ttx
Tests/subset/data/expect_HVVAR.ttx
Tests/subset/data/expect_HVVAR_retain_gids.ttx
Tests/subset/subset_test.py

Fixes subsetting HVAR/VVAR issues #1448 & #1587
When AdvWidth(Height)Map is missing from HVAR/VVAR, unused deltas are zeroed (with or without --retain-gids).
With --retain-gids, major/minor indices for an unused glyph is set to 0/0 if gid <= last used gid
With --retain-gids, if unused gid > last used gid, then its major/minor is set to that of last used gid (they are optimized out when the table is written out).
Added test cases to test_subset.py for HVAR & VVAR with and without --retain-gids

[subset] HVAR/VVAR with --retain-gids

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/instancer.py
Tests/varLib/data/PartialInstancerTest-VF.ttx
Tests/varLib/instancer_test.py

We don't actually apply deltas to hmtx/vmtx from HVAR/VVAR since these have already been applied from the gvar deltas when we call `glyf.setCoordinates` method using the glyph's four phantom points.
We simply call `instantiateItemVariationStore` on `{H,V}VAR.VarStore` in order to remove regions and scale remaining deltas, but we ignore the return value.
Also, we run `VarStore.optimize()` (which modifies the VarDatas layout) only when the HVAR/VVAR originally have an AdvWidthMap/AdvHeightMap.
If they do not (they use a direct implicit GID->VariationIndex mapping for advance deltas), then we keep the VariationIndex unchanged by not optimizing the VarStore.
If all the axes in fvar are being instanced, then we simply delete HVAR (just like varLib.mutator currently does).
Finally, supporting …

[instancer] support instantiating HVAR and VVAR  (TTF only for now)

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/ast_test.py

The code tries to write the short format when some values as None, but when writing the long format it would write any None value as is which is invalid, use 0 for None values instead.

[feaLib] don’t write None in ast.ValueRecord.asFea()

---

Lib/fontTools/ttLib/tables/S__i_l_l.py

'tis the season!
This didn't fire with normal ttx roundtrip testing because using the xml converts the bytes into a string masking the problem. It is only exposed if you roundtrip a font without going through XML.

Minor fixlet for Sill table

---

Lib/fontTools/ttLib/tables/_h_e_a_d.py
README.rst

Ensures that CFF FontBBox float values are rounded before being read into `_h_e_a_d` table.
Note: I had a look in regards to adding a unit test for this fix, but couldn't find any existing tests for class `table__h_e_a_d`. Do let me know if I missed an obvious place to add a test.
Resolves #1604

Fix: ttLib _h_e_a_d FontBBox rounding

---

Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/varLib/__init__.py
Tests/designspaceLib/designspace_test.py

Added `loadSourceFonts` method to `DesignSpaceDocument` object, which allows to use a custom opener function to load a font object from a SourceDescriptor's `path`, and store the result in memory inside the SourceDescriptor's `font` attribute.
The opener function is any callable that takes a path and returns a font -- _any_ font really.
In ufo2ft we assume source descriptor `font` holds a UFO (defcon.Font or similar), whereas in varLib.build we assume it is set to a ttLib.TTFont.

designspaceLib: add loadSourceFonts method with custom opener

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

When --recalc-bounds option is used the font extents in the head table need to be updated, but since tables are lazy-loaded by default the table will not be recompiled and will keep the old value. Force
recompiling the table by adding it to prune_post_subset tables, though I’m not 100% sure this is the best approach.

[subset] Update font extents in head table

---

Lib/fontTools/varLib/merger.py
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master0.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master1.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master2.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master3.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/TestFamily-Master4.ttx
Tests/varLib/data/test_results/Build.ttx
Tests/varLib/data/test_results/BuildMain.ttx
Tests/varLib/data/test_results/InterpolateLayoutMain.ttx
Tests/varLib/data/test_results/Mutator.ttx

The code was setting `GlyphClassDef.classDefs` for the base font to an empty dict then reading it from all fonts. It accidentally works when creating variable fonts because the `GlyphClassDef` of the other fonts
will be used, but when mutating there is only one font.
Fix by reading the glyph classes before assigning to an empty dict.

[varLib] Fix merging GDEF.GlyphClassDef in mutator

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/data/test.otf.ttx
Tests/fontBuilder/data/test.ttf.ttx
Tests/fontBuilder/data/test_var.ttf.ttx

An empty DSIG is enough to make MS applications happy and also fixes an error reported by MS Font Validator.

fontBuilder: Don't add a stub signature to DSIG

---

Lib/fontTools/varLib/featureVars.py
Lib/fontTools/varLib/instancer.py
Tests/varLib/instancer_test.py

we had forgotten to remap the ConditionTable.AxisIndex of remaining FeatureVariationRecords after dropping axes from fvar.
Also, we can drop lookups that are no longer referenced after we have subsetted or completely removed the FeatureVariations table.
This also adds unit tests for the instantiateFeatureVariations function, using the same test file "FeatureVars.ttx" used in varLib_test.py (the one built from Tests/varLib/data/FeatureVars.designspace with the dollar trick).

instancer: bugfixes and tests for instantiateFeatureVariations

---

Lib/fontTools/varLib/cff.py
Tests/varLib/data/test_results/BuildTestCFF2.ttx

There was a bug that caused the PrivateDict of the first region to be used for all others.
Fixes issue [varLib.cffLib] Bug in merging CFF2 PrivateDicts #1643.

[varLib.cff] Fix important bug in merging CFF2 PrivateDicts.

---

Lib/fontTools/varLib/cff.py
Tests/varLib/data/TestNonMarkingCFF2.designspace
Tests/varLib/data/master_non_marking_cff2/TestNonMarkingCFF2_ExtraLight.ttx
Tests/varLib/data/master_non_marking_cff2/TestNonMarkingCFF2_Regular.ttx
Tests/varLib/data/test_results/TestNonMarkingCFF2.ttx
Tests/varLib/varLib_test.py

Fixes issue: "KeyError in varLib.cff.merge_PrivateDicts #1632".

Fixes merge bug when VF source have no blends or no marking glyphs in any charstrings.

---

Lib/fontTools/unicodedata/Blocks.py
Lib/fontTools/unicodedata/ScriptExtensions.py
Lib/fontTools/unicodedata/Scripts.py

I run the `MetaTools/buildUCD.py` to donwload the latest blocks and scripts data from Unicode 12.1

Update Blocks, Scripts and ScriptExtensions to latest Unicode Data 12.1

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/BuildMain.ttx
Tests/varLib/data/test_results/SparseMasters.ttx
Tests/varLib/varLib_test.py

When building a variable font, varLib.build must make sure that the OS/2.usWeightClass is equal to the wght axis default location, that the OS/2.usWidthClass is set to the equivalent value (1-9) of
the wdth axis default location, and finally that post.italicAngle is set to the same default value as slnt axis.
Sometimes the base master doesn't have these values correctly set leading to discrepancies between OS/2 and post, on the one hand, and the fvar axes' default values.
See https://github.com/googlefonts/fontbakery/issues/2423

varLib: add set_default_weight_width_slant

---

Lib/fontTools/fontBuilder.py

Partially addresses #1660. This makes the otf minimal example work. The ttf example still doesn't work.

make the minimal examples work on windows 10

---

Lib/fontTools/varLib/__init__.py

When asked to build a "variable" font with only one source master, there's no variation data, we can skip building HVAR and gvar tables. The fvar and STAT table are still built.
Fixes https://github.com/fonttools/fonttools/issues/1670
Also see https://github.com/googlefonts/fontmake/issues/565

varLib: don't build empty HVAR or gvar tables

---

Lib/fontTools/cffLib/specializer.py
Tests/cffLib/data/TestCFF2Widths.ttx
Tests/cffLib/specializer_test.py

When checking if there was an initial width argument, old logic did not correctly sum the number of blend and non-blend arguments before the first hint or moveto operator.
Added test case. Old logic dropped the arguments for the hmoveto in the last glyph.

[cffLib specializer] Fix bug in programToCommands with CFF2 charstrings

---

Lib/fontTools/cffLib/__init__.py
Tests/cffLib/cffLib_test.py
Tests/cffLib/data/TestFDSelect4.ttx

Introduced in CFF2 table, but code does not limit it to CFF2 table. If
FDSelect format is set to 4, it will be read/written regardless of the
table version.

[cffLib] Support FDSselect format 4

---

.gitignore

Source: https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore
Allows e.g. to have a "venv" folder which I like to use.

Update gitignore with generic boilerplate

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

Allow the glyf table to be incomplete — to not contain all glyphs listed in the glyph order — when writing to XML. Partially addresses #684.

[ttLib] allow the glyf table to be incomplete when dumping to XML

---

Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/lexer_test.py
Tests/feaLib/parser_test.py

From https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.e:
> Decimal numbers must begin with a non-0 digit, octal numbers with a 0
> digit, and hexadecimal numbers with a 0x prefix to numbers and
> hexadecimal letters a-f or A-F.
Fixes https://github.com/fonttools/fonttools/issues/1541

[feaLib] Correctly handle octal numbers

---

tox.ini

let's see if this fixes the recent failues on Appveyor CI: e.g. https://ci.appveyor.com/project/fonttools/fonttools/builds/27126458/job/iomtsu4prflws4xu

tox.ini: pin pytest==5.1.1 to workaround issue with caplog fixture on windows

---

Lib/fontTools/pens/pointPen.py
Tests/pens/pointPen_test.py
Tests/pens/reverseContourPen_test.py

The PointToSegmentPen translates between PointPen and (Segment)Pen protocol.
In the SegmentPen protocol, closed contours always imply a final 'lineTo' segment from the last oncurve point to the starting point.
So the PointToSegmentPen omits the final 'lineTo' segment for closed contours -- unless the option 'outputImpliedClosingLine' is True (it is False by default, and defcon.Glyph.draw method initializes the
converter pen without this option).
However, if the last oncurve point is on a "line" segment and has same coordinates as the starting point of a closed contour, the converter pen must always output the closing 'lineTo' explicitly (regardless of the value of the 'outputImpliedClosingLine' option) in order to disambiguate this case from the implied closing 'lineTo'.
If it doesn't do …

PointToSegmentPen: preserve duplicate last point

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/G_P_K_G_.py
Lib/fontTools/ttLib/tables/G__l_o_c.py
Lib/fontTools/ttLib/tables/L_T_S_H_.py
Lib/fontTools/ttLib/tables/S__i_l_f.py
Lib/fontTools/ttLib/tables/T_S_I__5.py
Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_c_m_a_p.py
Lib/fontTools/ttLib/tables/_c_v_t.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/_g_v_a_r.py
Lib/fontTools/ttLib/tables/_h_m_t_x.py
Lib/fontTools/ttLib/tables/_l_o_c_a.py
Lib/fontTools/ttLib/tables/_p_o_s_t.py
Lib/fontTools/ttLib/tables/ttProgram.py
Lib/fontTools/ttLib/woff2.py
setup.cfg

Closes #868 
- removes pytest array.tostring deprecation warning filter in `setup.cfg`
- removes pytest array.fromstring deprecation warning filter in `setup.cfg`
- refactors array.tostring to array.tobytes across a number of modules
- refactors array.fromstring to array.frombytes across a number of modules

Refactor deprecated array tostring/fromstring methods to tobytes/frombytes

---

Lib/fontTools/subset/__init__.py

After subsetting some strikes might be empty (strikes don’t have to cover all glyphs equally) which would cause a key error later when saving the table.
Fixes https://github.com/fonttools/fonttools/issues/1633

[subset] Prune empty strikes in EBDT data

---

Lib/fontTools/ufoLib/__init__.py
Lib/fontTools/ufoLib/filenames.py
Lib/fontTools/ufoLib/glifLib.py
Lib/fontTools/ufoLib/plistlib.py
Lib/fontTools/ufoLib/utils.py
Lib/fontTools/ufoLib/validators.py
Tests/ufoLib/GLIF1_test.py
Tests/ufoLib/GLIF2_test.py
Tests/ufoLib/UFO1_test.py
Tests/ufoLib/UFO2_test.py
Tests/ufoLib/UFO3_test.py
Tests/ufoLib/UFOConversion_test.py
Tests/ufoLib/UFOZ_test.py
Tests/ufoLib/glifLib_test.py
Tests/ufoLib/testSupport.py

Use Python 3.6+ syntax, remove redundant code.

ufoLib: Clean up legacy code

---

Lib/fontTools/merge.py

Instead of appending font index to all glyph names and still potentially have duplicates, use similar code like we use and “post” and “CFF” tables to handle duplicate glyph names.

[merge] Handle duplicate glyph names better

---

Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

Both were treated as group names, as `NONE` was not checked at all and code for `ALL` was never reached.

[voltLib] Handle ALL and NONE in PROCESS_MARKS

---

Lib/fontTools/misc/fixedTools.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/ttLib/tables/F__e_a_t.py
Lib/fontTools/ttLib/tables/G__l_a_t.py
Lib/fontTools/ttLib/tables/S__i_l_f.py
Lib/fontTools/ttLib/tables/S__i_l_l.py
Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_a_v_a_r.py
Lib/fontTools/ttLib/tables/_f_v_a_r.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/_h_e_a_d.py
Lib/fontTools/ttLib/tables/_t_r_a_k.py
Lib/fontTools/ttLib/tables/otConverters.py
Tests/misc/fixedTools_test.py
Tests/misc/psCharStrings_test.py
Tests/ttLib/tables/TupleVariation_test.py
Tests/ttLib/tables/_a_v_a_r_test.py
Tests/ttLib/tables/_c_v_a_r_test.py
Tests/ttLib/tables/_f_v_a_r_test.py
Tests/ttLib/tables/_g_l_y_f_test.py
Tests/ttLib/tables/_g_v_a_r_test.py
Tests/varLib/instancer_test.py

Fixes https://github.com/fonttools/fonttools/issues/737
I changed `fixedToFloat` to NOT do any magic, simply return `value / (1 << precisionBits)`
The code of the previous fixedToFloat is now called `fixedToStr`, but returns a string and is used in `toXML` methods to write fixed-point numbers as compact decimal floats.
The function actually used in `toXML` methods is `floatToFixedToStr` (that in turn uses `fixedToStr`), because internally table objects store these fixed-point numbers as floats, not as integers.
But I still kept `fixedToStr` (and `strToFixed`) in `fixedTools` module, even though they are not used directly anywhere.
There is also a corresponding `strToFixedToFloat` that does the reverse and it's equivalent of doing `floatToFixedToFloat(float(string))`. This is used in …

don't round in fixedToFloat, unless we're dumping floats to XML

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

Found this one when I tried to add a name ID 25 string (type `str`) to a font that already had one (type `bytes`) and overlooked the `setName` method. Turns out there is no sanitization when you append name records manually to the `names` list.

[name] Handle duplicate name records with different `string` types

---

Lib/fontTools/ttLib/ttCollection.py

In ttCollection, I add "with statement context manager" like ttFont, so we can use ttCollection just like ttFont:
```
with TTCollection(font_path) as font:
pass
```

Add "with statement context manager" in ttCollection

---

Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/featureVars.py
Tests/designspaceLib/data/test.designspace
Tests/designspaceLib/designspace_test.py
Tests/varLib/data/FeatureVars.designspace
Tests/varLib/data/test_results/FeatureVars.ttx
Tests/varLib/data/test_results/FeatureVars_rclt.ttx
Tests/varLib/varLib_test.py

This PR implements #1625 and resolves #1371.
1. addFeatureVariations(): allow the feature tag to be specified (default to 'rvrn')
2. allow said feature to already exist, in which case we append new lookup indices to the existing feature
~Item 2 needs a test case.~
Update: what follows has been implemented in the meantime.
This needs integration with `varLib._add_GSUB_feature_variations()`, and _some_ way in the designspace file to specify what to do.
I propose the following:
Add a `processing` attribute to the `<rules>` tag, which can have a value of `"pre"` or `"post"`. "pre" will be default, and will use the `rvrn` feature for FeatureVariations. "post" will use the `rclt` feature instead, and will cause the substitutions to be done last in the GSUB processing order.
Example:
```xml …
```

[designspaceLib] [varLib] Allow FeatureVariations to be processed *after* other features

---

Lib/fontTools/ttLib/tables/otBase.py
Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/varLib/__init__.py
Tests/varLib/data/SingleMaster.designspace
Tests/varLib/data/test_results/SingleMaster.ttx
Tests/varLib/varLib_test.py

... even when the ItemVariationStore contains no Regions and thus we can't take the length of their VarRegionAxis arrays.
This is to appease older versions of OTS (< 8.0.0) which blindly enforce this rule and reject a VF that has, e.g., an empty HVAR table with no regions when the HVAR.VarStore.VarRegionList.RegionAxisCount != fvar.AxisCount.
Fixes https://github.com/fonttools/fonttools/issues/1670
Related:
https://github.com/fonttools/fonttools/pull/1671
https://github.com/googlefonts/fontmake/issues/565
https://github.com/khaledhosny/ots/pull/192

enforce VarStore RegionAxisCount == fvar.AxisCount

---

Doc/source/designspaceLib/readme.rst
Lib/fontTools/designspaceLib/__init__.py

- misc clarifications and edits from Erik
- proposed addition to allow rules be applied _after_ other features. Relates to #1747 and #1371

[WIP] [designspaceLib] designspace docs edits

---

Lib/fontTools/varLib/merger.py

[varLib] improve error when glyph orders don't match; fixes #1758

---

Lib/fontTools/misc/fixedTools.py
Lib/fontTools/pens/ttGlyphPen.py
Lib/fontTools/varLib/instancer.py
Tests/varLib/data/PartialInstancerTest2-VF.ttx
Tests/varLib/data/test_results/PartialInstancerTest2-VF-instance-100,100.ttx
Tests/varLib/data/test_results/PartialInstancerTest2-VF-instance-100,62.5.ttx
Tests/varLib/data/test_results/PartialInstancerTest2-VF-instance-400,100.ttx
Tests/varLib/data/test_results/PartialInstancerTest2-VF-instance-400,62.5.ttx
Tests/varLib/data/test_results/PartialInstancerTest2-VF-instance-900,100.ttx
Tests/varLib/data/test_results/PartialInstancerTest2-VF-instance-900,62.5.ttx
Tests/varLib/instancer_test.py

This PR adds support for Level-3 partial instacing (as defined in https://github.com/fonttools/fonttools/issues/1537#issuecomment-474983825): i.e. restricting axes min/max coordinates, dropping delta regions that fall completely outside the new limits.
The core method is `limitTupleVariationAxisRange`. This is called for each `{axisTag: (min, max)}` range and for each TupleVariation table, and either drops it entirely if outside the range, or scales the deltas and updates the tent's min/default/max.
The command line tool `fonttools varLib.instancer` now accepts (colon-separated) axis ranges, in addition to single points. E.g. to limit the wght axis between 400:700 and drop-and-pin the wdth axis to 75, you do:
```
$ fonttools varLib.instancer wght=400:700 wdth=75
```

[varLib.instancer] implement restricting axis ranges (aka L3) 

---

Lib/fontTools/ufoLib/__init__.py
Lib/fontTools/ufoLib/converters.py
Lib/fontTools/ufoLib/validators.py
Tests/ufoLib/UFOConversion_test.py

Pass glyphSet to `convertUFO1OrUFO2KerningToUFO3Kerning` so it can exclude glyph names from kerning group renaming. Fixes #1761.

ufoLib groupnames conversion 2 → 3

---

Lib/fontTools/pens/ttGlyphPen.py
Tests/pens/ttGlyphPen_test.py

otherwise the computed glyph xMin, yMin, xMax and yMax bounds can be computed incorrectly.
https://github.com/googlefonts/fontmake/issues/593
See the failing test.

ttGlyphPen must round float coordinates and offsets

---

Lib/fontTools/pens/roundingPen.py

I'd like to use this in ufo2ft to make sure we compile same OTF regardless of whether UFO contains float coordinates or not.

add RoundingPen, a filter pen to round coordinates and component offsets

---

Lib/fontTools/pens/filterPen.py
Lib/fontTools/pens/recordingPen.py
Lib/fontTools/pens/roundingPen.py
Lib/fontTools/pens/transformPen.py
Tests/pens/recordingPen_test.py

This PR adds a few point pens that are equivalent to the corresponding (segment) pens:
- FilterPointPen: passes through points/components unchanged to another 'slave' pen; mostly used as base class for more interesting filter pens, such as..
- TransformPointPen: a filter point pen that takes an Affine transforms and another point pen;
- RoundingPointPen: filter point pen that rounds point coordinates and components' offsets to integer;
- RecordingPointPen: records and replays point-pen commands (beginPath, addPoint, endPath)

[pointPens] Add {Filter,Recording,Transform,Rounding}PointPen

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

...so we don't trip on the overlap flag, that is set when instantiating variable fonts. Fixes #1771.

[ttLib.glyf] Make sure to use the flagOnCurve mask in glyph.draw()

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

The glyph.drawPoints() method had the same bug as glyph.draw(), as reported in #1771. This fixes that, too, and adds a test for it.

[ttLib.glyf] Fix flag bug in glyph.drawPoints()

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

In glyphs from the `glyf` table, glyph.draw() has always emitted a final `pen.lineTo()` back to the first point. This is redundant.
However, this may be a breaking change for client code, so I'm not sure it's wise to do this.

[ttLib.glyf] make glyph.draw() skip final lineTo()

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

Fixes #1777
The 'rvrn' feature is being incorrectly dropped because the feature indexes change if some other feature occuring before 'rvrn' is dropped. The feature indexes need to be remapped.
I add a failing test case to show the issue, then I'll follow up with the actual patch.

[subset] remap FeatureVariations SubstitutionRecord.FeatureIndex

---

Lib/fontTools/ufoLib/glifLib.py
Tests/ufoLib/glifLib_test.py

glifLib: ignore xml <!-- comments --> when parsing GLIF files with lxml

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

We have lots of source files which contain substitutions that do nothing or are duplicated because classes are reused for different features. Those fail compilation with feaLib currently.
I think if an identical substitution is added to a feature, it could be ignored instead of raising an error. The problem is only when a duplicate source glyph would introduce an ambiguity, i.e. the code would demand to replace one glyph with two different target glyphs.
Example:
```
@fig = [one two three Euro];
@figOldstyle = [one.osf two.osf Euro];
@figSC = [one.sc two.sc Euro.sc];
feature onum {
sub @fig by @figOldstyle;
} onum;
feature c2sc {
sub @fig by @figSC;
sub @figOldstyle by @figSC; # <-- adds sub Euro by Euro.sc; again
} cs2c;
```
Which is equal to:
```
feature onum {
sub [one two three Euro] …
```

[feaLib] Warning instead of error for duplicate identical substitutions

---

Lib/fontTools/ttLib/tables/_c_m_a_p.py

On a clean clone (make sure there are no pycs present yet),
```
python -c 'import fontTools.ttLib.tables._c_m_a_p'
```
results in
```
.../fontTools/ttLib/tables/_c_m_a_p.py:21: SyntaxWarning: "is" with a literal. Did you mean "=="?
if gid is 0:
```
Fix that.

Get rid of SyntaxWarning with py3.8.

---

Lib/fontTools/ttLib/tables/otTables.py
Tests/ttLib/tables/otTables_test.py

@marekj and @punchcutter discovered a major bug in the `splitMarkBasePos` function from `fontTools.ttLib.tables.otTables` (which is used when offsets within a MarkToBase subtable overflow uint16 limits).
https://github.com/googlefonts/noto-source/issues/145
The function splits the big subtable into two halves, each containing the same base coverage but only half of the marks.
The problem was that the MarkRecord.Class values of the second subtable were not being updated to match the new (halved) class count. And because the mark class values were out of sync, the base records would end up referencing either wrong or non-existent mark classes...
I added a (failing) test and will push a fix in a following commit.
Overflows in MarkBasePos subtables are rare in static fonts (although they may …

splitMarkBasePos should update MarkRecord.Class values after splitting

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

If the single substitution involved a glyph class, we were incorrectly using only the first glyph in the class.
Broken since ec6ff821f0e72022d7aec8794b6bb589d8f81808, apparently no one else uses this feature!

[feaLib] fix mixed single/multiple substitutions

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/data/lookupflag.fea
Tests/feaLib/data/lookupflag.ttx

In makeotf, lookups defined inside feature blocks inherit the current `lookupflag` of the feature, so don’t reset the `lookupflag` for such lookups.

[feaLib] Don’t reset lookupflag in nested lookups

---

Lib/fontTools/ttLib/tables/E_B_L_C_.py
Tests/ttLib/tables/C_B_L_C_test.py
Tests/ttLib/tables/data/NotoColorEmoji.subset.index_format_3.ttx

Fixes #1817
Ideally we should add a test for this. Currently, the only test that has to do with CBLC/EBLC is for the subset module. The Tests/subset/data/google_color.ttx file however only has format 1 index subtable.
I need to make a test font or modify the existing one.
/cc @ckitagawa-work

EBLC: fix padding length calculation for Format 3 IndexSubTable

---

Tests/feaLib/lexer_test.py

On Windows, tests may be run in the user's temp directory, so the previous code may compare `C:\Users\nikolaus.waxweiler\` against `C:\Users\NIKOLA~1.WAX\`.

[feaLib lexer tests] Compare realpath against realpath

---

Lib/fontTools/feaLib/parser.py
NEWS.rst
Tests/feaLib/builder_test.py
Tests/feaLib/parser_test.py

This checks that glyph names that appear in a feature file are actually in the glyph set provided in `glyphNames`, unless it is empty. 
Closes https://github.com/fonttools/fonttools/issues/1723.

[feaLib] Check that glyph names referenced in the feature file are part of the glyph set

---

Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/cff.py
Lib/fontTools/varLib/errors.py
Lib/fontTools/varLib/featureVars.py
Lib/fontTools/varLib/merger.py
Lib/fontTools/varLib/models.py
NEWS.rst
Tests/varLib/models_test.py
Tests/varLib/varLib_test.py

This is a support PR for https://github.com/googlefonts/fontmake/pull/634 and aims to make the varLib variable font building API raise `VarLibError` and derivatives instead of generic exceptions and assertion errors.
I try to differentiate between input errors and programming errors. Input errors should be catchable by fontmake and ideally tell the user what's wrong. Programming errors are unexpected (haha) and should continue to produce stack traces because there is nothing else useful you can do with them.

[varLib] Use proper exceptions for signalling input source errors

---

Lib/fontTools/pens/ttGlyphPen.py
Tests/pens/ttGlyphPen_test.py

Fixes https://github.com/googlefonts/fontmake/issues/558
When creating a composite glyph with a scaled component using the TTGlyphPen, the bounding
box coordinates may change depending on whether one computes the bbox *before* compiling, or
*after* decompiling. Before compiling, component.transform holds double precision floats,
but after compiling and decompiling, these are necessarily clamped to F2Dot14 fixed precision.
The TTGlyphPen needs to quantize transform floats to F2Dot14 so that the values don't
change after compilation.
Without this change, it may happen that round-tripping fonts through ttx (which by default
recalcBBoxes) will produce different bounding boxes for composite glyphs that have
scaled or transformed components.

[ttGlyphPen] quantize component.transform to F2Dot14 to normalize bbox

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

Fixes #1556 
As @blueshade7 noted, there is a bug computing bounding boxes for composite glyphs with components that uses firstPt/secondPt reference anchor points (instead of the more common XY offsets), and the components also have a transform.
This is because we are computing the translation offset between firstPt and secondPt _before_
applying the 2x2 scale/rotation/shear transform. By the time we also apply the translation, the
offset is now incorrect.
We need to compute the translation offset _after_ we have applied the 2x2 transform.

[glyf] fix getCoordinates for composite glyphs that use anchor points

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/fontBuilder_test.py

Make sure the CFF table generated by fontBuilder can be used by varLib without having to compile and decompile the table first. This was breaking in converting the CFF table to CFF2 due to some unset attributes.

fontBuilder: Allow varLib to use fresh CFF table

---

.travis.yml
Lib/fontTools/misc/timeTools.py
Tests/misc/timeTools_test.py

This commit uses non-localized date parsing in [`fontTools.misc.timeTools.timestampFromString`](https://github.com/fonttools/fonttools/blob/51bff6cf6a08976c831aa5c9e8c901fac7e61dea/Lib/fontTools/misc/timeTools.py#L46). This is consistent with the opposite function `fontTools.misc.timeTools.timestampToString`, which also uses a non-localized date format.
This function is used when importing a font from XML using [`fontTools.ttLib.TTFont.importXML`](https://github.com/fonttools/fonttools/blob/51bff6cf6a08976c831aa5c9e8c901fac7e61dea/Lib/fontTools/ttLib/ttFont.py#L318) via [`fontTools.ttLib.tables.table__h_e_a_d.fromXML`](https://github.com/fonttools/fonttools/blob/51bff6cf6a08976c831aa5c9e8c901fac7e61dea/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L107)
Depending on the LC_TIME locale setting, …

Use non-localized date parsing to fix #1838

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/SingleMaster.ttx

turns out gvar is required by OT spec for VF with TrueType outlines:
see https://github.com/fonttools/fonttools/issues/1855#issuecomment-598769956
Fixes https://github.com/fonttools/fonttools/issues/1855

[varLib] revert to always build gvar, even if empty

---

Lib/fontTools/designspaceLib/__init__.py
Tests/designspaceLib/designspace_test.py

... like data classes.
For now, I resisted the temptation to rewrite the whole thing use attrs or dataclasses, as I am time-constrained. I just wanted to be able to initialize axis/source/instance descriptors using their default constructor, which is more idiomatic than creating an incomplete object and then mutating its attributes afterwards.
I kept the same defaults as before (basically all None or False). The defaults are mostly meaningless, which is another pain point when using dsLib -- you don't know what piece of data is actually _required_ by what consumer.
We shall figure that out one day.

designspaceLib: allow to construct descriptors from keyword args

---

Lib/fontTools/ttLib/tables/C_P_A_L_.py

there wasn't option to initialize Color using RGBA, but instead BGRA or HEX. User inputs are mostly RGBA, before I had to use uncomfortably and unreadably `Color(*color[:3][::-1], color[3])` or switch it aside.

CPAL.Color.fromRGBA

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/ChainPosSubtable.fea
Tests/feaLib/data/GSUB_6.fea
Tests/feaLib/data/GSUB_8.fea
Tests/feaLib/data/bug514.fea
Tests/feaLib/data/cid_range.fea
Tests/feaLib/data/cid_range.ttx
Tests/feaLib/data/language_required.fea
Tests/feaLib/data/spec4h1.fea
Tests/feaLib/data/spec5f_ii_2.fea
Tests/feaLib/data/spec5f_ii_3.fea
Tests/feaLib/data/spec5f_ii_4.fea
Tests/feaLib/data/spec5fi3.fea
Tests/feaLib/data/spec8a.fea

For any string that feaLib can parse, feaLib should be able to parse the string converted to AST converted back to a string. Consider the following test.
```python
from fontTools.feaLib.parser import Parser
from io import StringIO
def round_trip(fea):
ast = Parser(StringIO(fea)).parse()
fea = ast.asFea()
return Parser(StringIO(fea)).parse().asFea()
round_trip("@A = [a -c];")
round_trip("@B = [\\800-\\1001];")
```
Before my changes, it fails:
```pycon
>>> round_trip("@A = [a -c];")
File "<stdin>", line 1, in <module>
File "<stdin>", line 4, in round_trip
File "parser.py", line 69, in parse
statements.append(self.parse_glyphclass_definition_())
File "parser.py", line 229, in parse_glyphclass_definition_
glyphs = self.parse_glyphclass_(accept_glyphname=False)
File "parser.py", line 303, in …
```

[feaLib] Fix round-tripping between feature file syntax and AST

---

Snippets/otf2ttf.py

Reported here https://github.com/googlefonts/cu2qu/issues/190, but as Behdad pointed out it's because the LSB isn't being adjusted to account for the different outline structure.

In otf2ttf conversion update LSB in hmtx to match xMin

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/GSUB_error.fea
Tests/feaLib/parser_test.py

Raise an exception when a substitute statement doesn't match any of the GSUB lookup rules. Add tests that trigger and test said exception.

[feaLib] Raise exception when GSUB statement doesn't match a rule.

---

README.rst

Change lxml reference link from `https://http://lxml.de` to `https://lxml.de`.

Fix broken lxml reference link

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

Fixes https://github.com/fonttools/fonttools/issues/1768
cc @lianghai

feaLib: without glyphNames, warn but don't parse hyphens as ranges

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/aalt_chain_contextual_subst.fea
Tests/feaLib/data/aalt_chain_contextual_subst.ttx

this was originally reported in https://github.com/googlefonts/fontmake/issues/648 by @m4rc1e and @vv-monsalve
If you have FEA like the one below, with `aalt` feature referencing another feature that in turn contains some chain contextual substitution lookups, one may get an `AttributeError: 'NoneType' object has no attribute 'getAlternateGlyphs'`: 
```
lookup CNTXT_LIGS {
sub f i by f_i;
sub c t by c_t;
} CNTXT_LIGS;
lookup CNTXT_SUB {
sub n by n.end;
sub s by s.end;
} CNTXT_SUB;
feature calt {
sub [a e i o u] f' lookup CNTXT_LIGS i' n' lookup CNTXT_SUB;
sub [a e i o u] c' lookup CNTXT_LIGS t' s' lookup CNTXT_SUB;
} calt;
feature aalt {
feature calt;
} aalt;
```
I copied the snippet above from the [FEA spec](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5fi …

[feaLib] Fix AttributeError: 'NoneType' object has no attribute 'getAlternateGlyphs'

---

Doc/source/pens/cu2quPen.rst
Doc/source/pens/index.rst
Doc/source/pens/pointPen.rst
Doc/source/pens/roundingPen.rst

This fell off the truck :)
Ignore reportLabPen for now, as reportlab is a missing dependency usually.

Add missing pen documentation

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/lookupflag.fea
Tests/feaLib/data/lookupflag.ttx

Setting script that is the same as current language system should make no effect. This is not documented in the spec, but it is what makeotf does. This as the effect of preserving `lookupflag` when set before such a `script` statement.
Fixes https://github.com/fonttools/fonttools/issues/1824

[feaLib] Ignore superfluous script statements

---

.readthedocs.yml

The [PDF builds on RTD fail with the current docstrings/configuration](https://readthedocs.org/projects/fonttools/builds/10881463/).  This PR transitions to distribution of [static HTML site zip archives](https://fonttools.readthedocs.io/_/downloads/en/latest/htmlzip/) and [ePub](https://fonttools.readthedocs.io/_/downloads/en/latest/epub/) builds for those who want to download pre-built content.  We can troubleshoot this if PDF documentation downloads are useful to anyone.

Eliminate PDF documentation builds on Read The Docs

---

Doc/source/index.rst

Sphinx doesn't like the list item line break formatting that is used in the README.rst file (#1888).  This is a Sphinx doc formatting PR for list items on the home page of the RTD documentation.

[Sphinx docs] indent line breaks in lists

---

Lib/fontTools/feaLib/__main__.py

Makes the command line tool a little nicer to use. Adds `--traceback` option to show them when needed.

[feaLib] Hide traceback by default on command line

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

Raise if `lookup_index` is None, which would happen only of the lookup referenced belongs to the wrong table. The error message needs to be less cryptic, though.
Fixes https://github.com/fonttools/fonttools/issues/1896

[feaLib] Check lookup index in chaining lookups

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/AlternateChained.fea
Tests/feaLib/data/AlternateChained.ttx

Support was added in db49f20d6b2629e1ba25c4afd3fb60817387f3d6, but there was only a parser test and no builder test, fix the build and add a builder test based on the existing parser one.
Fixes https://github.com/fonttools/fonttools/issues/1901

[feaLib] Fix building chained alt substitutions

---

Lib/fontTools/misc/transform.py

This removes some boilerplate code, and also helps when using static type checkers like mypy.
The typing.NamedTuple class was added with python 3.6 which is our min required python, so we are good.
I kept the docstrings and doctests for the methods that are no longer needed (`__len__`, `__getitem__`, `__eq__`, `__hash__`) as they can be helpful.

transform: make Transform class a NamedTuple

---

Lib/fontTools/varLib/instancer.py

Fixes a `varLib.instancer` example

varLib.instancer documentation fix

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

It is usually a good idea to reuse name table records for the non-core nameIDs, such as those for `fvar` and `STAT` names. Finding an existing name record matching a single string is not very hard, but it becomes a mess real quick for multilingual names.
The added `nameTable.findMultilingualName(names)` method makes this easier:
```python
names = dict(en="Width", nl="Breedte")
nameID = nameTable.findMultilingualName(names)
if nameID is None:
nameID = nameTable.addMultilingualName(names)
```
I considered making this part of `addMultilingualName()` itself, but thought that perhaps it's better to keep this separate.

[ttLib.name] Add nameTable.findMultilingualName() method

---

Doc/source/conf.py
Doc/source/developer.rst
Doc/source/index.rst
Doc/source/optional.rst
Doc/source/ttx.rst
MetaTools/buildTableList.py
README.rst

* Split off developer-centric info to new page, making front page of docs more user-focused.
* List all utilities and sub-modules with brief descriptions.
* Make README more concise and focused.
* Add links to online documentation.

Tidy up top-level documentation and README

---

Lib/fontTools/cu2qu/errors.py
Lib/fontTools/varLib/cff.py

Avoids cases where super() argument is not enclosing class: https://help.semmle.com/wiki/display/PYTHON/First+argument+to+super%28%29+is+not+enclosing+class

Use Python3 inheritance style for super.___init__

---

Lib/fontTools/ttLib/tables/_m_e_t_a.py
Tests/ttLib/tables/_m_e_t_a_test.py

I work on a project where an ascii string is stored in a private `meta` key. For us it would be practical if we could see the ascii contents as a comment string in the TTX output.
This PR checks whether the data could be interpreted as ascii (and does not contain special characters < `0x20`), and emits a comment with the contents decoded from ascii.
Maybe this is a bit too specific, so I won't be heartbroken if this gets rejected.

[ttLib.table._m_e_t_a] if data happens to be ascii, emit comment in TTX

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/MultipleLookupsPerGlyph.fea
Tests/feaLib/data/MultipleLookupsPerGlyph.ttx
Tests/feaLib/data/MultipleLookupsPerGlyph2.fea
Tests/feaLib/data/MultipleLookupsPerGlyph2.ttx
Tests/feaLib/parser_test.py

This is an implementation of the suggestion at adobe-type-tools/afdko#1119 to support the syntax:
```
sub a' lookup lu_1 lookup lu_2;
```
I know it's generally not a great idea to add your own non-standard extensions to a commonly used public spec, but there appears to be support for this concept on the Adobe side. My plan is to get this reference implementation working here, see what I can do with the makeotf code and get the spec changed; somebody has to go first.

[feaLib] Support multiple lookups per glyph position

---

Doc/source/colorLib/builder.rst
Doc/source/colorLib/errors.rst
Doc/source/colorLib/index.rst
Lib/fontTools/colorLib/builder.py

Does not add any new documentation (there is already some documentation for user-facing functions). It just makes colorLib.builder the top-level documentation entry, because that’s the part the user needs to care about.

[docs] Reorganise colorLib docs

---

Lib/fontTools/cffLib/width.py
Lib/fontTools/mtiLib/__init__.py
Lib/fontTools/ttLib/woff2.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/interpolatable.py
Lib/fontTools/varLib/interpolate_layout.py
Lib/fontTools/varLib/models.py
Lib/fontTools/varLib/varStore.py

Another slightly long PR, sorry; but each commit is self-contained, and some of them are one-liners.
We have a number of command line tools which are somewhat opaque. (varLib.models in particular was very confusing.) This ensures that they all use argparse to have a consistent interface, and all have `--help` documentation which at least details their parameters, and hopefully therefore gives more of a clue about what they do. Those which use logging have had a command-line logging parameter added.

Ensure all fonttools CLI tools have help documentation

---

Doc/source/feaLib/ast.rst
Doc/source/feaLib/builder.rst
Doc/source/feaLib/error.rst
Doc/source/feaLib/index.rst
Doc/source/feaLib/lexer.rst
Doc/source/feaLib/parser.rst
Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py

Quite a big change, but it’s a big library:
* Rearrange docs by user intention, highlighting the things you can do with each component.
* Remove reference to lexer and error modules from documentation tree, since they’re not user-facing.
* I’ve added docstrings to the parser even though we only provide access to the user-facing part of the API in the main documentation, just to clarify what some of the more obscure methods do and provide links to the spec.
* AST *is* user-facing if you’re building your own feature files in code, so all classes are documented with the user in mind.

[docs] Document feaLib

---

LICENSE.external
Lib/fontTools/subset/__init__.py
Tests/subset/data/TestContextSubstFormat3.ttx
Tests/subset/subset_test.py

Fixes https://github.com/fonttools/fonttools/issues/1879
In Format-3 ChainContext subtables, the array of input coverages is under `InputCoverage` attribute, whereas in non-Chain Context Format 3 subtables it is called simply `Coverage`.

subset: fix AttributeError while subsetting Context{Subst,Pos} Format 3

---

Tests/designspaceLib/designspace_test.py

Use API correctly: condition sets must be wrapped in an extra layer of `Iterable`.

Fix test_addRuleDescriptor

---

.travis/run.sh
Doc/source/developer.rst
tox.ini

https://tox.readthedocs.io/en/latest/config.html#conf-skip_missing_interpreters
Runing `tox` with no options runs the tests agaist all the python
environments that are listed inside the `tox.ini`'s `envlist` (currently 3.6, 3.7 and 3.8).
Before this change, if any of these requested versions was not available, tox would exit with an error. Now it will simply continue (with a warning).
This can be useful when on a developer box, one might only have a subset of all our supported interpreters installed. We don’t want to mark the build as failed because of it.
Note that on the CI I am passing the opposite command line switch that overrides this setting, because there I want to make sure none of the specified interpreters is skipped.
This simplifies running the test suite. It's now simply `pip …

tox: add skip_missing_interpreters=true

---

Doc/source/cu2qu/cli.rst
Doc/source/cu2qu/cu2qu.rst
Doc/source/cu2qu/errors.rst
Doc/source/cu2qu/index.rst
Doc/source/cu2qu/ufo.rst
Lib/fontTools/cu2qu/cu2qu.py

* Reorganise the documentation so that everything is in one place and users are more clearly pointed to the modules which are likely to be useful for their purposes. (I still think it’s worth having at least a brief reference to ``cu2qu.cli`` in there, as a way of reminding users that there is a command-line implementation.)
* Explain a little bit about the methodology.
* Add docstrings for all the methods I understand.

[docs] Document cu2qu library

---

Lib/fontTools/varLib/featureVars.py
Tests/varLib/data/FeatureVarsWholeRange.designspace
Tests/varLib/data/FeatureVarsWholeRangeEmpty.designspace
Tests/varLib/data/test_results/FeatureVarsWholeRange.ttx
Tests/varLib/varLib_test.py

Original use case: A VF containing weight and italic axes with a subordinate VF containing only a weight axis of the italic forms. Some Cyrillic glyphs need to be swapped out for special italic forms for some languages like Macedonian. The solution we settled on requires that the special forms are substituted across the entire weight axis range, which varLib filtered out before.

[varLib] Allow feature variations to be active across the entire space

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py
Tests/varLib/data/test_results/BuildTestCFF2.ttx

When reading from binary, `name.string` may be an encoded bytes sequence. Previously, `findMultilingualName()` would fail to match these with the requested input.
Calling `toUnicode()` before we compare to the requested string fixes this.

[ttLib.name] Fix findMultilingualName()

---

Lib/fontTools/feaLib/ast.py
README.rst

Version 4.10.0 broke `feaLib.ast.ChainContextPosStatement` and `ChainContextSubstStatement`. Previously each of these classes had a `lookups` field that was a list of lookups. #1905 changed it to a list of lists of lookups. For compatibility, it should treat a lookup within the outer list as if it were a list of a single entry.
In 4.9.0, and once again with my fix, this script:
```python3
#!/usr/bin/env python3
from fontTools.feaLib.ast import (
ChainContextSubstStatement,
GlyphName,
LookupBlock,
)
print(ChainContextSubstStatement(
[],
[GlyphName('x')],
[],
[LookupBlock('dummy')],
))
```
printed this:
```
sub x' lookup dummy;
```
In 4.10.0, it prints this:
```
Traceback (most recent call last):
File "./bug.py", line 13, in <module>
[LookupBlock('dummy')],
File …
```

[feaLib.ast] Restore compatibility with 4.9.0

---

Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/include/test.fea
Tests/feaLib/data/include/test.ufo/features.fea
Tests/feaLib/data/test.fea
Tests/feaLib/parser_test.py

ufo2ft reads a UFO's feature file into a StringIO and sets the `name` attribute to the UFO, not the feature file within: https://github.com/googlefonts/ufo2ft/blob/53dd7c6/Lib/ufo2ft/featureCompiler.py#L34-L40. `IncludingLexer` then uses that attribute to determine where to look for includes.
I want to change ufo2ft to make it point to the actual feature file and change `IncludingLexer` to take an explicit directory to use for includes, so that users get a better error message if something goes wrong. For backwards compatibility, `IncludingLexer` continue handling the `name` attribute as above.

[feaLib] Explicitly look outside UFO for includes

---

Lib/fontTools/voltLib/ast.py
Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

Adds `__str__()` method to ast classes that writes back VOLT data. Tries to replicate VOLT syntax idiosyncrasies as much as possible for better round-trip conversion.

[voltLib] Support writing back ast as VOLT data

---

Lib/fontTools/ttLib/tables/O_S_2f_2.py

`_getUnicodeRangeSets` used to calculate sets containing lots of numbers, only to get intersections between a set and ranges. Creating and manipulating a lot of big sets is both slow and memory consuming.
The function has been replaced by `_getUnicodeRanges`, returning ranges instead of sets. Ranges are both really lightweight and really fast.
Tests on intersectUnicodeRanges are now 3 times faster and save about 130 MB (!) of RAM.
Before: 0.28 seconds, 148 MB RAM
```
time python fonttools/Lib/fontTools/ttLib/tables/O_S_2f_2.py
0.23user 0.05system 0:00.28elapsed 100%CPU (0avgtext+0avgdata 147760maxresident)k
```
After: 0.08 seconds (**-70%**), 14 MB RAM (**-90%**)
```
time python fonttools/Lib/fontTools/ttLib/tables/O_S_2f_2.py
0.08user 0.00system 0:00.08elapsed 100%CPU (0avgtext+0avgdata …
```

Don’t calculate whole sets of unicode codepoints

---

Lib/fontTools/voltLib/parser.py
Tests/voltLib/parser_test.py

Corresponds to the “Do not overwrite camp table” option in VOLT.

[voltLib] Accept DO_NOT_TOUCH_CMAP keyword

---

Lib/fontTools/otlLib/builder.py
Lib/fontTools/ttLib/tables/_n_a_m_e.py
Lib/fontTools/varLib/__init__.py
Tests/otlLib/builder_test.py
Tests/ttLib/tables/_n_a_m_e_test.py

Fix for #1985: ensure that the AxisNameID in the STAT table is not less than 256. This needed an additional argument to the addMultiLingualName() name table method.

Fix for #1985: ensure that the AxisNameID in the STAT table is > 255

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

Don't attempt to recover malformed data from str, only from bytes. Fixes #1997.

[ttLib.tables._n_a_m_e] Fix #1997: Only attempt to recovered malformed data from bytes

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py

This replaces #1991. Mostly this is about refactoring common code to a superclass, but lays a foundation for the optimizer which will come later.

[otlLib] Refactor chained contextual builders

---

Lib/fontTools/ufoLib/glifLib.py

not a dict where the key is the case sensitive file name
fixing #2001

make sure a list of possible case-insensitive file names is send

---

Lib/fontTools/feaLib/ast.py

This fixes the docstring; yes, it does it using a Google-style docstring, and yes, this is currently inconsistent, but half the docstrings I've written so far are Python and the other half are Google-style so we're inconsistent already, and better docs doesn't hurt. Going through all the docstrings and converting them all to Google-style is on my todo list. Consider this just getting one in early. :-)

Fix documentation for MultipleSubstStatement (fixes #2012)

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Tests/otlLib/builder_test.py
Tests/otlLib/mock_builder_test.py

As mentioned in #2020:
> Besides, these rules ideally could be turned into a named tuple and their items accessed with attribute lookup (e.g. rule.prefix) instead of unpacking the tuple to get to its items by position.
(Note: This sits on top of #2025. Merge that one first, and this will magically become readable.)

Use namedtuple to represent contextual rules

---

Snippets/decompose-ttf.py

Snippet based on https://github.com/fonttools/fonttools/issues/2029#issuecomment-662816227

[Snippets] add snippet that shows how to decompose glyphs in a TTF

---

Lib/fontTools/subset/__init__.py

This import is causing an unsightly DeprecationWarning.
I checked manually: the only names being used from py23 are
open, range and zip, which are defined to be the same as the
corresponding Python 3 builtins, so this should cause no
visible change except for suppressing the warning.

Remove import of py23 fron subset/__init__.py

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

The logic in `glyph.getCompositeMaxpValues()` was flawed: it would return a value that is too high when the composite contains more than one nested component. Using a separate variable for the initial value fixes this. This fixes #2044.

[ttLib] Fix for #2044: fix maxp.maxComponentDepth calculation

---

Doc/source/designspaceLib/readme.rst

Better document rule processing order

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/lookupflag.fea
Tests/feaLib/data/lookupflag.ttx
Tests/feaLib/parser_test.py

Almost everywhere else when a glyph class name is accepted, anonymous glyph classes are also accepted. This is rather inconsistent and inconvenient.

[feaLib] Allow anonymous glyphclass in LookupFlags

---

Lib/fontTools/ttLib/ttFont.py
Tests/ttLib/ttFont_test.py

Rationale:
- Currently, all sfnt table packer/unpacker classes must live in `fontTools.ttLib.tables`
- Sometimes a project can benefit from private table data, and would like to use the standard TTFont table API, without needing an explicit step to pack/unpack
- Proposals for new OpenType tables would benefit from this, as experimentation can then easily be done without forking fonttools.
Implementation:
```python
def registerCustomTableClass(tag, moduleName, className=None):
"""Register a custom packer/unpacker class for a table.
The 'moduleName' must be an importable module. If no 'className'
is given, it is derived from the tag, for example it will be
table_C_U_S_T_ for a 'CUST' tag.
"""
...
```
I considered taking the simpler route by having the register function take a class object, …

Add registry for custom table packer/unpacker classes

---

Lib/fontTools/varLib/interpolatable.py

Today I was surprised to run `fontTools varLib.interpolatable` on a font, get a pass, and then find that `fontTools varLib` could not in fact interpolate the font. Here are some more checks in `interpolatable`.
* Checks node count of each path
* Checks operation type of each path node

[varLib] Test for interpolatability of paths

---

.gitignore
Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/sfnt.py
Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ttLib/woff2.py

Closes #2057.
Also disabled by default for the WOFF2 reader, largely because that's how the API is documented. I have no idea if this makes sense for WOFF2 the same way it does for SFNT.

Disable checksum checking by default

---

.travis.yml
Lib/fontTools/misc/plistlib.py
Lib/fontTools/misc/plistlib/__init__.py
MANIFEST.in
dev-requirements.txt
mypy.ini
setup.py
tox.ini

Wherein I spend my life adding typing information to the plistlib module and use Pylance in strict checking mode. Maybe I'll get somewhere.
First boss: https://github.com/microsoft/pyright/issues/988
I wish I could just kill `Data`.
The module is half red because the `etree` module could do with some typing information, too.
@chrissimpkins hi there

Add typing info to plistlib

---

.travis/install.sh
Lib/fontTools/ttLib/removeOverlaps.py
Lib/fontTools/varLib/instancer.py
README.rst
Snippets/remove-overlaps.py
Tests/varLib/data/PartialInstancerTest3-VF.ttx
Tests/varLib/data/test_results/PartialInstancerTest3-VF-instance-400-no-overlap-flags.ttx
Tests/varLib/data/test_results/PartialInstancerTest3-VF-instance-400-no-overlaps.ttx
Tests/varLib/data/test_results/PartialInstancerTest3-VF-instance-700-no-overlaps.ttx
Tests/varLib/instancer_test.py
requirements.txt
setup.py
tox.ini

this may help for VF generated instances containing overlaps on old macOS (10.11 El Capitan and lower) that seem to ignore the OVERLAP_SIMPLE/OVERLAP_COMPOUND flags,  see https://github.com/google/fonts/issues/2602
Note I haven't tested this, feel free to use and improve on it.
EDIT (30/09/2020):
The PR has changed from a snippet to a full-blown new module called `fontTools.ttLib.removeOverlaps`. This exports a `removeOverlaps` function that takes a TTFont and an optional list of glyphNames to modify (by default it does them all).
Also, the `fonttools varLib.instancer` tool has a new `--remove-overlaps` command-line option that uses the new module to remove overlaps of full VF instances.
Finally, in the `instantiateVariableFont` function in `varLib.instancer` module, the `overlap` option …

add module to remove overlaps from TTF with skia-pathops

---

Lib/fontTools/ufoLib/glifLib.py
Tests/ufoLib/glifLib_test.py

The current code hard-requires `x` and `y` either way but is being coy about it. If you're missing `y` and have validation turned off, you'll just get a `TypeError` about how `None` cannot be converted to a number instead of a proper descriptive `GlifLibError`.
As a tiny side-benefit, my profiler says that this makes `_validateAndMassagePointStructures` go a tiny fraction of a second faster :)

[glifLib] Hard-require x and y coordinates

---

Lib/fontTools/varLib/instancer.py
Lib/fontTools/varLib/mutator.py
Tests/varLib/instancer_test.py

it is valid to have a font with GSUB v1.1 where FeatureVariations is unused; on loading the GSUB table, the attribute is present and is set to `None`. 
The instancer was simply checking if `hasattr(table, "FeatureVariations")` and assuming that if present, it ought to be not None. But that's not always True.

[instancer] FeatureVariations table is optional in GSUB 1.1 and can be None

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/FeatureVarsCustomTag.designspace
Tests/varLib/data/test_results/FeatureVarsCustomTag.ttx
Tests/varLib/varLib_test.py

Add designspace lib key to specify a custom feature tag for feature variations, as discussed in #2079 
This looks for the custom tag when "processing = last". Alternatively it could override the value for "processing" altogether.
I used `com.github.fonttools.varLib.featureVarsFeatureTag` for the lib key, as it's really `varLib` that's defining it.

[varLib] Add designspace lib key for custom feavar feature tag

---

Snippets/scale-font.py

Check the presence of positioning attributes in subTable.Value

Bug fix of the Lookup Type 1 scaling in scale-font.py

---

Lib/fontTools/varLib/__init__.py

Interpret empty non-default glyphs as 'missing', if the default glyph is not empty. Part of discussion over at googlefonts/ufo2ft/issues/408
If this idea is considered useful and not harmful, it probably needs a CFF2 counterpart.

[varLib] Interpret empty non-default glyphs as 'missing'

---

Lib/fontTools/svgLib/path/parser.py
Tests/svgLib/path/parser_test.py

Some SVG authoring tool write arc commands without any space or comma around the boolean 'large-arc' and 'sweep' flags, leading our svg path parser to choke.
E.g. `A1.2 1.2 0 0122 6.2` is currently tokenized as `["A", "1.2", "1.2", "0", "0122", "6.2"]`, whereas it should instead be tokenized as `["A", "1.2", "1.2", "0", "0", "1", "22", "6.2"]`
This PR makes the path parser smarter by special-casing arc command so that we only consume one character ('0' or '1') for these special boolean flags.

svgLib: handle arc commands with bool flags not separated by space/comma

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/ChainPosSubtable.ttx
Tests/feaLib/data/GPOS_8.ttx
Tests/feaLib/data/GSUB_5_formats.fea
Tests/feaLib/data/GSUB_5_formats.ttx
Tests/feaLib/data/GSUB_6.ttx
Tests/feaLib/data/GSUB_6_formats.fea
Tests/feaLib/data/GSUB_6_formats.ttx
Tests/feaLib/data/ZeroValue_ChainSinglePos_horizontal.ttx
Tests/feaLib/data/ZeroValue_ChainSinglePos_vertical.ttx
Tests/feaLib/data/bug512.ttx
Tests/feaLib/data/spec5f_ii_3.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_7_diff.ttx
Tests/varLib/data/test_results/InterpolateLayoutGPOS_7_same.ttx

This builds on existing work in the otlLib builder module. Currently we build all contextual/chained contextual lookups as format 3 subtables. However, there are often more efficient representations. Format 1 (simple glyph contexts) and format 2 (class based contexts) may save disk space.
In this PR, we build all the possible representations and compare their byte size, adding the most compact representation to the font. I've tried to break it down into manageable pieces.
Fun fact: I'm working on a font with lots of contextual rules; this patch took the final font size from 236Kb to 144Kb.

[otlLib] Build format 1 and format 2 contextual lookups

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/lookupDebugInfo.py

This builds on #2052 (Feature file debugging). Currently we can add the `Debg` table to the font but you have to ask for it in Python, in whatever calls `addOpenTypeFeatures`.
With this patch, you can export `FONTTOOLS_LOOKUP_DEBUGGING=1` to get feature file debugging. This makes it really easy to enable source-level debugging without having to modify your existing (fontmake or whatever) toolchain.

Turn on feaLib debugging from the environment

---

Lib/fontTools/pens/quartzPen.py
README.rst
Tests/pens/cocoaPen_test.py
Tests/pens/quartzPen_test.py

FontTools supports drawing on macOS via the [`CocoaPen`](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/pens/cocoaPen.py), which transforms a path into an `NSBezierPath`. However, for lower-level drawing on macOS, animation with CoreAnimation, and other use-cases, it’s useful to have outlines represented as `CGPath` instead of `NSBezierPath`. RoboFab used to have a [`QuartzPen`](https://github.com/robotools/robofab/blob/master/Lib/robofab/pens/quartzPen.py) but it’s no longer functional under Python 3. This PR adds a `QuartzPen` back to FontTools, together with some unit tests that only run when PyObjC is installed.

Added QuartzPen

---

.github/workflows/test.yml
requirements.txt

Trying my luck with GHA conditional syntax (is there a way to see what a workflow change would do without pushing to github?) in order to fix #2108. The updated workflow should `pip install pyobjc` only on macOS.

Optionally install PyObjC if on macOS test env

---

Lib/fontTools/ufoLib/__init__.py
Lib/fontTools/ufoLib/glifLib.py
Tests/ufoLib/UFO3_test.py
Tests/ufoLib/glifLib_test.py

For use when reading existing UFOs, to comply with the specification stating that a contents.plist file must exist in a glyph set.
Avoid unconditionally checking for the file because `UFO(Reader|Writer).getGlyphSet` and therefore indirectly `GlyphSet` are used to create new fresh glyph sets.
Closes https://github.com/fonttools/fonttools/issues/2111.

Add expectContentsFile parameter to GlyphSet

---

Lib/fontTools/pens/momentsPen.py
Lib/fontTools/varLib/interpolatable.py

* Allow UFO files to be checked
* Report open paths (instead of raising an exception)
* Report non-existant glyphs (instead of raising an exception)
* Reformat code with black
* Tidy up output and add an option (--json) to produce a machine-readable list of incompatibilities
Example text output:
```
Glyph D was not compatible:
Node 1 incompatible in path 0: curveTo in Coolangatta-Regular, lineTo in Coolangatta-Bold
Node count differs in path 1: 7 in Coolangatta-Regular, 6 in Coolangatta-Bold
Glyph N was not compatible:
Node 11 incompatible in path 0: curveTo in Coolangatta-Regular, lineTo in Coolangatta-Bold
Glyph v was not compatible:
Node 7 incompatible in path 0: lineTo in Coolangatta-Regular, curveTo in Coolangatta-Bold
```
Example JSON output:
```JSON
{
"D": [
{
"type": …
```

Various fixes to varLib.interpolatable

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/expect_layout_scripts.ttx
Tests/subset/data/layout_scripts.ttx
Tests/subset/subset_test.py

Allow specifying which LangSys tags to accept for each script, using `script.lang` form. For example:
--layout-scripts=arab.dflt,arab.URD,latn
To keep `DefaultLangSys` and `URD` language for `arab` script, and all languages for `latn` script.

[subset] Allow LangSys tags in --layout-scripts

---

Lib/fontTools/ttLib/woff2.py
Tests/ttLib/woff2_test.py
Tests/ttx/ttx_test.py
setup.py

brotlipy has been renamed to brotlicffi to no longer conflict with the import namespace `brotli` and now guarantees the same API as Google's C bindings.
This example project shows how to use the `brotlicffi` library: https://github.com/python-hyper/brotlicffi/tree/master/example

Switch from brotlipy to brotlicffi for PyPy support

---

Lib/fontTools/colorLib/builder.py

Makes a huge difference when processing complex svgs to COLR. On my macbook:
```
time nanoemoji ~/oss/noto-emoji/third_party/waved-flags/svg/emoji_u1f1f7_1f1f8.svg
before: real  1m57.618s
after: real  1m14.734s
```
Also shows in profile, see https://github.com/googlefonts/nanoemoji/issues/218

Cache tuples

---

Tests/ttLib/woff2_test.py

There is a small typo in Tests/ttLib/woff2_test.py.
Should read `override` rather than `ovverride`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, ovverride -> override

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/CmapSubsetTest.subset.ttx
Tests/subset/data/CmapSubsetTest.ttx
Tests/subset/data/TestContextSubstFormat3.ttx
Tests/subset/subset_test.py

Behdad was prescient at https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L2228-L2231.
My idea: 
1. Delete a `platformID="0" platEncID="4" format="12" language="X"` (Unicode platform, Unicode full repertoire) cmap if there is a `platformID="0" platEncID="3" language="X"` (Unicode BMP only) cmap that contains the same Unicode set after subsetting.
2. Delete a `platformID="3" platEncID="10" format="12" language="X"` (Windows platform, Unicode full repertoire) cmap if there is a `platformID="3" platEncID="1" language="X"` (Unicode BMP) cmap that contains the same Unicode set after subsetting.

Subsetting: prune redundant format 12 cmaps

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/colorLib/geometry.py
Tests/colorLib/builder_test.py

Fixes encoding a tricky radial gradient in Noto Emoji's 🦟 (U+1F99F) https://github.com/googlefonts/picosvg/issues/158
For more info also see discussion at https://github.com/googlefonts/colr-gradients-spec/issues/204

COLRv1: avoid abrupt change after rounding c0 when too near c1's perimeter

---

Lib/fontTools/varLib/featureVars.py

I.e. when you forgot to add `languagesystem grek dflt;` to your feature file.
Before: 
> fontmake: Error: In 'MyFont.designspace': Generating fonts from Designspace failed: 'NoneType' object has no attribute 'FeatureIndex'
After:
> fontmake: Error: In 'MyFont.designspace': Generating fonts from Designspace failed: Feature variations require that the script 'grek' defines a default language system.

[varLib] featureVars.addFeatureVariationsRaw: Raise legible error message when script is missing a dflt langsys

---

Lib/fontTools/colorLib/builder.py
Tests/colorLib/builder_test.py

PaintColrLayers.NumLayers is 8-bit unsigned int (max 255). When a source len(paints) > 255, we were raising a compilation error.
With this patch, we now build a 255-ary tree of PaintColrLayers which theoretically supports unlimited number of leaves.
E.g. the BASKET in Noto Emoji contains a whopping 364 layers.

COLRv1: support unlimited paints as 255-ary tree of PaintColrLayers 

---

Lib/fontTools/encodings/codecs.py
Tests/ttLib/tables/_n_a_m_e_test.py

codecs: handle errors different from 'strict' for extended mac encodings

---

Lib/fontTools/otlLib/builder.py
Tests/otlLib/builder_test.py

There is currently an assertion in ClassDefBuild.add that stops a glyph that is already present in a class from being added again. However, there is no error reported, and thus it can be quite difficult to debug.
This PR changes this assertion into a raised exception, while also adding the related tests.

Raise an exception when ClassDefBuilder attempts to add a duplicate glyph.

---

Lib/fontTools/ttLib/woff2.py
NEWS.rst
Tests/ttLib/data/woff2_overlap_offcurve_in.ttx
Tests/ttLib/woff2_test.py

This fixes outline corruption of glyphs that start with an off-curve and have e.g. the overlap bit set, previously they'd be turned into on-curves.

WOFF2: An off-curve should stay off even with flags

---

Lib/fontTools/fontBuilder.py

COLR Base glyph records must be sorted by glyph index. The `colorLib.builder.buildCOLR` function has an optional `glyphMap` parameter that maps from glyph names to glyph indices (as returned from `TTFont.getReverseGlyphMap()`).
FontBuilder knows all that so it should pass it on to colorLib to ensure base records are sorted by GID.

fontBuilder: pass glyphMap to buildCOLR to sort base records by GID 

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/colorLib/unbuilder.py
Lib/fontTools/ttLib/tables/otTables.py
Tests/colorLib/builder_test.py
Tests/colorLib/unbuilder_test.py

When a `TTFont` is loaded with `lazy=True`, the otTables are only decompiled upon request by `BaseTable.__getattr__` triggered when the requested attribute is not found in the instance's `__dict__`.
Since the `Paint.Format` enum class was defined inside the `Paint` class, every `Paint` instance, even when loaded lazily, would have a 'Format' attribute and the magic decompile-on-missing-attribute would not trigger, because the class attribute was being returned and thus `__getattr__` would not be executed, and the lazy Paint instance was not correctly decompiled on demand.
For this reason (and to not add further special cases), it's better to simply move this `Paint.Format` enum class outside the `Paint` class to the module level scope, and rename it `PaintFormat`.

COLRv1: fix lazy loading by moving Paint.Format enum outside of Paint class nested scope

---

Doc/source/ttLib/ttFont.rst
Lib/fontTools/pens/ttGlyphPen.py
Lib/fontTools/ttLib/ttFont.py

I've been trying to do more complicated stuff (involving components) with the fontBuilder, and it was very painful because it really wasn't clear how to use `TTGlyphPen` to build new glyphs. I will be making some changes to fontBuilder to make it all easier, but this is what I discovered along the way.

Document expected arguments for _TTGlyphSet, _TTGlyph and TTGlyphPen

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/colorLib/table_builder.py
Lib/fontTools/colorLib/unbuilder.py
Lib/fontTools/ttLib/tables/otConverters.py
Lib/fontTools/ttLib/tables/otData.py
Tests/colorLib/builder_test.py
Tests/colorLib/table_builder_test.py
Tests/colorLib/unbuilder_test.py

Writing per-format functions is tiresome, try to avoid it by leaning on otData. Setting up as PR because I think it's far enough along it might be convenient to be able to comment.

Use otData for dict to COLR conversion

---

Lib/fontTools/colorLib/builder.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/C_O_L_R_.py
Lib/fontTools/ttLib/tables/otTables.py
Tests/subset/subset_test.py

This adds support for subsetting COLRv1 base glyphs (#2127)
Does not yet implement ~~pruning unused CPAL palettes (#2174) or~~ unused varIndices in CORL.VarStore.
EDIT: It now also implements pruning unused CPAL palette entries.

Subset COLRv1 & prune unused CPAL entries

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/data/GPOS_4.fea
Tests/feaLib/data/GPOS_5.fea
Tests/feaLib/data/GPOS_6.fea
Tests/feaLib/data/bug453.fea
Tests/feaLib/data/spec6d2.fea
Tests/feaLib/data/spec6e.fea
Tests/feaLib/data/spec6f.fea
Tests/feaLib/data/spec6h_ii.fea

This changes the formatting of ast.MarkBasePosStatement, ast.MarkLigPosStatement, ast.MarkMarkPosStatement to indent the anchor statements and make them a bit more legible or diffable.
For example:
```
pos base a <anchor 11 1> mark @TOP_MARKS <anchor 12 -1> mark @BOTTOM_MARKS;
pos ligature [c_t s_t] <anchor 500 800> mark @TOP_MARKS <anchor 500 -200> mark @BOTTOM_MARKS
ligComponent <anchor 1500 800> mark @TOP_MARKS <anchor 1500 -200> mark @BOTTOM_MARKS <anchor 1550 0> mark @OGONEK;
pos mark [acute grave macron ogonek] <anchor 500 200> mark @TOP_MARKS <anchor 500 -80> mark @BOTTOM_MARKS;
```
would become
```
pos base a
<anchor 11 1> mark @TOP_MARKS
<anchor 12 -1> mark @BOTTOM_MARKS;
pos ligature [c_t s_t]
<anchor 500 800> mark @TOP_MARKS
<anchor 500 -200> mark @BOTTOM_MARKS
ligComponent …
```

[feaLib] Format anchors one per line instead of all on the same line

---

Lib/fontTools/misc/arrayTools.py
Lib/fontTools/misc/bezierTools.py

Adds the following functions to bezierTools:
* quadraticPointAtT
* cubicPointAtT
* linePointAtT
And the generic function which takes a list of tuples and dispatches to the right point-at-time function
* segmentPointAtT
As well as intersection functions:
* lineLineIntersections
* curveLineIntersections
* curveCurveIntersections
And the generic function which takes two lists of tuples and dispatches to the right intersections function:
* segmentSegmentIntersections
Implementations taken from my beziers.py library.

Add intersections and point-at-time functions to bezierTools

---

Lib/fontTools/misc/arrayTools.py
Lib/fontTools/misc/vector.py
Lib/fontTools/varLib/__init__.py
Tests/misc/arrayTools_test.py
Tests/misc/vector_test.py

I felt our n-dimensional Vector class could be improved by making it a subclass of tuple, and deserves its own module.
This change makes Vector instances immutable. It appears this was the intention, as it did support `__getitem__` but not `__setitem__`.
The internal `values` attribute is gone. I added a `values` read-only property for backward compatibility. Setting `.values` is no longer supported (due to Vector's new immutablity).
I added a two methods:
- `vector.length()`: an alias for `abs(vector)`
- `vector.normalized()`: returns the norm vector
I added some DeprecationWarnings.

[misc.arrayTools] move Vector to its own submodule, and rewrite as a tuple subclass

---

Lib/fontTools/varLib/cff.py
Lib/fontTools/varLib/errors.py

Add VarLibCFFHintTypeMergeError, raised when hint (and hintmask) incompatibilities occur during CFF merging.
Closes #2197

[varlib] disambiguate cff merge errors

---

Lib/fontTools/varLib/errors.py
Lib/fontTools/varLib/merger.py
Tests/varLib/data/IncompatibleArrays.designspace
Tests/varLib/data/IncompatibleFeatures.designspace
Tests/varLib/data/IncompatibleLookupTypes.designspace
Tests/varLib/data/master_incompatible_arrays/IncompatibleArrays-Bold.ttx
Tests/varLib/data/master_incompatible_arrays/IncompatibleArrays-Regular.ttx
Tests/varLib/data/master_incompatible_features/IncompatibleFeatures-Bold.ttx
Tests/varLib/data/master_incompatible_features/IncompatibleFeatures-Regular.ttx
Tests/varLib/data/master_incompatible_lookup_types/IncompatibleLookupTypes-Bold.ttx
Tests/varLib/data/master_incompatible_lookup_types/IncompatibleLookupTypes-Regular.ttx
Tests/varLib/varLib_test.py

Fixes #2224 (as well as some other silent errors) and adds a test.

(Even) better merger errors

---

Lib/fontTools/misc/py23.py

This warning doesn't seem to have teeth since it has been around for 2+ yrs :)

[py23] Nit: change py23 deprecation warning from "next release" to "future release"

---

Lib/fontTools/otlLib/builder.py
Tests/otlLib/builder_test.py

Follow up from https://github.com/fonttools/fonttools/pull/2229
see discussion at https://github.com/fonttools/fonttools/commit/2089d051265d96db9dfdbcf15af10e1e003ccd82#r48578120

[otlLib] Ensure built ValueRecords are padded with 0s like when decompiled

---

Lib/fontTools/cffLib/__init__.py
Lib/fontTools/cffLib/specializer.py
Lib/fontTools/fontBuilder.py
Lib/fontTools/misc/etree.py
Lib/fontTools/misc/filenames.py
Lib/fontTools/misc/loggingTools.py
Lib/fontTools/misc/psCharStrings.py
Lib/fontTools/misc/sstruct.py
Lib/fontTools/misc/textTools.py
Lib/fontTools/ttLib/macUtils.py
Lib/fontTools/ttLib/tables/C_O_L_R_.py
Lib/fontTools/ttLib/tables/C_P_A_L_.py
Lib/fontTools/ttLib/tables/G_M_A_P_.py
Lib/fontTools/ttLib/tables/G_P_K_G_.py
Lib/fontTools/ttLib/tables/M_E_T_A_.py
Lib/fontTools/ttLib/tables/V_O_R_G_.py
Lib/fontTools/unicode.py
Tests/misc/timeTools_test.py

Tracking in https://github.com/fonttools/fonttools/issues/2232
This PR replaces `basestring` with `str` across all library and test modules *except* misc.py23.  I tested this locally in cPy3.9 with the py23 module basestring definition removed and the test suite passes

py23 transition: Convert `basestring` to `str`

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/GPOS_PairPos_Format2_ClassDef1_useClass0.subset.ttx
Tests/subset/data/GPOS_PairPos_Format2_ClassDef2_useClass0.subset.ttx
Tests/subset/data/GPOS_PairPos_Format2_PR_2221.ttx
Tests/subset/subset_test.py

This does two things:
1. Intersect subsetter glyphset with the table's Coverage before
passing to ClassDef1 for subsetting.  Anything that doesn't
get past Coverage wouldn't ever get to ClassDef1,
2. Never reuse class0 of ClassDef2.  There's unspoken assumption
that ClassDef2's class0 is never used for actual kerning, since
that's the unbounded "every other glyph" class.  Previously our
ClassDef subsetter was reusing class0 if "every other glyph"
happened to become empty because of the subset glyphset.  Don't
do that for PairPos's ClassDef2.  As a result of this assumption,
don't keep a PairPosClass2 subtable if only ClassDef2's class0
survived subsetting.
Would be good to add tests for both.
Related to https://github.com/harfbuzz/harfbuzz/issues/2703

[subset] Improve PairPosFormat2 subsetting

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/otBase.py
Lib/fontTools/varLib/merger.py

Fixes https://github.com/fonttools/fonttools/issues/2272
The 4 failing tests are adjacent and because of the second commit.  2 of them just need expectations updated. The other two, that are producing empty lookup:
```
+      <Lookup index="0" empty="1"/>
```
need a fix in `feaLib` (I suppose) to prune empty lookups. I couldn't understand why that's not happening.

[subset] Fix hint-dropping

---

Lib/fontTools/varLib/instancer/__init__.py

Updated to indicate that Level 3 axis range sub-spaces are supported
This section will need to be updated if/when https://github.com/fonttools/fonttools/issues/2157 is closed with an implementation for L4

[varLib.instancer] update instantiateVariableFont docs to indicate L3 support

---

Lib/fontTools/varLib/mutator.py

Otherwise head table compilation would fail because of the floating point side bearing. The advance width is already rounded.

[mutator] Round lsb for CFF2 fonts as well

---

Lib/fontTools/pens/basePen.py
Lib/fontTools/pens/pointPen.py
Lib/fontTools/pens/recordingPen.py

Extracted from https://github.com/fonttools/fonttools/pull/2202 to not let my commits rot too long.
1. Make RecordingPointPen actually pass on identifiers
2. Introduce PenError to eventually replace all the asserts in pen code, as assert should be used for debugging only.

Pen error maintenance

---

Lib/fontTools/ttLib/removeOverlaps.py
Tests/ttLib/removeOverlaps_test.py

Sometimes skia-pathops simplify may fail (for unknown reasons which I'm still trying to debug).
It's a good idea to know the name of the offending glyph
https://github.com/google/fonts/issues/3365
EDIT: It's actually even better to **not** fail at all. It turns out that if we round the path's coordinates to integers _before_ passing it on to pathops.simplify, then it works -- at least for the two glyphs in the Noto Ethiopic and Telugu fonts which triggered this issue.
The effect of rounding before removing overlaps is minimal, since we are going to round afterwards anyway once we encode the glyf table; besides, we only try rounding when simplify fails with the unrounded float coordinates (the ones that we get from the instancer).
All in all, I believe the workaround is better than …

removeOverlaps: work around pathops.simplify error

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/delete_glyph.fea
Tests/feaLib/data/delete_glyph.ttx

`sub [a b c] by NULL;` was producing errors, now it builds as multiple statements.

[feaLib] Allow substituting a glyph class with NULL

---

Lib/fontTools/feaLib/ast.py

...although I'm not sure what this backslash-space sequence is supposed to do.

[feaLib] fixed two instances of 'DeprecationWarning: invalid escape sequence'

---

Lib/fontTools/varLib/merger.py
Tests/varLib/instancer/data/PartialInstancerTest4-VF.ttx
Tests/varLib/instancer/instancer_test.py

If ValueRecord has XAdvDevice but no XAdvance, the MutatorMerger currently raises AttributeError as it assumes that whenever one of the Device tables are present, the respective non-device values are also present -- but they might be omitted, and should default to 0. 
Adding the failing test case, followed by the fix itself

instancer: Fix AttributeError when ValueRecord has XAdvDevice but no XAdvance

---

Lib/fontTools/pens/pointPen.py

Allows GuessSmoothPointPen to accept a parameterized tolerance for testing. Note that the code is not exactly identical to the fontPens version to keep the diff minimal. As a bonus, `math.atan2()` call is fixed as well. See also #2343.

Use newer version of GuessSmoothPointPen from fontPens

---

Lib/fontTools/ttLib/tables/TupleVariation.py

In python 3.7 and earlier most_common() sorts first by the item count and then arbitrarily in the event of ties. This can result in two identical instancing operations producing different binary results.

sort shared tuples produced by Counter.most_common()

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Tests/ttLib/tables/TupleVariation_test.py

most frequent first (like before https://github.com/fonttools/fonttools/pull/2351), only sort ties alphabetically

TupleVariation: make shared tuples order deterministic

---

Lib/fontTools/misc/intTools.py
Lib/fontTools/otlLib/builder.py
Lib/fontTools/otlLib/optimize/__init__.py
Lib/fontTools/otlLib/optimize/__main__.py
Lib/fontTools/otlLib/optimize/gpos.py
Lib/fontTools/varLib/merger.py
NEWS.rst
Snippets/compact_gpos.py
Tests/otlLib/optimize_test.py

This PR upstreams to fontTools a way to compact binary GPOS table in TTF, by splitting them into subtables in a smart way. The algorithm can yield significant file size savings depending on the font, e.g. sometimes it removes 50% of the GPOS table, while preserving all the kerning information, leading to no change in the font's spacing, and no reflows in documents.
The idea behind this algorithm is that the GPOS subtables can be big sparse matrices, full of zeros, especially on fonts that cover multiple script with kerning between glyphs of the same script but not across scripts. (see the picture below for illustration purposes: it represents an hypothetical class to class kerning lookup, and shows how large regions without any data naturally appear in cross-script kerning or even within …

Add GPOS compaction code in varLib.merger and otlLib.builder + new `fonttools otlLib.optimize` command

---

Lib/fontTools/misc/xmlReader.py
Tests/ttLib/ttFont_test.py

[ttLib] when importing XML, only set sfntVersion if the font has no reader and is empty

---

Lib/fontTools/ttLib/removeOverlaps.py
Lib/fontTools/varLib/instancer/__init__.py

This is to be able to ignore tricky glyphs that sometimes trip up Skia PathOps.Simplify operation.
We have no idea how to fix this upstream (short of having the glyphs redrawn), and perfect is the enemy of good..
Works around https://github.com/fonttools/fonttools/issues/2363 and https://github.com/google/fonts/issues/3365
/cc @nathan-williams

instancer: add --ignore-overlap-errors option

---

Lib/fontTools/otlLib/builder.py

The chained contextual builder tries building up to three subtable formats, and then returns the smallest. If one of these builds overflows, the whole thing crashes, even though another subtable would work fine. This mitigates the crash by emptying out subtable formats which do not build correctly.
The reason I could not catch a more specific exception is because the symptom of the build overflowing is obscure (See #2290):
```
'OTTableWriter' object has no attribute 'name'
```

[otlLib] Fix chained contextual builder overflow

---

Lib/fontTools/misc/bezierTools.py
Tests/misc/bezierTools_test.py

This fixes two problems in bezierTools:
* First, if a line was *almost* horizontal or *almost* vertical - but had a height/weight of > epsilon - then finding a point on the line would return nonsensical values.
* Second, when finding a curve/line intersection, the returned intersection point could, because of floating point error, not *quite* be on the line, leading to problems later.

Fix two problems when handling orthogonal lines

---

Lib/fontTools/otlLib/builder.py

My fix to @anthrotype's review comment in #2404 was premature. If a lookup could not be expressed as a particular format, the value in the `candidates` array would be `None`. The overflow check would try building it *anyway*, leading to ridiculous warnings:
```
WARNING: Contextual format 1 at foo.fea:5:5 overflowed ('NoneType' object is not iterable)
```
This skips over non-existent subtables when doing the overflow check.

Fix overflow check (again)

---

.github/workflows/test.yml
README.rst
Tests/designspaceLib/designspace_test.py
Tests/t1Lib/t1Lib_test.py
mypy.ini
setup.py
tox.ini

3.10 is out next week, while 3.6 reaches end of life by the end of this year.
It's time to require 3.7 or greater, so we can finally use built-in dataclasses and more.
Fixes https://github.com/fonttools/fonttools/issues/2350

drop Python 3.6, require >= 3.7

---

Lib/fontTools/unicodedata/Blocks.py
Lib/fontTools/unicodedata/ScriptExtensions.py
Lib/fontTools/unicodedata/Scripts.py
Lib/fontTools/unicodedata/__init__.py
Tests/unicodedata_test.py

In Debian we have unicode-data updated to 14.0 and encountered some test errors.
This PR updates unicodedata to 14.0 and fixes the related tests.  Please review.

update to unicode 14.0

---

Lib/fontTools/colorLib/unbuilder.py
Tests/colorLib/unbuilder_test.py

Don't crash if there is no layer list

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/otTables.py
Tests/ttLib/tables/otTables_test.py

Fixes #2438. Again :D In addition to unit test `pyftsubset --output-file=/tmp/reem.ttf --gids=0,128,210,211,218,225,227,232,234,235,237,238,241,244,246,250,251,254,261,264,270,271,277,280,282,284,286,289,295,297,299,307,308,316,317,318,320,327,331,343,345,347,348,349,350,351,357,365,370,371,374,376,378,392,393,398,399 ReemKufiInk-Regular.otf` now doesn't kerplode.

Traverse when there is no layer list

---

setup.cfg

[interrogate](https://interrogate.readthedocs.io/en/latest/) is a handy tool for checking documentation coverage. This configures interrogate with some project-specific defaults.

[docs] Add interrogate configuration

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/subset/cff.py
Lib/fontTools/subset/svg.py
Lib/fontTools/subset/util.py
Tests/subset/subset_test.py
Tests/subset/svg_test.py
tox.ini

Add support for subsetting OT-SVG table 

---

Lib/fontTools/ttLib/sfnt.py

The optional “start” parameter isn’t there, so that part of the comment is not current.

Removed comment about missing “start” optional argument to `calcChecksum`

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/PairPosSubtable.fea

This follows on from #2445, and forbids the following FEA syntax:
```fea
markClass [] <anchor 150 -10> @TOPMARKS;
feature test {
sub a by [];
sub a by c [];
sub a from [];
sub f f [] by f;
ignore sub a []';
ignore sub [] a';
sub a []' by b;
sub [] a' by b;
rsub [] by a;
pos [] 120;
pos a [] 120;
enum pos a [] 120;
pos cursive [] <anchor NULL> <anchor NULL>;
pos base [] <anchor NULL> mark @TOPMARKS;
pos mark [] <anchor NULL> mark @TOPMARKS;
pos ligature [] <anchor NULL> mark @TOPMARKS;
ignore pos a []';
ignore pos [] a';
} test;
```
All of these rules were allowed before, and would fail with hard errors (i.e. non user-facing stuff, IndexErrors and the like) in the builder. Glyph deletion is still allowed with the *explicit* NULL glyph.

Forbid empty classes (take 2)

---

Lib/fontTools/ttLib/tables/otTables.py

I've been looking at overflow resolution this morning, as it is currently the bane of my life. My font takes around 5 minutes to build, most of which time is taken up with resolving lookup overflows. (Not subtable overflows - lookup overflows.) The reason overflow resolution takes so long is that once an overflow is resolved, fontTools goes back and starts the whole compilation process all over again.
Now. It seems to me that if the offset to lookup N is too big to fit in a ushort, the offset to lookup N+1 is going to be too big as well. In fact, all lookups from lookup N onwards are going to need handling. So rather than handling them one at a time, why not just promote the lot to extension lookups?
Doing this takes my font's build time down to 30 seconds, almost none of which is to do …

Speculatively promote lookups to extension

---

Lib/fontTools/ttLib/tables/otBase.py

This line in `otBase.py` took me quite a while to puzzle out:
```
items[i] = item = internedTables.setdefault(item, item)
```
I *knew* that it was deduplicating the subwriter graph, but it's wasn't immediately clear *how*.  Since the compilation/OTTableWriter code is pretty gnarly at the best of times, I figure we should be trying to help people find their way through it.

Demystify deduplication

---

Lib/fontTools/pens/svgPathPen.py

If one wants to draw a TTFont's glyph outlines as SVG paths while at the same time apply some rounding to the float coordinates (e.g. introduced as result of some transformation), at the moment adding a RoundingPen filter to the pen chain is not sufficient when the glyph contains TrueType quadratic splines (qCurveTo). That's because the rounding would occur too early, before the qCurve get split into atomic quadratic Bezier segments (this is done in the superclass BasePen.qCurveTo method, that calls the SVGPathPen._qCurveToOne with each sub-curve), thus leaving unwanted floating-point coordinates in the SVG output.
An alternative approach is to make sure that the qCurves are decomposed before they reach the RoundingPen, by defining a new filter pen that does that, e.g.:
```python
from …
```

svgPathPen: add option to customize number formatting (e.g. rounding)

---

Doc/source/optional.rst
Lib/fontTools/unicodedata/__init__.py
README.rst
requirements.txt
setup.py

it now supports pypy3 and Unicode 14.0
https://github.com/fonttools/unicodedata2/releases/tag/14.0.0
Python 3.11 doesn't require the backport as it already ships Unicode 14.0

bump unicodedata2 dependency to 14.0.0

---

Lib/fontTools/misc/psLib.py

In Python 3, `bytes` != `str`, so we explicitly convert to str, since the `fontdir.keys()` are of type `str`.
To check the behavior, for example, do as follows:
```python
>>> from fontTools.t1Lib import T1Font
>>> t1Font = T1Font('Tests/t1Lib/data/TestT1-Regular.pfa')
>>> gs = t1Font.getGlyphSet()
```

Fix type of fontName in suckfont

---

Doc/docs-requirements.txt
Lib/fontTools/pens/freetypePen.py
Tests/pens/freetypePen_test.py

#2494 fails to generate the corresponding RTD entry due to the lack of the dependency:
https://readthedocs.org/api/v2/build/15748934.txt
```
WARNING: autodoc: failed to import module 'freetypePen' from module 'fontTools.pens'; the following exception was raised:
No module named 'freetype'
```
This PR solves the issue by raising ImportError in `__init__`, rather than by adding a line to `Doc/docs-requirements.txt`.

FreeTypePen: fix missing RTD entry

---

Lib/fontTools/ttx.py
Tests/ttx/ttx_test.py

One should just use 'pause' command in a batch script to wait to for key press, no need for ttx to do anything.
Fixes #2507

remove waitForKeyPress on windows

---

Lib/fontTools/ufoLib/filenames.py
Tests/ufoLib/filenames_test.py

This PR fixes:
1. The "\0" was inside a raw string, meaning it wasn't getting substituted.
2. The "(" and ")" characters are listed in the specification as illegal, but weren't getting substituted.
3. The reserved names were missing LPT5-9 and COM5-9.
4. The previous code had "A:-Z:" literally in the reserved names, but did not expand them, so they were "dead weight". Colons were always replaced first so drive letters never survived to that stage anyway.
It does not fix:
1. Filenames must not end in a period or space.
2. Prefix and suffix aren't being treated.

[ufoLib] Expand reserved names and fix illegal characters

---

Lib/fontTools/colorLib/geometry.py
Tests/colorLib/builder_test.py

Fixes rounding of radial gradient geometry in 'SING OF THE HORNS' (medium-light skin tone) noto emoji 🤘🏼
noto-emoji CORLv1 font **before** this patch (notice the darker knuckle):
And **after** this patch (all look good):
***
This is basically the same bug as https://github.com/googlefonts/picosvg/issues/158 which affected the 🦟 mosquito emoji. It turns out the tolerance we are using to consider whether start circle is inside the end circle was too strict/tight. Relaxing a bit, and making it _relative_ tolerance (as in `math.isclose` as opposed to absolute difference) makes both the 🦟 and the 🤘🏼 happy.

[colrv1] use math.isclose with relative tolerance to check radial circles' inside-ness

---

Lib/fontTools/otlLib/builder.py
Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/otlLib/builder_test.py
Tests/ttLib/tables/_n_a_m_e_test.py

The function to create a STAT table created duplicate name table entries, because it did not take care about existing name table entries with the name name. This PullRequest takes care about it.
EDIT(anthrotype): `buildStatTable` calls `nameTable.addMultilingualName` which by default creates both mac and windows names; if the name table only contains one of the two (usually only windows, no mac ones), then `addMultilingualName` can't reuse the existing name IDs (or else it would produce inconsistent nameIDs between mac and windows platforms) and thus it creates duplicate records. This PR adds `windowsNames` and `macNames` parameters to `buildStatTable` so that one can select whether to only add one or both of the two sets. This way, when calling buildStatTable with a name able that only …

Add windowsNames and macNames parameters to buildStatTable

---

Lib/fontTools/varLib/__init__.py

When building gvar, some situations cause fontmake/varLib to fail, for example if a component has a coordinate that's >32k or <-32k. This adds a debug line that prints each glyph name for which gvar is built, so it’s easier to pinpoint where the faulty glyph is.

Add debug logger showing the glyph name for which gvar is built

---

Lib/fontTools/ttLib/ttCollection.py
Tests/ttLib/ttCollection_test.py

currently fails with 'ValueError: seek of closed file'

fix opening TTCollection with lazy=True

---

Lib/fontTools/varLib/merger.py

I had a situation where I instanced a variable font, fiddled with the instances, and put it back together into a variable font; but the merge step was not working. It turned out this was because the font had a single positioning rule (called by a contextual positioning rule) which was only effective for some locations. At other locations, the rule had no effect, so it had a ValueFormat=0.
Although the merger has code to set the output value format of a single pos to be the highest format of its constituent subtables, it still attempts to merge the ValueFormat attributes. These should be added to the exclude list.
Additionally, I came across a lookup where *all* the value formats of a subtable were zero. (I was splitting a variable font with a ital axis into separate Upright/Italic VFs, …

Handle merging SinglePos with valueformat=0

---

Lib/fontTools/ttLib/tables/_c_m_a_p.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/ttLib/tables/otBase.py
Lib/fontTools/ttLib/ttFont.py
Tests/ttLib/ttFont_test.py

While attempting to tackle glyph reordering in https://github.com/fonttools/fonttools/issues/2060, I needed a way to say "decompile everything in the font". The lazy=False unfortunately does not exactly do what it says to be doing, and that's confusing for people who are not familiar with the fonttools internals (some colleagues did stumble on this). Not only one has to set lazy=False, but one also has to iterate over all the tables and actually decompile them using silly loop like:
```python
for tag in font.keys():
_ = font[tag]
```
A quick recap about `TTFont.lazy` attribute. It has three states: it defaults to None, and can be optionally be set to True or False.
When it is set to True, the font keeps a reference to the original input file (inside its SFTNReader); when it's None (or …

add ensureDecompiled method to decompile all the tables irrespective of lazy attribute

---

Lib/fontTools/subset/svg.py
Tests/subset/svg_test.py

/cc @frankrolf
Fixes https://github.com/fonttools/fonttools/issues/2548
I tested locally with [Noto Emoji OT-SVG](https://github.com/adobe-fonts/noto-emoji-svg/releases) and it works now

[subset] fix subsetting OT-SVG when glyph id attribute is on the root <svg> element

---

Lib/fontTools/varLib/merger.py
Tests/varLib/instancer/data/SinglePos.ttx
Tests/varLib/instancer/data/test_results/SinglePos-VF-instance-280,18.ttx
Tests/varLib/instancer/instancer_test.py

Under certain conditions, instantiating GPOS SinglePos subtables results in all zero values. This seems to be caused by the merger reassigning the output `Value` to a new `ValueRecord` before merging it, but the “things” it is being merged with is a list with a single item which is the output Value itself, so it gets overridden to zero before merging.
The above is probably gibberish since I don’t really understand much of varLib, but the fix seems to copy the old `Value` to when creating a new one before merging.
Without this fix the added test will have its SinglePos values incorrectly instantiated to zero.

[varLib] Fix instantiating some SinglePos subtables

---

Lib/fontTools/ufoLib/glifLib.py
Lib/fontTools/varLib/interpolatable.py

This seems to work already. Detects the example in the issue.
I also ran this on master-compatible UFOs built from Noto Sans,
and detected several issues. Confirmed visuall in AxisPraxis that
theta.sc for example has wrong starting point in that font, there's more...
```
Glyph theta.sc was not compatible:
Contour start point differs: NotoSans-DisplayRegular, NotoSans-DisplaySemiBoldCondensed
Contour start point differs: NotoSans-DisplayRegular, NotoSans-DisplaySemiBoldCondensed
Contour start point differs: NotoSans-DisplaySemiBoldCondensed, NotoSans-DisplaySemiBold
Contour start point differs: NotoSans-DisplaySemiBoldCondensed, NotoSans-DisplaySemiBold
```
There's a TODO item left to be done, which is to check for mirrored
contours and rotations thereof.
Towards fixing …

[varLib.interpolatable] Check for wrong contour starting point

---

Lib/fontTools/misc/psCharStrings.py
Tests/misc/psCharStrings_test.py

[CFF/T2] Ensure that pen.closePath() gets called for CFF2 charstrings. Fixes #2455

[CFF/T2] Ensure that pen.closePath() gets called for CFF2 charstrings

---

Lib/fontTools/ttLib/tables/_c_m_a_p.py

It is bad style, and causes unnecessarily confusing tracebacks, such as seen in #2584.
Additionally, use `v = d.get(k)` instead of checking first and then getting.

[cmap] don't handle expected case in exception handler

---

Lib/fontTools/config/__init__.py
Lib/fontTools/misc/configTools.py
Lib/fontTools/misc/testTools.py
Lib/fontTools/otlLib/optimize/__init__.py
Lib/fontTools/otlLib/optimize/gpos.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/otBase.py
Tests/config_test.py
Tests/misc/configTools_test.py
Tests/subset/subset_test.py

As discussed in #2552, this adds a config option to disable serializing GSUB/GPOS with uharfbuzz even when the latter can be imported.
I also took this opportunity to make some changes to the configTools. The Config mapping methods accept either a str (name of an option) or the Option object itself, which I think can be handy and avoids repetition when the latter is already in scope.

define USE_HARFBUZZ_REPACKER config option

---

Lib/fontTools/otlLib/builder.py
Lib/fontTools/otlLib/optimize/gpos.py
Lib/fontTools/varLib/merger.py

Attempt to fix https://github.com/fonttools/fonttools/issues/2592 by bringing back the environment variable until ufo2ft can switch to using the new config system
@anthrotype

Fix ufo2ft regression by bringing back the env var for now

---

Lib/fontTools/ttLib/tables/otBase.py
Tests/subset/subset_test.py

Fixes https://github.com/fonttools/fonttools/issues/2594
* when hb repacker fails, we now emit a WARNING logging message, no longer an ERROR
* we only emit the warning message once, not multiple times at each iteration of the offset overflow resolution loop; it's always going to be the same anyway and it doesn't currently add any additional information besides the fact that it failed
* we no longer let the uharfbuzz error propagate (and thus stop execution if unhandled by client) even when the USE_HARFBUZZ_REPACKER option was explicitly set to True by the user, but we continue with the hybrid approach of trying hb first and if that fails attempt to fix offset overflow with pure-python serializer then re-trying until it completes. This is the normal state of things until hb repacker …

[otBase] demote repacker ERROR to WARNING, only 1 per loop; don't exit at first failure

---

Lib/fontTools/designspaceLib/types.py

just happened to see this in a lint check for our own code

correct naming of dataclasses '__post_init__' method

---

.github/workflows/publish.yml
.github/workflows/test.yml

* Use newer GitHub Actions
* Test on Python 3.7 and 3.10 on Ubuntu, and only on 3.10 on Windows and macOS

Update CI testing

---

Lib/fontTools/svgLib/path/parser.py
Tests/svgLib/path/parser_test.py

SVG documentation has an explicit requirement that _consumers_
of path arc commands accept and *correct* certain bad values.
This includes using the absolute value of the arc command's rx
and ry radius parameters.
See "9.5.1. Out-of-range elliptical arc parameters"
https://www.w3.org/TR/SVG/paths.html#ArcOutOfRangeParameters
Lib\fontTools\svgLib\path\parser.py is missing any guard against
negative values for rx and ry parameter. Adding an abs() to each
value read will implement the SVG specification.
A problem was seen here while most programs and browsers handle
bad arc commands just fine. A bug report has been registered with
Inkscape (!) to protect any other non-SVG compliant programs.
See https://gitlab.com/inkscape/inbox/-/issues/6857 for more details.
This fix was tested and found …

Protect SVG path parsing from negative rx ry on arc commands

---

Lib/fontTools/svgLib/path/parser.py
Tests/svgLib/path/parser_test.py

Using svg.draw(pen) and parse_path() from svgLib threw exception
ValueError: could not convert string to float: 'a'
on a SVG <path> string generated by Inkscape. Altering the path
string might object to other string bits like 'Z' or 'v', or
give even stranger exceptions.
Finally tracked it down to the path containing particular valid
numbers like "-4e-5" or "1e-4". Changing these to "-4.0e-5" or
"1.0e-4" would stop the exceptions.  parse_path() was not
accepting valid SVG real numbers.
The specification for real number formats is a bit of a mess in
CSS land right now, but the reassuringly concrete spec is:
https://www.w3.org/TR/css-syntax-3/#number-token-diagram
which allows for a real number having an exponent but without having
a fractional part, such as the number "1e3".
This change …

Handle one more valid real number format in svgLib parse_path()

---

Lib/fontTools/ttLib/tables/otBase.py

Harfbuzz repacker can handle subtables shared across extension lookups so there's no need to disallow such sharing. Add a parameter to _doneWriting to allow sharing to be enabled when preparing the object graph for passing to harfbuzz.

Enable sharing across subtables of extension for harfbuzz packing.

---

Lib/fontTools/subset/svg.py
Lib/fontTools/ttLib/tables/S_V_G_.py
Tests/ttLib/tables/S_V_G__test.py

This is based on @bungeman's https://github.com/fonttools/fonttools/pull/2627 and it's supposed to supersede that one.
The difference is this tries to ensure that existing code that depends on `docList` containing sequences of three items `(doc, startGID, endGID)` continues to work without modification.
I define a new SVGDocument dataclass that exports a Sequence-like interface, only the first three elements can be read by their position in the fake tuple.

Clean up svgDoc compression #2

---

Lib/fontTools/varLib/errors.py
Lib/fontTools/varLib/merger.py

The exception `UnsupportedFormat` was defined and then immediately redefined with the same name in varLib.errors, and imported twice from varLib.merger, probably as result of a sweeping find/replace.
Rename the duplicate to `InconsistentFormats` as originally intended.

[varLib.merger/errors] fix undefined exception name

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

I just had a frustrating situation where the FEA parser reported a missing glyph in my source, and then I fixed it and re-ran it, and then it reported another missing glyph, and I fixed it and re-ran it, and...
With this PR, "missing glyph" errors are gathered and reported at the end of parsing:
```
ERROR: The following glyph names are referenced but are missing from the glyph set:
ampersand (first found at source/build/features.fea:43570:16)
asterisk (first found at source/build/features.fea:43605:14)
```

[feaLib] show all missing glyphs at once

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/data/name.fea
Tests/feaLib/data/name.ttx

Since https://github.com/adobe-type-tools/afdko/commit/3fa06c51db37d3a2fb967552d61c47c9fbb8584c, only nameIDs 2 and 6 are reserved.

[feaLib] Let the parser set nameIDs 1 through 6

---

Lib/fontTools/ttLib/tables/otBase.py
Tests/subset/subset_test.py

Refactor control flow of the packer to use a state machine with three states:
1. Pure python: only uses the existing fonttools packing and overflow resolution.
2. Harfbuzz+python: uses harfbuzz packing and python overflow resolution. Extensions are allowed to be shared.
3. Python fallback: if harfbuzz+python runs out of resolution options, this disables extension sharing and only uses python packing. Once it succeeds control is passed back to the harfbuzz packer to produce the final packing with extension sharing enabled.
Fixes #2661 while allowing extension sharing to be re-enabled.

Update how table packing falls back to fontTools from harfbuzz.

---

Lib/fontTools/feaLib/builder.py

- Allow features to be added to VF without building GDEF (say, to only add GSUB)
- Warn when GDEF would be needed but isn't requested
This fixes #2694

Allow features to be added to VF without building GDEF

---

Lib/fontTools/merge/cmap.py
Tests/merge/data/CFFFont_expected.ttx

Fixes https://github.com/fonttools/fonttools/issues/1950

[merge] Use '.' instead of '#' in duplicate glyph names

---

Tests/varLib/models_test.py
setup.cfg

From the commit message:
[varLib.models] Add test for modeling rounding error
Tests https://github.com/fonttools/fonttools/pull/2214
If you flip demo to True, it does a slower test and demos the new error as well
as the error the old code was producing (ie. rounding deltas post-modeling).
Indeed, the new error is always capped by 0.5 as expected, whereas the old one
was unbounded. Here's the worst-case error of the bad code:
...
240     0.42    4.8
...
240 is just the line number. 0.42 is new error. 4.8 is old error.

Test var model error

---

Lib/fontTools/feaLib/builder.py

Only warn about not-requested-GDEF if building a VF *and* GPOS is requested but GDEF isn't.
Fixes #2694 more.

[feaLib.builder] Fix for #2694: Remove GDEF warning

---

Lib/fontTools/varLib/models.py

It's okay for our other modules to use these symbols, but they don't really belong in the API of varLib.

[varLib] Clean up __all__

---

Lib/fontTools/ttLib/ttGlyphSet.py

A trivial fix to make glyph.drawPoints(pen) work for CFF glyphs.

[ttLib] make glyphset[gn].drawPoints(pointPen) work for CFF

---

Lib/fontTools/ttLib/tables/_g_v_a_r.py

Follow-up for #2741
Previously, the `gvar` glyph loader required the decompompilation of the entire `glyf` table. This can take a considerable amount of time for big fonts. With this change, `glyf` glyphs are also loaded on demand. 
In my use case (a laaaarge font), loading a single var glyph took about 10 seconds, and now it takes almost no time at all.

Read 'gvar' more lazily by not parsing all of the 'glyf' table

---

Lib/fontTools/ttLib/ttGlyphSet.py

This avoids going through SegmentToPointPen, which will arbitrarily delete an endpoint if happens to coincide with the start point. Which is not good for interpolation.

[ttLib] VarGlyphSet: implement drawPoints natively

---

Lib/fontTools/fontBuilder.py

This may seem weird for a real font, but it happens for a sparse master, where all variation happens in unencoded glyphs. (FontGoggles uses FontBuilder to build minimal master TTFs)

[fontBuilder] don't error when there are zero code points

---

Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ttLib/ttGlyphSet.py
Tests/pens/ttGlyphPen_test.py
Tests/ttLib/data/TestTTF_normalizeLocation.ttx
Tests/ttLib/ttFont_test.py
Tests/ttLib/ttGlyphSet_test.py

- only differentiate between glyf and CFF/CFF2 implementations, not var vs non-var
- use collections.abc.Mapping to get a more consistent dict-like object with less code
- prefer HVAR metrics over gvar metrics
- move some responsibilities from the _TTGlyphSet objects to the _TTGlyph objects
- adjust some tests to the changes

[ttGlyphSet] Refactor/rebuild class hierarchy

---

Lib/fontTools/ttLib/tables/_g_v_a_r.py
Tests/ttLib/tables/_g_v_a_r_test.py

like cmap, or glyf or OTL tables, we need to respect lazy=False flag and decompile everything upfront, also we want to add an ensureDecompiled method (called by TTFont.ensureDecompiled) to allow loading everything in one go even when a font had been opened lazily.

[gvar] be non lazy for TTFont.lazy=False, add ensureDecompiled

---

Lib/fontTools/designspaceLib/split.py
Tests/designspaceLib/split_test.py

Designspace documents can contain unbounded conditions, which [omit one of "minimum" or "maximum"](https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#condition-element). In fontTools, the absence of either is represented with None, both when designspace files [are parsed](https://github.com/fonttools/fonttools/blob/1306a71/Lib/fontTools/designspaceLib/__init__.py#L1838-L1850), and when designspace objects [are processed in varLib](https://github.com/fonttools/fonttools/blob/bb6fd8d22e7aa20d8ae6553c15f5686fbaf7d862/Lib/fontTools/varLib/__init__.py#L670-L677).
For unbounded conditions, the splitting functions expect "minimum" or "maximum" [to be absent](https://github.com/fonttools/fonttools/blob/1306a71db323556232b1f5ece1c2ab77476d0884/Lib/fontTools/designspaceLib/split.py#L …

Avoid crash when handling unbounded conditions during designspace splitting

---

Lib/fontTools/feaLib/lexer.py
setup.py

This adds unoptimized cython magic to the feaLib.lexer class. On a large feature file, it reduced parsing time from 27s to 18s. (I tried doing the same to feaLib.parser but it didn't gain much.)

Cythonize lexer

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/variable_bug2772.fea
Tests/feaLib/data/variable_bug2772.ttx

Use buildPairPosClassesSubtable's ability to promote value records; this allows variable and non-variable kerns to share a subtable. See discussion in #2772.

Promote pair-pos value records

---

Lib/fontTools/subset/__init__.py

may aid debugging lazy-loading issues like https://github.com/fonttools/fonttools/issues/2806

subset: add --no-lazy option to load font eagerly as TTFont(lazy=False)

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/instancer_test.py

same as https://github.com/fonttools/fonttools/pull/2811 but moved the logic to _instantiateFeatureVariations directly, instead of after it. Plus, added small test
/cc @qxliu76

[instancer] downgrade GSUB/GPOS version if there are no FeatureVariations after instancing (2)

---

Lib/fontTools/subset/__init__.py

Fixes #2814
or at least is a workaround until a proper 'fix'

[subset] keep and don't prune CPAL if OT-SVG table is present

---

Lib/fontTools/varLib/mutator.py

Avoid negative hmtx values when creating font from variable CFF2 font

---

Lib/fontTools/varLib/instancer/names.py

Add stat.ElidedFallbackNameID to the set of used name IDs, to prevent it being pruned. Fixes #2822

[instancer] Don't prune stat.ElidedFallbackNameID

---

Lib/fontTools/unicodedata/Blocks.py
Lib/fontTools/unicodedata/ScriptExtensions.py
Lib/fontTools/unicodedata/Scripts.py
Tests/unicodedata_test.py

by re-running the MetaTools/buildUCD.py script using the current UCD database.

unicodedata: Update Scripts/Blocks to Unicode 15.0

---

Lib/fontTools/subset/__init__.py
NEWS.rst
Tests/subset/subset_test.py

Hello, I'm Jack from the SD team at Dalton Maag. We found this while trying to subset a font with CPALv1. I assume that it was just missing an enumerate() ?

[subset] Keep nameIDs used by CPAL palette entry labels

---

Lib/fontTools/varLib/models.py
Tests/varLib/models_test.py

The problem @LettError pointed out in #2843 could be resolved if `supportScalar()` uses the axis min/max values, instead of hard-coding them to -1 and +1.
With this change, the snippet below shows extrapolations as expected:
```python
from fontTools.varLib.models import VariationModel
def formatRow(row, cellWidth=8):
fmt = f"{{v:>{cellWidth}}}"
return "".join(fmt.format(v=v) for v in row)
locations = [{}, {"x": 1}, {"y": 1}, {"x": 1, "y": 1}]
model = VariationModel(locations, extrapolate=True)
values = [100, 200, 300, 400]
rng = [-1, 0, 1, 2]
print(formatRow([""] + rng))
for x in rng:
row = [x]
for y in rng:
v = model.interpolateFromMasters({"x": x, "y": y}, values)
row.append(v)
print(formatRow(row))
```
Output:
```
-1       0       1       2
-1  -200.0     0.0   200.0   400.0
0  -100.0 …
```

[varLib.models] Attempt to fix #2843 by computing the axis ranges

---

Lib/fontTools/varLib/models.py

We are allowing extrapolation in the variation model, but when we normalise values, these are still clamped to the axis min/max (-1.0<=>1.0). This allows normalized values to extend beyond that range.
This may not be the right approach, because it looks like the extrapolation option of the variation model allows for values which aren't normalised but which just have a min/max range. But I don't understand that well enough to know how it handles defaults.

Allow extrapolation in normalization

---

Lib/fontTools/varLib/models.py
Tests/varLib/models_test.py

https://github.com/fonttools/fonttools/pull/2847 is incomplete, because it fails with ZeroDivisionError for things like:
```
normalizeLocation({"wght": 100}, {"wght": (400, 400, 700)}, extrapolate=True)
normalizeLocation({"wght": 1000}, {"wght": (400, 700, 700)}, extrapolate=True)
```
tests fails at the moment, fix in follow-up commit.

Fix ZeroDivisionErrors with normalizeLocation(extrapolate=True)

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py

This makes sure that when we are building variable fonts, we check that all masters have the same component transform in composite glyphs.  We were not checking for this before.

[glyf] Return component transform as part of control data

---

Lib/fontTools/varLib/instancer/__init__.py
Lib/fontTools/varLib/instancer/names.py
Tests/varLib/instancer/data/PartialInstancerTest-VF.ttx
Tests/varLib/instancer/instancer_test.py
Tests/varLib/instancer/names_test.py

Also renamed AxisTent => AxisTriple because I think "tent" is more appropriate to visualize master supports (i.e. a triangle with a peak in the middle), here it's simply the new desired min, default, max values of an axis, aka the axis limits.
I could have named the triple AxisLimit(s) but the latter name was already used to mean a map from axis tags to axis values so I decided to keep the term "AxisLimits" to mean exactly that; I even made a custom mapping that automatically expands singles/tuples so the rest of the code internally can expect triples.
The public facing `instantiateVariableFont` of course continues to accept a hybrid map of axis tags to single values or 2- (and now also 3-) tuples, which are normalized to this AxisLimits.
A lot of words for nothing.

[instancer-l4] expand singles/tuples to triples upfront and use triples throughout

---

Lib/fontTools/ttLib/tables/S_V_G_.py

Subsetting NotoColorEmojiSvg for one glyph.
Before: 280ms
After: 80ms
Fixes https://github.com/fonttools/fonttools/issues/2360

[subset/SVG] Speed up

---

Lib/fontTools/pens/svgPathPen.py

Fixes https://github.com/fonttools/fonttools/issues/2089

[svgPathPen] Don't close path in endPath()

---

Lib/fontTools/varLib/instancer/__init__.py
Lib/fontTools/varLib/instancer/names.py
Tests/varLib/instancer/instancer_test.py

Previously we were only updating these when pinning wght/wdth/slnt axes. Now we do whenever any of these axes defaults are changed, whether or not the axes are pinned or kept
Fixes https://github.com/fonttools/fonttools/issues/2885

[instancer] update OS/2 class and post.italicAngle when default moved (L4)

---

Lib/fontTools/ttLib/woff2.py
Tests/ttLib/woff2_test.py

Fixes #2576
This updates our `fontTools.ttLib.woff2` encoder/decoder to support retaining the `OVERLAP_SIMPLE` glyf flag, following the updated [WOFF 2.0 specification](https://www.w3.org/TR/WOFF2/#glyf_table_format) and official google/woff2 implementation.

[woff2] Support encoding/decoding OVERLAP_SIMPLE glyf flags

---

Lib/fontTools/ttLib/scaleUpem.py

Fixes https://github.com/fonttools/fonttools/issues/2893

Skip scaling of vsindex in scaleUpem.py

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_g_v_a_r.py

Keep it in the API though.
The compile code doesn't use the pointCount. This avoids expanding the glyph unnecessarily (and makes my smarties code work as well, since it builds glyphs that cannot be expanded by current fonttools).

[gvar] Don't expand glyph for unused pointCount

---

Lib/fontTools/feaLib/builder.py
README.rst
Tests/feaLib/data/name.ttx
Tests/feaLib/data/spec8b.ttx
Tests/feaLib/data/spec8c.ttx
Tests/feaLib/data/spec8d.ttx
Tests/feaLib/data/spec9e.ttx

This patch ensures that feaLib always produces a name table with entries sorted in the order proscribed by the spec: platform id, encoding id, language id, name id.
This breaks some tests, and so I have manually updated the test data to match the new outputs.
---
I'm not very familiar with this project, so very possible i have overlooked or omitted something, please let me know! There was one question I had, will point it out in the diff.
closes #2909

[feaLib] Sort name table entries in builder

---

Tests/feaLib/data/GPOS_1_zero.ttx

In what I presume was error, this test case included a space on the line immediately following the `<ttFont>` element; this space is not present in any other ttx files.
For reasons that are unclear to me, and likely not worth investigating, the presence (or absence) of this space does not influence the passing or failure of this test case; however it *does* cause a failure in my feature compiler, which is reusing this test suite, and so I would like to fix it here, and simplify my own life somewhat.

[feaLib] Remove rogue whitespace in GPOS_1_zero.ttx

---

Lib/fontTools/merge/__init__.py

Sort tags before processing; this makes merge behave more deterministically.
Due to the nature of Python sets, the unioning of the tag lists results in a fairly random tag order.
This causes surprising errors if multiple tables contain problems: you randomly get one or the other error.

[merge] Sort tags before processing

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/GSUB_5_formats.fea
Tests/feaLib/data/bug2949.fea
Tests/feaLib/data/bug2949.ttx
Tests/feaLib/data/bug509.fea
Tests/feaLib/parser_test.py

Fixes https://github.com/fonttools/fonttools/issues/2949
- If there are no marked glyphs in an "ignore" statement, issue a warning. The spec disallows this but makeotf allows it. It is most likely a typo, so a warning is warranted.
- Mark the first glyph not all the glyphs, this matches makeotf.
- In asFea() always mark the input glyph.
- Update the tests.

[feaLib] Fix handled of "ignore" with unmarked glyphs

---

Lib/fontTools/ttLib/tables/sbixGlyph.py

Instead of appending glyph raw data with `imageData` for `graphicType=dupe` which will always be `NoneType`, append with the reference glyph ID.
Closes https://github.com/fonttools/fonttools/issues/2962

Handle glyphs with dupe graphic type on compile correctly

---

Lib/fontTools/ttLib/tables/otBase.py
Tests/subset/subset_test.py

Fixes https://github.com/fonttools/fonttools/issues/2965
In otTables.py we have a custom implementation of ClipList.postRead where we build a `clips` dictionary of ClipBox records keyed by glyph name, ensuring each value is a distinct object (they may be shared for ranges of glyph IDs in the binary table):
https://github.com/fonttools/fonttools/blob/f73220816264fc383b8a75f2146e8d69e455d398/Lib/fontTools/ttLib/tables/otTables.py#L1325-L1332
We call `copy.copy(rec.ClipBox)`. If the TTFont was loaded lazily like the subsetter does by default (unless one passes --no-lazy), then the ClipBox record is only decompiled when any of its attribute is accessed (thanks to our magic `BaseTable.__getattr__`).
In python <= 3.10 we didn't need to do anything special and calling copy.copy on a lazy object …

copy OTTableReader before copying/pickling lazily loaded table

---

Tests/subset/subset_test.py

modify test so that a couple color glyphs share the same clipbox to trigger issue copying lazy objects 
https://github.com/fonttools/fonttools/pull/2968

reproducer for bug subsetting COLR.ClipList with shared clips #2965

---

Lib/fontTools/varLib/models.py

Perhaps I simply misread but it looks like we might be saying continue if `P ⊂ C` and `C ⊂ P` which could be directly written as P == C?
Spotted while reading models.py in hopes of learning something.

Odd check pattern

---

Lib/fontTools/ttLib/tables/sbixGlyph.py

Minimal example is when you extract TTX files (including sbix, with one or more glyphs using `ref`) and rebuild the TTF via `ttx` command.
```
...
File "/opt/homebrew/lib/python3.10/site-packages/fontTools/misc/xmlReader.py", line 155, in _endElementHandler
self.currentTable.fromXML(name, attrs, content, self.ttFont)
File "/opt/homebrew/lib/python3.10/site-packages/fontTools/ttLib/tables/_s_b_i_x.py", line 105, in fromXML
current_strike.fromXML(name, attrs, content, ttFont)
File "/opt/homebrew/lib/python3.10/site-packages/fontTools/ttLib/tables/sbixStrike.py", line 144, in fromXML
current_glyph.compile(ttFont)
File "/opt/homebrew/lib/python3.10/site-packages/fontTools/ttLib/tables/sbixGlyph.py", line 80, in compile
rawdata += struct.pack(">H", ttFont.getGlyphID(self.referenceGlyphName)) …
```

Ensure sbix's Glyph.referenceGlyphName is set

---

Lib/fontTools/pens/reverseContourPen.py
Tests/pens/reverseContourPen_test.py

In https://github.com/fonttools/fonttools/pull/2922, @behdad added an `outputImpliedClosingLine` parameter to the `ReverseContourPen`, plus a test that only expected a certain number of segments. 
I was looking at this again today, and got a little suspicious as I noticed the number of pen commands increases from _4_ in the default `outputImpliedClosingLine=False` case, to _6_ in the `outputImpliedClosingLine=True` case, whereas I would only expect it to increase only by +1, i.e. to _5_, in the latter case, given it no longer omits the closePath's closing line.
It turns out, with `outputImpliedClosingLine=True`, not only the implied closing line is emitted, but also an additional, duplicate lineTo right after moveTo is emitted, which I belive is incorrect.
Here I first push the failing …

reverseContourPen_test: check outputImpliedClosingLine works as expected

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

The conditions in the subsetter were so that re-computing the xAvgCharWidth would only happen when also pruning Unicode ranges, while the two are not connected. This makes the two options independent from one another.

[subset] Compute xAvgCharWidth even when --no-prune-unicode-ranges is given

---

Lib/fontTools/ttLib/tables/O_S_2f_2.py

The code was copied from ufo2ft. It includes an additional guard against a zero division error that seems to not have been a problem in fontTools before?

`OS/2.xAvgCharWidth`: Guard against a ZeroDivisionError

---

Lib/fontTools/cu2qu/cu2qu.py
Lib/fontTools/misc/bezierTools.py
Lib/fontTools/misc/symfont.py
Lib/fontTools/pens/momentsPen.py
Lib/fontTools/qu2cu/qu2cu.py
Lib/fontTools/varLib/iup.py

It's possible sometimes that `import cython` does _not_ fail but then attempting to get `cython.compiled` raises `AttributeError` exception. It actually happened in our internal production environment... (still unclear as to the root cause).
So here in this PR, to check that the cython library is correctly installed I also catch AttributeError raised when the `compiled` variable is not there (even though it _must_ be there for the 'real' cython, but sometimes a 'pretend' one sneaks in, probably because sys.path has been messed with).
somewhat similar issue to https://github.com/pydantic/pydantic/pull/573 and https://github.com/ipython/ipython/issues/13294

prevent cython.compiled raise AttributeError if cython not properly installed

---

Lib/fontTools/mtiLib/__init__.py
Tests/mtiLib/data/featurename-backward.ttx.GSUB
Tests/mtiLib/data/featurename-forward.ttx.GSUB
Tests/mtiLib/data/lookupnames-backward.ttx.GSUB
Tests/mtiLib/data/lookupnames-forward.ttx.GSUB
Tests/mtiLib/data/mixed-toplevels.ttx.GSUB
Tests/mtiLib/data/mti/chained-glyph.ttx.GPOS
Tests/mtiLib/data/mti/chained-glyph.ttx.GSUB
Tests/mtiLib/data/mti/chainedclass.ttx.GSUB
Tests/mtiLib/data/mti/chainedcoverage.ttx.GSUB
Tests/mtiLib/data/mti/gposcursive.ttx.GPOS
Tests/mtiLib/data/mti/gposkernset.ttx.GPOS
Tests/mtiLib/data/mti/gposmarktobase.ttx.GPOS
Tests/mtiLib/data/mti/gpospairclass.ttx.GPOS
Tests/mtiLib/data/mti/gpospairglyph.ttx.GPOS
Tests/mtiLib/data/mti/gpossingle.ttx.GPOS
Tests/mtiLib/data/mti/gsubalternate.ttx.GSUB
Tests/mtiLib/data/mti/gsubligature.ttx.GSUB
Tests/mtiLib/data/mti/gsubmultiple.ttx.GSUB
Tests/mtiLib/data/mti/gsubreversechanined.ttx.GSUB
Tests/mtiLib/data/mti/gsubsingle.ttx.GSUB
Tests/mtiLib/data/mti/mark-to-ligature.ttx.GPOS

This stores the original lookup name in the `Debg` table when building MTI feature files. This allows the fonts to be debugged used Crowbar or other debuggers, and more sensibly decompiled to FEA:
Before:
```
lookup ChainedContextualGSUB7 {
lookupflag 0;
;
sub [katelu gatelu tthatelu ratelu shatelu] tasubscripttelu' lookup SingleSubstitution8;
sub @class2 tasubscripttelu' lookup SingleSubstitution9;
sub ssatelu tasubscripttelu' lookup SingleSubstitution19;
sub [katelu gatelu tthatelu ratelu shatelu] @class3 tasubscripttelu' lookup SingleSubstitution8;
sub @class2 @class3 tasubscripttelu' lookup SingleSubstitution9;
sub ssatelu @class3 tasubscripttelu' lookup SingleSubstitution19;
sub [katelu gatelu tthatelu ratelu shatelu] @class3 ailengthmarktelu tasubscripttelu' lookup …
```

[mtiLib] Add debug info

---

Lib/fontTools/mtiLib/__init__.py
Tests/mtiLib/mti_test.py

[We do the same for feaLib.builder ](https://github.com/fonttools/fonttools/blob/501353f3df2de69a126587da22cb0c6fb1db5acc/Lib/fontTools/feaLib/builder.py#L239-L240) to decide whether to build a Debg table or not: i.e. we check if FONTTOOLS_LOOKUP_DEBUGGING environment variable is defined and if so we go on to build one, otherwise we don't.
Fixes https://github.com/fonttools/fonttools/pull/3018

[mtiLib] only build `Debg` table if FONTTOOLS_LOOKUP_DEBUGGING env var is set

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/TestNoOverwriteSTAT.designspace
Tests/varLib/data/master_no_overwrite_stat/Test-CondensedBlack.ttx
Tests/varLib/data/master_no_overwrite_stat/Test-CondensedThin.ttx
Tests/varLib/data/master_no_overwrite_stat/Test-ExtendedBlack.ttx
Tests/varLib/data/master_no_overwrite_stat/Test-ExtendedThin.ttx
Tests/varLib/varLib_test.py

when master UFOs contain STAT table definition inside features.fea, varLib should not overwrite that with its own (potentially incomplete) STAT but keep whatever is there (587b0fbf115dea2302e86c81aacbf245621ea32d).
This fixes https://github.com/googlefonts/fontmake/issues/985 and https://github.com/googlefonts/ufo2ft/issues/723
/cc @kontur 
Also while I am at, I changed fonttools varLib CLI to call the new `build_many` API which supports DesignSpace v5 with multiple variable fonts within the same doc (#2659).

[varLib] Don't overwrite pre-existing STAT

---

Lib/fontTools/ttLib/ttFont.py
Tests/ttLib/ttFont_test.py

Fixes https://github.com/fonttools/fonttools/issues/3030

ttFont.getGlyphID should raise KeyError on missing glyphs

---

Lib/fontTools/misc/arrayTools.py
Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/ttLib/tables/otTraverse.py
Tests/ttLib/tables/C_O_L_R_test.py
Tests/ttLib/tables/data/COLRv1-clip-boxes-cff.ttx
Tests/ttLib/tables/data/COLRv1-clip-boxes-glyf.ttx
Tests/ttLib/tables/data/COLRv1-clip-boxes-q1-expected.ttx
Tests/ttLib/tables/data/COLRv1-clip-boxes-q10-expected.ttx
Tests/ttLib/tables/data/COLRv1-clip-boxes-q100-expected.ttx

ClipBoxes are optional in COLRv1 but can make rendering more efficient. Currently colorLib.builder.buildCOLR takes an optional clipBoxes parameter with user-defined clipBoxes (nanoemoji computes those upfront and provides them to colorLib). Other clients like glyphsLib don't compute the clipBoxes for us, so COLRv1 fonts built from fontmake via glyphsLib have no clip boxes.
This adds a method so one can ask fonttools to compute them, taking into account various paint transforms.
For example one can do:
```python
from fontTools.ttLib import TTFont
font = TTFont("path/to/input/font.ttf")
font["COLR"].table.computeClipBoxes(font.getGlyphSet(), quantization=100)
font.save("path/to/output/font.ttf")
```
This currently only works for static, non variable COLRv1 tables, which is OK, since for …

[COLRv1] Add method to automatically compute ClipBoxes, w/ optional quantization

---

Doc/source/index.rst

Just a small PR to keep the docs up-to-date following [the change to require Python 3.8](https://github.com/fonttools/fonttools/blob/c87bcde/NEWS.rst#4390-released-2023-03-06) :)

[docs] Bump minimum Python version in docs, as 3.8 is now required

---

Lib/fontTools/ttLib/tables/ttProgram.py

Formatting the whole codebase with black pretty much destroyed the inline docs for TrueType programs. This PR reverts the change and prevents reformatting of the affected lines.

Revert black formatting of inline instruction docs

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

Closes https://github.com/fonttools/fonttools/issues/3040.

Conditionset: consult avar to normalize values

---

Lib/fontTools/ufoLib/errors.py
Lib/fontTools/ufoLib/glifLib.py
Tests/ufoLib/glifLib_test.py

Hello!
This PR abstracts across XML library exceptions with glifLib errors when parsing glyphs, which allows dependent projects to catch syntax errors without requiring logic to account for which XML library fonttools is using internally (e.g. for implementing fonttools/ufoLib2#264).
The PR also also adds tests to ensure that the exception we expose remains stable across future releases.
* `glifLib.readGlyphFromString()`
* `glifLib.GlyphSet.readGlyph()`
If we wanted to abstract over lxml/xml exceptions more broadly, we could catch them in `etree.py` and wrap them with a fonttools-specific XmlParsingError; this would also have the cost of maintaining wrapper functions (e.g. for `etree.fromstring()`) where there currently are none.

[glifLib] Wrap XML library exceptions with glifLib types when parsing glifs

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/feaLib/variableScalar.py
Tests/feaLib/builder_test.py

Follow-up to #3042.
1. Guard against missing `avar` entries when normalizing condition set locations
2. Apply `avar` also to variable locations
Closes #3040.

Apply `avar` also to variable locations

---

Lib/fontTools/ttLib/ttFont.py
Tests/ttLib/ttFont_test.py

Intended to fix https://github.com/fonttools/fonttools/issues/3052
I first push a reproducer which I expect to fail on Python < 3.11

fix SpooledTemporaryFile has no seekable method

---

Lib/fontTools/ttLib/ttFont.py

This PR fixes https://github.com/fonttools/fonttools/issues/3095 .
This exception was being caused by the use of a filename template string `fileNameTemplate = path + ".%s" + ext` that is then used with the % operator to fill in the split table type ` tablePath = fileNameTemplate % tagToIdentifier(tag)`
This PR changes the code to just create the `tablePath` string without using a `fileNameTemplate` string, so filenames containing `%` are no longer an issue.

fix ttx split tables option to work on filenames containing '%' fixes #3095

---

Lib/fontTools/varLib/featureVars.py
Tests/varLib/data/test_results/FeatureVars_rclt.ttx

Fixes https://github.com/fonttools/fonttools/issues/3097
One test needs updated expectations.

[featureVars] Process lookups for features other than rvrn last

---

Lib/fontTools/feaLib/parser.py
Tests/feaLib/parser_test.py

This how GlyphsApp handles it and how it is handled in single substitution.

feaLib: handle singleton class as a single glyph in multiple subst

---

Lib/fontTools/feaLib/ast.py
Tests/feaLib/data/GSUB_2.fea
Tests/feaLib/data/GSUB_2.ttx

This is a follow-up to #3103. If the same glyph appears multiple times in the input class, only the first copy’s rule can ever be applied, so the rest can be skipped. Without this change, if the rule is in a chaining substitution lookup, `Builder.add_multiple_subst` creates duplicate multiple substitution lookups.

feaLib: Dedupe multiple substitutions with classes

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/fontBuilder_test.py

fontBuilder: add glyphDataFormat=0; error with accidentally cubic outlines

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/data/variable_scalar_valuerecord.fea
Tests/feaLib/data/variable_scalar_valuerecord.ttx

If a variable scalar does not vary (i.e. all values are the same), we can simplify it and use a simple value instead. Arguably users shouldn’t be using variable scalar in this case, but it helps when the feature code is auto generated so each feaLib users doesn’t have to do the check done here themselves.

[feaLib] Simplify variable scalars that don’t vary

---

Lib/fontTools/otlLib/builder.py

The old code used `mark` instead of `glyph` so it would either raise an `UnboundLocalError` or produce an error message with the wrong glyph name.

[otlLib] Fix error message in `MarkBasePosBuilder`

---

Lib/fontTools/pens/ttGlyphPen.py
Tests/pens/ttGlyphPen_test.py

Fixes https://github.com/googlefonts/fontmake/issues/1001

TTGlyphPen: do not error with empty contours, simply ignore them

---

Lib/fontTools/pens/ttGlyphPen.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

we have a drop_implied_oncurves function inside ttGlyphPen, but that being a pen only works for a single glyph.
Thus I modified this to work on one or more (interpolatable) glyphs and to only prune oncurve points that are impliable for _all_ of the input glyphs, such that the modified glyphs maintain interpolability.
I also moved it to the glyf table module. I'd like to use this in ufo2ft to massage the glyphs of master TTFs before it calls varLib.build.
fontc does a similarly eager pruning of oncurve points and I'd like to have this done (optionally) in fontmake-py as well.

implied oncurve points for interpolatable glyphs

---

Lib/fontTools/pens/ttGlyphPen.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Lib/fontTools/varLib/__init__.py
Tests/ttLib/tables/_g_l_y_f_test.py
Tests/varLib/data/DropOnCurves.designspace
Tests/varLib/data/master_ttx_drop_oncurves/TestFamily-Master1.ttx
Tests/varLib/data/master_ttx_drop_oncurves/TestFamily-Master2.ttx
Tests/varLib/data/test_results/DropOnCurves.ttx
Tests/varLib/varLib_test.py

Follow up from #3146 
I decided to add this to varLib directly instead of ufo2ft, since the method for dropping the oncurve points was already here.
The option is False by default.
Don't expect much savings, mostly in the hundred of bytes for normal fonts so usually not worth rebuilding yours.
I was thinking of adding a tolerance to increase the chances of pruning oncurves (right now it has to be exactly in the middle, we use math.isclose). But maybe another time, I just need this for testing purposes (diffing against fontc)

[varlib] add --drop-implied-oncurves option

---

Lib/fontTools/subset/__init__.py

Those have confused Windows users before.
Fixes https://github.com/fonttools/fonttools/issues/3149

[subset] Remove quotation marks from command-line samples

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

I found a bug in dropImpliedOnCurvePoints whereby we don't correctly drop impliable oncurve points if this occurs on the first point of the second contour.. because we forgot to update the contour start = last + 1...

fix a bug in dropImpliedOnCurvePoints

---

Lib/fontTools/misc/vector.py
Lib/fontTools/pens/ttGlyphPen.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/varLib/instancer/instancer_test.py

Currently (#3146) we only compute implied oncurves after coordinates have already been rounded. We should compute if an oncurve point is in between previous/next off-curve points both before they get rounded and afterwards, and accept it either way.
The TTGlyphPens need to allow leaving the coordinates un-rounded, so that ufo2ft can set `round=noRound` when building master interpolatable TTFs; then it can send these to varLib.build and have the impied points dropped (when impliable for all masters).

Drop impliable oncurves either before or after rounding

---

Lib/fontTools/fontBuilder.py
Tests/fontBuilder/data/test_var.otf.ttx
Tests/fontBuilder/fontBuilder_test.py

Fixes #3182.
The avar-2 bit is untested, but I did add a minimal FontBuilder avar test that would have caught #3182.

[FontBuilder] Update setupAvar() to also support avar-2, fixing _add_avar() call site

---

Lib/fontTools/fontBuilder.py

The `hidden` flag was not set on the fvar axis, when using FontBuilder's `setupFvar()` method. This PR fixes that.

[FontBuilder] Propagate the 'hidden' flag to the fvar Axis instance

---

Lib/fontTools/fontBuilder.py
Lib/fontTools/ttLib/tables/O_S_2f_2.py
Tests/fontBuilder/fontBuilder_test.py

Convert panoseDefault to namespace object

---

Lib/fontTools/unicodedata/__init__.py

Without explicit annotation, some type checkers inferred that the type of the 'default' argument could only be `type[KeyError]`. This was the case in unicodedata_test.py, where pyright disallowed `"LTR"`. This PR adds annotations to avoid this, fixing the issue in the test, and in external code depending on the API.
Some explicit conversions of literals to `str` were removed, as Python 3 no longer requires them and in one case they would have required a less specific return type to be used.
* Some of the other functions in this file have the same semantics and suffer from the same type error, and so this fix could also be extended to them as usage requires.
* `HorizDirection` and `T` may become importable; do we want to avoid this for either?

Fix typing of script_horizontal_direction()

---

Lib/fontTools/varLib/merger.py
Tests/varLib/merger_test.py

Implement merging of sparse CursivePos.
Part of https://github.com/fonttools/fonttools/issues/3168

[varLib.merger] Support sparse CursivePos

---

Lib/fontTools/fontBuilder.py

Bug introduced in https://github.com/fonttools/fonttools/commit/a421f9045a4d1e130daece08350ed7c1ed300ee7#diff-c01f84c2ac99ae2b60f071d4a38ff88c2653d27f19e62e11bef3dc7fe7f68925R352
Causes created date to be set to 0 instead of the current timestamp.

Fix wrong created date in fontBuilder

---

Lib/fontTools/varLib/instancer/featureVars.py
Tests/varLib/instancer/instancer_test.py

Fixes https://github.com/fonttools/fonttools/issues/3211

[instancer] Allow null ConditionSet

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/_n_a_m_e.py

[subset] Revert use of NameVisitor to fix speed regression

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/_n_a_m_e.py

https://github.com/fonttools/fonttools/issues/3213#issuecomment-1644158826

Faster name visitor subset

---

Doc/source/designspaceLib/xml.rst

I'm not really sure how the docs work, so this might not be right? lmk :)
closes #3224

[designspace] Clarify in docs that <lib> is plist

---

Lib/fontTools/t1Lib/__init__.py

Fix several issues exposed by the fonts posted in #3238. This fixes #3238.
- fix when /Private follows /CharStrings instead of vice versa as is more common
- fix expected ND and PD values
- handle the case where lenIV is not 4 (writing)
- write /Subrs properly, not just the "standard 5"

[t1Lib] Fix several Type 1 issues

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

I get warning from _makeMacName() because it does not have a TTFont, but the font is there, just not passed from addMultilingualName() -> findMultilingualName() -> _makeMacName().

[ttLib] Fix warning when calling addMultilingualName() with "ar" name

---

Lib/fontTools/varLib/varStore.py
Tests/varLib/data/test_results/Build.ttx
Tests/varLib/data/test_results/BuildMain.ttx
Tests/varLib/data/test_results/SparseCFF2-VF.ttx
Tests/varLib/data/test_results/SparseMasters.ttx
Tests/varLib/data/test_results/TestVVAR.ttx
Tests/varLib/varStore_test.py

It should be after each vardata optimization. 
Here's a testcase, I used this command `fonttools varLib.instancer --no-overlap-flag --no-recalc-timestamp --no-optimize --output=ft.ttf test/subset/data/fonts/NotoSans-VF.abc.ttf wght=200:600 wdth=80:90 CTGR=20:60`
File used is this: https://github.com/harfbuzz/harfbuzz/blob/main/test/subset/data/fonts/NotoSans-VF.abc.ttf
And generated MVAR table is like below:
<VarStore Format="1">
<Format value="1"/>
<VarRegionList>
<Region index="0">
<VarData index="0">
<NumShorts value="0"/>
<VarRegionIndex index="0" value="0"/>
<VarRegionIndex index="1" value="3"/>
<Item index="0" value="[-7, 6]"/>
<Item index="1" value="[-4, 4]"/>
</VarData>
</VarStore>
2 regions indexed at 1 and 2 are not used and not pruned. 
This PR will fix it.

fix the order of prune_unused_regions

---

.github/workflows/test.yml
requirements.txt
setup.py
tox.ini

The [third Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc3-released-honestly-the-final-release-candidate-i-swear/34093?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
Python 3.12.0 final is due out on Monday: [2023-10-02](https://peps.python.org/pep-0693/).
See also https://dev.to/hugovk/help-test-python-312-beta-1508/

Add support for Python 3.12

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py

I'm forever getting errors like this:
```
fontmake: Error: In 'master_ufo/Foo.designspace': Generating fonts from Designspace failed: 'j'
```
which are not informative. This is slightly more informative:
```
fontmake: Error: In 'master_ufo/Foo.designspace': Generating fonts from Designspace failed:
master_ufo/Foo-Regular-18pt.ufo/features.fea:1865:5: Could not find glyph 'j' in font
```

Better OTL builder errors

---

Lib/fontTools/misc/bezierTools.py
Tests/misc/bezierTools_test.py

Fixes https://github.com/fonttools/fonttools/issues/3287

bezierTools: fix incorrectly typed cython local variable

---

Lib/fontTools/ttLib/tables/_h_h_e_a.py
Lib/fontTools/ttLib/tables/_v_h_e_a.py

I believe that was the spirit of this code, do have recalc() do nothing if the metrics tables are missing
Fixes https://github.com/fonttools/fonttools/issues/3289

Fix UnbouldLocalError and let {h,v}hea be no-op when no {v,h}mtx is present

---

Lib/fontTools/ttLib/tables/E_B_D_T_.py
README.rst

In the `E_B_D_T_` module, `_reverseBytes()` with `bytes` arguments longer than 1 lead to a recursive call from a loop. However, a loop over `bytes` produces `int`s, which have no `len()`, leading to a `TypeError`.
Fixed with `isinstance` as it appears the function is intended to be applicable to both `int` and `bytes` arguments.
Contributing guidelines suggest pull request authors should be listed in the README - let me know if I should add my name there, happy to do so but this is a kinda trivial edit.

Bug fix for `TypeError` in `_reverseBytes()` in module `E_B_D_T_`, currently breaks on `bytes` arguments longer than 1

---

Lib/fontTools/merge/tables.py
Lib/fontTools/misc/arrayTools.py
Lib/fontTools/ttLib/__main__.py
Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

Mostly around `recalcBounds`.
For Handjet font, this bring compile time down from 11s to 0.22s:
```
time ./fonttools ttLib Handjet.ttf -o out.ttf -tglyf
```
Brings down instancing speed for me from 23s down to 0.36s.
Part of fixing https://github.com/fonttools/fontbakery/discussions/4301

Faster `glyf` compile

---

Lib/fontTools/cffLib/specializer.py

Fixes https://github.com/fonttools/fonttools/issues/3311

Fix SyntaxWarning in Python 3.12

---

Lib/fontTools/subset/__init__.py

Similar to this commit: https://github.com/fonttools/fonttools/commit/1d0f3c27fcefa4f3265afc04eebf10360a0eed0c

[subset] fix another null-offset error in MarkLigPos

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/data/PairPosSubtable.ttx
Tests/feaLib/data/bug633.ttx
Tests/feaLib/data/spec5f_ii_3.ttx
Tests/feaLib/data/variable_bug2772.ttx
Tests/otlLib/builder_test.py

Fixes https://github.com/fonttools/fonttools/issues/3321
see https://github.com/fonttools/fonttools/blob/c3d876/Lib/fontTools/misc/classifyTools.py#L77
i.e. we want (large classes first, then lexicographic order on the glyphs); previously otlLib was sorting by the _reverse_ of (small classes first, then glyphs lexicographic order) -- effectively comparing the reverse of the glyph sets of classes of the same size.
note the ttx dump of previously built fonts may change but there won't be any functional changes.

[otlLib] make ClassDefBuilder class order match varLib.merger's

---

Lib/fontTools/subset/__init__.py
Lib/fontTools/ttLib/tables/O_S_2f_2.py
Tests/subset/data/NotoSansCJKjp-Regular.subset.ttx
Tests/subset/data/TestContextSubstFormat3.ttx
Tests/ttLib/tables/O_S_2f_2_test.py

Based on https://github.com/googlefonts/ufo2ft/blob/efb4658890ba645292a9c6bc055c91afe225c4a1/Lib/ufo2ft/util.py#L357.

Support calculating OS/2.ulCodePageRange* bits

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/variable_mark_anchor.fea
Tests/feaLib/data/variable_mark_anchor.ttx

Calling `makeOpenTypeAnchor` modifies the anchor and drops its variable components; as mark anchors are reused, they need to be cloned before building.

Clone variable mark anchor before building

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/data/PartialInstancerTest-VF.ttx
Tests/varLib/instancer/instancer_test.py

Fixes #3297 
note that the hhea vertical metrics will _not_ be updated if they were not already in sync with OS/2 before the instancing

[instancer] Ensure hhea vertical metrics stay in sync with OS/2 after MVAR instancing

---

Lib/fontTools/varLib/interpolatable.py
Lib/fontTools/varLib/interpolatablePlot.py
Tests/varLib/interpolatable_test.py

Using names to refer to masters is weird. Return the index and the user can look up the name.
This changes the API in two ways:
- `test` and `test_gen` do not accept a `names` parameter anymore. If needed I can put it back there unused.
- `master`, `master1`, `master2` in the problem reports are now indices, not names. If this is undesirable, I can add separate `master_idx`, `master1_idx`, `master2_idx` instead. Maybe that's better.

[interpolatable] Return master indices in addition to master names

---

Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ttLib/ttGlyphSet.py
Lib/fontTools/varLib/interpolatable.py

Avoids unnecessary work in the interpolator.
What do you think?

[ttGlyphSet] Add option to not recalculate glyf bounds

---

Lib/fontTools/varLib/featureVars.py
Tests/varLib/featureVars_test.py

Currently, addFeatureVariationsRaw always deletes existing GSUB.FeatureVariations and overwrites them with the newly built records.
https://github.com/fonttools/fonttools/blob/0b05cec0a345fc9d912170f1fa811215ae54579c/Lib/fontTools/varLib/featureVars.py#L352
It doesn't have to, though. If the features for which we are adding feature variations are not already "variable", we can simply append the new DS-rules-generated records to the existing FeatureVariations list.
We can raise an error if the existing FeatureVariations already reference the same feature tags used by the DS rules, as that could generate ambiguity/undefined logic.

[featureVars] don't overwrite FeatureVariations, append new records

---

Lib/fontTools/merge/__init__.py
Lib/fontTools/merge/options.py

- proper usage help
- print key names during merging when `--verbose` (so that failing fields of tables can be identified)
New options:
- `--input-file` to read file names from file instead of command line
- `--output-file` moved from `main` to `Options`
- `--import-file` to import TTX after merge

Merge tool improvements

---

Lib/fontTools/varLib/featureVars.py
Tests/feaLib/builder_test.py
Tests/varLib/featureVars_test.py

If a FeatureVariationRecord with the same ConditionTable exists re-use it and append FeatureTableSubstitutionRecord’s.
Without this, in the following feature code only the first lookup will be applied since there will be two FeatureVariationRecord with the same ConditionTable, so the first will be matched and the other will be skipped:
conditionset test {
wght 600 1000;
wdth 150 200;
} test;
variation ccmp test {
sub e by a;
} ccmp;
variation rlig test {
sub b by c;
} rlig;
With this change only one FeatureVariationRecord will be created with two FeatureTableSubstitutionRecord’s.

[featureVars] Re-use FeatureVariationRecord's when possible

---

.github/workflows/wheels.yml

https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
This caused the PyPI upload job to fail earlier. Hopefully this should fix it.

[CI] adapt to new upload/download-artifact changes 

---

Lib/fontTools/feaLib/lexer.py
Lib/fontTools/feaLib/parser.py
Tests/feaLib/lexer_test.py
Tests/feaLib/parser_test.py

These were implemented to follow FEA spec, but makeotf does not seem to have a length limit on class names, and the glyph names limit (if it still has it, I didn’t check) seems like an implementation detail we don’t have to enforce.
Fixes https://github.com/googlefonts/ufo2ft/issues/588
See also https://github.com/googlefonts/ufo2ft/pull/811#discussion_r1461667058

feaLib: Drop glyph and class names length limit

---

Lib/fontTools/pens/hashPointPen.py
Lib/fontTools/pens/recordingPen.py
Lib/fontTools/pens/roundingPen.py
Tests/pens/roundingPen_test.py

From discussion in #3422:
Add option to supply a function to RoundingPen and RoundingPointPen which is used to round the scale components of transforms.
The scenario to use this to make sure scale values conform to F2Dot14, as used in TrueType composite glyphs, is described in the docstring of the related HashPointPen.

Add transformRoundFunc parameter to RoundingPens

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Tests/feaLib/data/spec8a.ttx

Fixes https://github.com/fonttools/fonttools/issues/2937 and https://github.com/fonttools/fonttools/issues/836
alternate glyphs are now sorted in the order that the source features are named in the aalt definition, as the FEA spec says, and not by glyph order.

[feaLib] fix ordering of alternates in aalt lookups

---

Doc/source/designspaceLib/xml.rst

String values were using <integer> tag.

Doc: Fix xml example of public.fontInfo

---

Lib/fontTools/cu2qu/ufo.py
Tests/cu2qu/ufo_test.py

In ufo2ft preProcessor, we need to know which specific glyphs were actually modified (converted to quadratic), in order to do other things while processing filters, not simply whether the fonts were modified as a whole; thus, here I changed `cu2qu.ufo.fonts_to_quadratic` to return the set of modified glyph names instead of just True/False.
The change is backward compatible because client code that checks whether the returned value was True/False will continue to work since `bool(set)` is True for non-empty set, False for empty ones.

[cu2qu/ufo] return set of modified glyph names from fonts_to_quadratic

---

Lib/fontTools/ttLib/tables/otConverters.py

Some OT tables rely on "aux" fields which are conditions written as strings; a classic example is the Device field which has the condition "DeltaFormat in (1,2,3)". This is currently stored as a string in the Convertor object, and is `eval`ed for each Device table it decompiles.
`eval` is very slow. You can get a small speedup - quite a large speedup for fonts with lots of Device/VariationIndex tables - by compiling the string and `eval`ing the compiled version later.

Optimization on load

---

Doc/source/index.rst

cut down a few lines, modified some

slight index.rst improvement

---

Lib/fontTools/misc/sstruct.py
Lib/fontTools/ttLib/tables/E_B_L_C_.py
Lib/fontTools/ttLib/tables/_m_a_x_p.py

Currently if you give a field value - any field value - a number it isn't expecting for whatever reason (float when uint is expected, number out of range, etc.), you get this:
```
font["OS/2"].usWinDescent = -600
font.save("foo.ttf")
...
File "/opt/homebrew/lib/python3.11/site-packages/fontTools/ttLib/tables/O_S_2f_2.py", line 173, in compile
data = sstruct.pack(OS2_format_2, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/lib/python3.11/site-packages/fontTools/misc/sstruct.py", line 75, in pack
data = struct.pack(*(formatstring,) + tuple(elements))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: argument out of range
```
Which at least leads you to the right table, but nothing more than that. With this PR, you get:
```
data = sstruct.pack(OS2_format_2, self) …
```

Better failure mode for sstruct

---

Lib/fontTools/feaLib/variableScalar.py

VariableScalar's value_at_location() method is untested and unused, but I find it useful (if only for playing and testing) and found that it's broken. I fixed it, but that makes an assumption about the intended call signature: I assume the intention was to feed it a location dict in user coordinates.

[feaLib.variableScalar] fix value_at_location() method

---

Lib/fontTools/ttx.py
Tests/ttx/ttx_test.py

Fixes https://github.com/fonttools/fonttools/issues/3507

[ttx] use GNU-style getopt to intermix options and positional arguments

---

Lib/fontTools/subset/__init__.py
Tests/subset/subset_test.py

This option should affect only pre-defined name IDs, user name IDs should be pruned when nit used, as usual.
Fixes https://github.com/fonttools/fonttools/issues/3508

[subset] Prune unused user name IDs even with --name-IDs='*'

---

Lib/fontTools/cffLib/CFFToCFF2.py
Lib/fontTools/cffLib/transforms.py

The transforms.py changes are for them to work with fonts without font.charset. I'm not sure how we didn't catch these before.
Ideally needs test.
Fixes https://github.com/fonttools/fonttools/issues/3511

[CFFToCFF2] Remove unused subroutines if necessary

---

Lib/fontTools/feaLib/lexer.py

Fix https://github.com/googlefonts/fontmake/issues/972

Allow UTF-8 with BOM for features.fea

---

Lib/fontTools/pens/svgPathPen.py
NEWS.rst

This reverts commit 42d6b6b4fedf51dd741d3134da74df04339335b4.
As discussed with @anthrotype, this changed default behavior.

Revert "[svgPen] Write two digits after decimal by default"

---

Lib/fontTools/varLib/instancer/__init__.py

All limits are tuples now when not None. The old logic was broken and for the following command:
$ fonttools varLib.instancer  AdobeVFPrototype.otf CNTR=50:80 wght=900
it was saving the output with the name suffix `-instance`, whereas it's clearly a partial instantiation. This fixes that.

[instancer] Fix output filename decision-making

---

README.rst
dev-requirements.txt
setup.py

it happened a few times that one updates the NEWS.rst and doesn't check that it is still valid reStructuredText, only to find out later on while publishing the wheels that the `long_description` contains syntax error and would display as plain text on PyPI.
This ensures that we run the `readme_renderer` to render the .rst and check for any syntax errors _before_ it proceeds to bump the version in the same `python setup.py release` command.
This is the same thing that `twine check` does when verifying the metadata of a package.
I can't easily add a test for this, but rest assured that I have tried locally a few times and it works.
The release workflow does not change. The only gotcha is that it's preferable to install bump2version and readme_renderer in the venv before running `setup.py …

Check for reStructuredText syntax errors in README+NEWS while running release command

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/contextual_inline_multi_sub_format_2.fea
Tests/feaLib/data/contextual_inline_multi_sub_format_2.ttx

We already attempt to reuse a existing anonymous lookup for inline _single_ substitutions in chained contextual lookups, when additional rules don't conflict (either they replace different glyphs or are duplicated)
https://github.com/fonttools/fonttools/blob/93f724447d4a4baace46b68510af66c14ea73127/Lib/fontTools/feaLib/builder.py#L1361
This PR extends this approach for multiple substitutions as well.
Fixes https://github.com/fonttools/fonttools/issues/3551

[feaLib] try reuse existing inline chained multiple subst lookups when possible

---

Lib/fontTools/otlLib/maxContextCalc.py
Tests/otlLib/maxContextCalc_test.py

This PR fixes `maxCtxContextualRule`, which was returning too high results for reverse chaining contextual single substitutions. Its `GlyphCount` field is the number of glyphs in the coverage table, not the number of glyphs in the input sequence. The input sequence is always 1 glyph long because it is a reverse chaining contextual _single_ substitution.

Fix OS/2.usMaxContext for reverse GSUB rules

---

Lib/fontTools/misc/visitor.py
Tests/misc/visitor_test.py

With this PR, a visitor object will look for registered visitors on an objects superclasses as well as on the object itself, fixes #3580.

Visitor inheritance

---

Lib/fontTools/merge/__init__.py

Mostly fixing the explanation of how glyphs get renamed (they get `.n` added, not `#n`), but couldn't resist a couple of other minor fixups too.

Minor fixes to documentation for merge

---

Lib/fontTools/varLib/models.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/variable_mark_anchor.ttx
Tests/feaLib/data/variable_scalar_anchor.ttx
Tests/feaLib/data/variable_scalar_valuerecord.ttx
Tests/varLib/data/test_results/BuildAvar2.ttx

See:
https://github.com/fonttools/fonttools/pull/2846#issuecomment-2267750076
I *think* this is an improvement, and no one should have been relying on the broken existing behavior.
We do have multiple tests failing because of it. I can go through them and confirm in each case that the new tent is preferred. But I welcome feedback.
Docs need updating.
Tests need fixing.

[varLib.models] By default, assume OpenType-like normalized space

---

Tests/otlLib/optimize_test.py

I typically run tests like:
$ python setup.py build_ext -i && PYTHONPATH=Lib pytest
Previously, this particular test and only this, required that a `pip install -e .` has had happened. Not anymore.

[Tests] Do not require fonttools command to be available

---

Doc/docs-requirements.txt
Doc/source/colorLib/index.rst
Doc/source/conf.py
Doc/source/designspaceLib/xml.rst
Doc/source/developer.rst
Doc/source/index.rst
Doc/source/ttLib/ttFont.rst

These are pretty minor, but need to come before some reorg work on the autodoc configuration.
It does make a change to docs-requirements.txt, as described in #3606, which I think is necessary for the time being. I can only debug the output locally as long as the RTD theme is broken. I think a fix to the theme package is imminent, though.

Small docs cleanups

---

Tests/subset/data/Andika-Regular.subset.ttx
Tests/subset/subset_test.py

If we subset this test font (a subset of Google Fonts' Andika-Regular.ttf) and request to keep 'cv43', only the FirstParaUILabelNameID (324) is currently kept, the other two (325 amd 326) get incorectly dropped. All referenced nameIDs should be kept.
This will be fixed with https://github.com/fonttools/fonttools/pull/3617
```
>       assert nameIDs == keepNameIDs
E       assert {0, 1, 2, 3, 4, 5, 6, 321, 322, 323, 324} == {0, 1, 2, 3, 4, 5, 6, 321, 322, 323, 324, 325, 326}
E         Extra items in the right set:
E         325
E         326
E         Full diff:
E         - {0, 1, 2, 3, 4, 5, 6, 321, 322, 323, 324, 325, 326}
E         ?                                         ----------
E         + {0, 1, 2, 3, 4, 5, 6, 321, 322, 323, 324}
```

subset_test: add failing test to reproduce issue #3616

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py

Fixes https://github.com/fonttools/fonttools/issues/3616

NameRecordVisitor: include whole sequence of character variants' UI labels, not just the first

---

Doc/source/conf.py
Lib/fontTools/designspaceLib/__init__.py
Lib/fontTools/ufoLib/__init__.py

This changes the Sphnix config to keep the napoleon and autodoc extensions from interfering with each other, and it moves the module docstrings for designspaceLib and ufoLib (in the respective `__init__.py`s) to the start of the file. That's more in line with PEP257, but more practically, autodoc will not see those docstrings unless they are absolutely first.

Docs: fix Sphinx builds

---

Lib/fontTools/subset/__init__.py

Two small things I noticed in the docs:
1. Remove `./` from example (32617523eebf6723c24bbd0126bbc4f7df181e4d)
2. Add note to escape the `?` from arguments (41854749d7f2eedf860b9ec082aca3565be641ea)

Small tweaks to pyftsubset documentation

---

Lib/fontTools/varLib/instancer/__init__.py
Tests/varLib/instancer/data/3634-VF.ttx
Tests/varLib/instancer/data/test_results/3634-VF-partial.ttx
Tests/varLib/instancer/instancer_test.py

Fixes #3634
The issue above emerges when assumptions are made about point equality based on unrounded points, whereas the comparisons that happen at runtime will be based on rounded points. In particular, unrounded points are present when `varLib.instancer` calculates and applies deltas to the font's original coordinates to effect a new default position, and so this PR rounds immediately after this happens to ensure that the coordinates match those in the final `glyf` table.
---

Fix visual artefacts with partial L2 instancing

---

Lib/fontTools/pens/freetypePen.py
Lib/fontTools/pens/pointInsidePen.py
Lib/fontTools/pens/recordingPen.py
Lib/fontTools/pens/svgPathPen.py
Lib/fontTools/pens/transformPen.py
Lib/fontTools/svgLib/path/__init__.py
Lib/fontTools/svgLib/path/parser.py
Lib/fontTools/ttLib/sfnt.py
Lib/fontTools/ttLib/ttFont.py
Lib/fontTools/ufoLib/__init__.py
Lib/fontTools/varLib/__init__.py
Lib/fontTools/varLib/cff.py
Lib/fontTools/varLib/instancer/__init__.py
Lib/fontTools/varLib/mutator.py
Lib/fontTools/voltLib/voltToFea.py

Fixes several code-block and `Example::` stanzas, plus a couple of bullet lists, in various docstrings.

Docs: cleanup code blocks

---

Lib/fontTools/subset/__init__.py

In Python 3.12, it's a syntax error to use invalid escape sequences. `\?` is not a valid escape sequence but is used in a docs variable in `subset/__init__.py`. This PR escapes the backslash.

Escape `\` in subset docs

---

Lib/fontTools/varLib/interpolatableTestContourOrder.py

Found while porting. We first compare the reversed control vectors, and next we are supposed to compare the reversed Green vectors, but too much cut-and-paste means we test the control vectors a second time.

Fix cut-and-paste error

---

Lib/fontTools/ttLib/tables/TupleVariation.py
Lib/fontTools/ttLib/tables/_g_v_a_r.py
Tests/ttLib/tables/TupleVariation_test.py

This makes VARC+gvar fonts slightly larger but slightly faster. Slightly being about 20%. I think it's worth having the code in, since it makes no change to the font format, just how we encode things. I'll try to wire it up further.
Originally posted as https://github.com/fonttools/fonttools/pull/3650

[TupleVariation] Optimize for loading speed, not size

---

Lib/fontTools/ufoLib/glifLib.py
Tests/ufoLib/GLIF1_test.py
Tests/ufoLib/GLIF2_test.py

I created a UFO that erroneously had a `<unicode>` element without a `hex` attribute. Naturally instead of just fixing this in my own code, i poked about inside fonttools to work out how to improve the validation, run the tests, and blah blah blah.

Check unicode elements have required hex attribute

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/misc/xmlReader.py
Lib/fontTools/ufoLib/glifLib.py

Set `isfinal=1` in `Parse()` calls to ensure proper resource finalization after parsing.
[Python XML Parser Documentation](https://docs.python.org/3/library/pyexpat.html#xml.parsers.expat.xmlparser.Parse)

Set isfinal to true in XML parser for proper resource cleanup

---

Lib/fontTools/ttLib/reorderGlyphs.py
Tests/ttLib/reorderGlyphs_test.py

Fixes https://github.com/fonttools/fonttools/issues/3681
* Included logic to handle reordering of glyphs in CFF fonts by updating the `CharStrings` and `charset` properties.

[ttLib.reorderGlyphs] Update CFF table charstrings and charset

---

Lib/fontTools/cffLib/specializer.py
Tests/cffLib/specializer_test.py

The code was always merging at least two blends, which was causing stack-overflow with a test font of ours. Move the overflow check earlier to catch that.
Fixes https://github.com/fonttools/fonttools/issues/3676
No test. Unfortunately I won't have the time to figure out how to test this.

[CFF2] specializer fix stack overflow

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/cmap14_font1.no_uvs.ttx
Tests/subset/data/cmap14_font1.no_uvs_non_default.ttx
Tests/subset/data/cmap14_font1.ttx
Tests/subset/data/cmap14_font1.uvs.ttx
Tests/subset/data/cmap14_font1.uvs_non_default.ttx
Tests/subset/subset_test.py

cmap14 subsetting code was not considering variation selectors in the input unicode set when deciding which variant glyphs to keep. This updates subsetting to only keeps variant glyphs if their variation selector code point is in the input unicodes set.

[subset] consider variation selectors subsetting cmap14

---

Lib/fontTools/varLib/iup.py

See #3703.
In some cases we were seeing different output from iup depending on whether or not we were running cython code.
I've tracked this particular issue down to the line that is changed in this diff, and the change introduced in this diff does (locally, for me, on one machine with one architecture and one compiler) seem to suppress the problem.
However... it feels pretty bad??
I'm not sure how motivated I am to try and generate a proper minimal test case and try to get this fixed upstream. I guess I'm.. medium motivated? But at the very least it would be nice to figure out a more robust way to prevent this optimization from happening, and at the very _very_ least it would be nice to figure out away to test this.
The solution I was hoping for was some way to write some actual …

[varLib] "Fix" cython iup issue?

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py

When passing a parsed feature file that has variable anchors to addOpenTypeFeatures(), builder would modify the anchors in place and discard the variations, which break any subsequent use of the feature file.
I encountered this building a font that has variable cursing anchors with ufo2ft. The cursFeatureWriter would write the variable anchors, but then when kernFeatreWriter compiles the file to get GSUB closure, the variation would be dropped from the anchors, and later when when the feature data is compiled into the font, the anchors would be compiled without variations.

[feaLib] Don’t modify variable anchors in place

---

Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/contextual_inline_format_4.fea
Tests/feaLib/data/contextual_inline_format_4.ttx

With this patch we will now reuse lookups more frequently when a contextual lookup has inline ligature substitution rules.
- closes #3701

[feaLib] More efficient inline format 4 lookups

---

NEWS.rst

For context, https://googlefonts.github.io/fontc_crater/ is believed to benefit significantly from #3726

Update news to prepare for release

---

Lib/fontTools/misc/transform.py
Tests/misc/transform_test.py

This PR adds explicit type annotations to more of the `Transform` class and friends, to stop eager type checkers from implicitly assuming that we cannot pass `float`s to function arguments that have `int` or `None` defaults.
In addition, the PR contains a few other smaller fixes/tidies that were made while in the neighbourhood:
- Fix test obscured by overlapping function name
- Remove now-redundant inline `math` imports
- Add a few more type annotations, where there was low-hanging fruit
---
Ideally in the future we can explicitly type more of the `Transform` class's return values too, but we will need Python 3.11's `typing.Self` to represent its current behaviour exactly.

[transform] Fix typing, test, and tidy

---

Lib/fontTools/feaLib/ast.py

The current docstring suggests that both `.glyph` and `.replacement` should be **lists** of “glyph-containing objects”:
https://github.com/fonttools/fonttools/blob/ef07e3b2cc6987a35ba32d8dcbb79a435965ba3b/Lib/fontTools/feaLib/ast.py#L595-L604
But the `asFea()` implementation actually expects `.glyph` and `.replacement` to be “glyph-containing objects”, not nested in lists:
https://github.com/fonttools/fonttools/blob/ef07e3b2cc6987a35ba32d8dcbb79a435965ba3b/Lib/fontTools/feaLib/ast.py#L616-L629

Correct docstring of AlternateSubstStatement

---

Lib/fontTools/misc/bezierTools.py
Tests/misc/bezierTools_test.py

This feels a bit hacky, but fixes the problem.
I was tempted to also implement this for quads but I don't have a test case for that; the change is trivial enough so could make it anyway, but wanted to keep the patch minimal for the time being.
- fixes #3742

[bezierTools] Improve robustness of curve splitting

---

Lib/fontTools/ttLib/tables/_n_a_m_e.py
Tests/ttLib/tables/_n_a_m_e_test.py

`table__n_a_m_e.names` access was guarded in a few places, but not everywhere (e.g. `getName`, `removeUnusedNames`). Removed guards and set `self.names = []` attribute in constructor to ensure it exists.

Ensure names attr exists on table__n_a_m_e

---

Lib/fontTools/pens/statisticsPen.py

An open contour was hitting this because _startingPoint wasn't set.
Fixes https://github.com/fonttools/fonttools/issues/3527
@punchcutter Please test.

[StatisticsControlPen] Fix uninitialized variable

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/pens/ttGlyphPen_test.py

The first commit reproduces the issue found in https://github.com/googlefonts/fontc/issues/1206, whereby the bounding box of a composite glyph with non-trivial transforms that references a base glyph in turn containing un-rounded floating-point coordinates, may end up with off-by-ones 
The fix (in a follow up commit) is to compute their bounding box on the rounded integer coordinates.
context: when building a VF, ufo2ft passes to fonttools TTGlyphs with unrounded coordinates, so that the latter can effectively drop implied off-curve glyf points (when that optional feature is enabled). We want to keep the coords unrounded (they will be eventually rounded anyway upon saving, after dropImpliedOncurvePoints has done its thing), but at the same time we want ufo2ft to compute the _final_ glyf …

[glyf] fix bbox of transformed components with un-rounded coordinates

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/pens/ttGlyphPen_test.py

This is a regression introduced with https://github.com/fonttools/fonttools/pull/3750
The test currently fails because after that PR we are rounding the coordinates extracted from each component of a composite glyph *before* these are transformed; with nested components of components with non trivial transforms, the rounding errors compound leading to incorrect bounds.
The correct way to do this (in a way that gives the same result whether the simple glyphs' original coordinates were rounded to begin with or not) is to ensure the rounding occurs only at the leaves (on the simple glyphs), and
at the very end of the chain after all the nested component trasforms have been concatenated and applied; but not at intermediate levels of the component tree.

[recalcBounds] fix rounding of bbox for nested transformed components

---

Lib/fontTools/unicodedata/Blocks.py
Lib/fontTools/unicodedata/ScriptExtensions.py
Lib/fontTools/unicodedata/Scripts.py
MetaTools/buildUCD.py
Tests/unicodedata_test.py

The method that was being used to read the header from the input was inadvertently dropping the first non-header line on the floor; although this happens to be okay in some cases (where there is an empty line after the header) in the case of newer versions of the ScriptExtensions.txt file, this was causing the generated code to be missing the first entry, for U+00B7 (MIDDLE DOT)

[unicodedata] Fix bug in buildUCD.py

---

Doc/source/ttLib/index.rst
Doc/source/ttLib/macUtils.rst
Doc/source/ttLib/removeOverlaps.rst
Doc/source/ttLib/reorderGlyphs.rst
Doc/source/ttLib/scaleUpem.rst
Doc/source/ttLib/sfnt.rst
Doc/source/ttLib/standardGlyphOrder.rst
Doc/source/ttLib/tables/TupleVariation.rst
Doc/source/ttLib/ttCollection.rst
Doc/source/ttLib/ttFont.rst
Doc/source/ttLib/ttGlyphSet.rst
Doc/source/ttLib/woff2.rst
Lib/fontTools/ttLib/tables/otTables.py
Lib/fontTools/ttLib/tables/otTraverse.py
Lib/fontTools/ttLib/ttFont.py

Adds text to help orient newcomers at ttLib and at ttLib/ttFont, and fills in helper/utility module pages.
This also links the idea of TTGlyphs (or ttGlyphSet members) to the pen protocol, hopefully clarifying that relationship.

[Docs] ttLib: higher-level navigation and helper documentation

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/test_results/BuildGvarCompositeExplicitDelta.ttx
Tests/varLib/varLib_test.py

Apparently the macOS bug has been fixed. I'm not sure when, but in 10.14.6 the workaround introduced in #1381 is not needed anymore. Can anybody confirm?

Remove workaround (#1381)

---

Lib/fontTools/feaLib/error.py

Adding a default value for `location` makes `FeatureLibError` pickleable and thus useable with multiprocessing.

[feaLib] Make FeatureLibError pickleable (#3762)

---

Lib/fontTools/varLib/varStore.py
Tests/varLib/varStore_test.py

When the VarStore.optimize() algorithm was improved with the addition of a priority queue, specifically with this commit https://github.com/fonttools/fonttools/commit/47ec18f788, a pre-sorting step of the todo list (before the queue itself was populated) was kept to make sure the algorithm continued to produce stable results no matter the order of the inputs.
The optimizer's output is itself sorted, again for stability, but using a different key function with_sort_key() from the one used on the input todo list gain_sort_key().
The rationale for a distinct gain_sort_key, where encodings get sorted by maximum theoretical gain (decreasing, initally, when reverse=True was set, then incrasing as reverse was somehow dropped), is no longer needed now that a priority queue is used (this sorts by …

[varStore] use the same sorting for both input/output

---

Lib/fontTools/ttLib/__main__.py

does the same as ttx homonymous option

add --no-recalc-timestamp to fonttools ttLib CLI

---

Lib/fontTools/ttLib/__main__.py

works the same as ttx's -b compile option, i.e. sets TTFont(recalcBBoxes=False)

add -b (recalcBBoxes=False) flag to ttLib CLI

---

Lib/fontTools/ttLib/tables/_c_m_a_p.py
Lib/fontTools/ttLib/ttFont.py

I see 10% or so loading glyph names from a large CJK font.

[cmap] Speed up glyphOrder loading from cmap

---

Lib/fontTools/misc/testTools.py
Lib/fontTools/ttLib/tables/D__e_b_g.py
Tests/ttLib/tables/D__e_b_g_test.py

Fixes https://github.com/fonttools/fonttools/issues/3779
note this changes the ttx dump of 'Debg' table in that it wraps the CDATA block inside a `<json>` sub-element, which is required for the XMLReader to be able to parse it back from TTX.
Since parsing was silently broken until now, we shouldn't worry about backward compatibility but treat this as a bug fix.
It's also a private table which shouldn't be in production fonts so we are probably free to change as needed.

[Debg] fix parsing from XML; add roundtrip tests

---

Lib/fontTools/otlLib/optimize/gpos.py
Tests/otlLib/optimize_test.py

This especially improves ergonomics when unconditionally invoking the otlLib optimizer as a script, e.g.:
```bash
python -m fontTools.otlLib.optimize Abc.ttf
```
If a `GPOS` table was not present, this would previously crash with `KeyError`; now the script can be used on any font instead.

[otlLib.optimize] Fix crash when the provided TTF does not contain a `GPOS`

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/builder_test.py
Tests/varLib/data/test_results/Build.ttx
Tests/varLib/data/test_results/BuildMain.ttx

This saves a handful of bytes for the common case where a font is variable but has no variation in its advances (e.g. for some monospace fonts across `wght`), and we include an empty metrics variation table so that the shaper can immediately ascertain this without interpolating phantom points.
e.g. a direct mapping is now preferred for the font in the included test case, shrinking the table from 47 to 42 bytes
```diff
--- before.xml
+++ after.xml
@@ -1,19 +1,16 @@
<?xml version="1.0" encoding="UTF-8"?>
<Version value="0x00010000"/>
<VarStore Format="1">
<Format value="1"/>
<VarRegionList>
</VarRegionList>
<VarData index="0">
<NumShorts value="0"/>
<Item index="0" value="[]"/>
</VarData>
</VarStore>
-<AdvWidthMap>
-  <Map glyph="A" outer="0" inner="0"/>
-</AdvWidthMap>
```
This …

Prune unused regions from HVAR and VVAR when using a direct mapping

---

Lib/fontTools/feaLib/ast.py
README.rst

They don’t really have `self.glyphs`. The erroneous `self.glyph` has been hiding in a branch of edge case (no prefix, no suffix, and no nested lookups).
It’s unclear if such an edge case should be serialized as a special case (without the `'` mark), therefore I’m only proposing a minimal fix for now.

[feaLib] Correct ChainContextPosStatement and ChainContextSubstStatement

---

Lib/fontTools/ttLib/tables/otBase.py

The `OTTableWriter.getOverflowErrorRecord()` method accesses `name` attribute unconditionally, but `OTTableWriter()` constructor does not set it and instead call sites like in otConvertor.py set the name.
But not all call sites set the name. In my case an overflow is happening `otlLib.builder.ChainContextualBuilder.getCompiledSize_()` which constructs an `OTTableWriter` and uses it without setting a name. I don’t even know what name it should use, and it feels less error prune for `OTTableWriter` constructor to set an initial name.

[ttLib] Fix `AttributeError` when reporting table overflow

---

Lib/fontTools/ttLib/tables/_g_l_y_f.py
Tests/ttLib/tables/_g_l_y_f_test.py

Regardless of whether or not a component transform is simple, we still have to round the points before returning, or we risk the error propogating up to another component that might have a non-trivial transform.

[ttLib] Apply rounding more often in getCoordinates

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/otlLib/builder.py
Tests/feaLib/ast_test.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/single_pos_NULL.fea
Tests/feaLib/data/single_pos_NULL.ttx
Tests/feaLib/parser_test.py

* Serializing `<NULL>` in single pos statements was broken (it was skipped resulting in invalid feature code).
* Building such lookups was broken as well.
AFDKO’s makeotf does not support `<NULL>` at all, but we support it in pair pos lookups, so this is not much different. It might not be of much value, but it is something OpenType layout supports and it is causing round tripping issue for some code I’m working on.

[feaLib] Correctly handle <NULL> in single pos lookups

---

Lib/fontTools/feaLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/class_pair_pos_duplicates.fea
Tests/feaLib/data/class_pair_pos_duplicates.ttx

AFDKO’s makeotf removes the duplicates and produces the following message:
NOTE: [line     3 char  29] Removing duplicate glyph <A>
NOTE: [line     3 char  29] Removing duplicate glyph <A>
While feaLib fails with:
Traceback (most recent call last):
File "/fonttools/Lib/fontTools/feaLib/builder.py", line 875, in buildLookups_
otLookups.append(l.build())
^^^^^^^^^
File "/fonttools/Lib/fontTools/otlLib/builder.py", line 1460, in build
builder.addPair(glyphclass1, value1, glyphclass2, value2)
File "/fonttools/Lib/fontTools/otlLib/builder.py", line 1340, in addPair
self.classDef1_.add(gc1)
File "/fonttools/Lib/fontTools/otlLib/builder.py", line 2656, in add
raise OpenTypeLibError(
fontTools.otlLib.error.OpenTypeLibError: Glyph A is already present in class.

[feaLib] Remove duplicates from class pair pos classes

---

Lib/fontTools/otlLib/builder.py

As well as general creature comforts, this avoids popular Python type checkers assuming that the elided fallback name argument can only accept an integer.

Add typing for the simpler STAT arguments

---

Lib/fontTools/otlLib/builder.py

Follow up to https://github.com/fonttools/fonttools/pull/3812.
No need to evaluate the types we added early.

[otlLib.builder] Add future import for annotations

---

Lib/fontTools/mtiLib/__init__.py
Lib/fontTools/subset/__init__.py
Lib/fontTools/ufoLib/__init__.py
MetaTools/buildUCD.py
Snippets/svg2glif.py

#3495 on more text file readers. Fix #3822 through `ufoLib/__init__.py`

Update text file read to use UTF-8 with BOM

---

Lib/fontTools/misc/symfont.py
Lib/fontTools/varLib/featureVars.py
NEWS.rst
Tests/varLib/data/test_results/FeatureVars_latn_dflt_var.ttx
Tests/varLib/varLib_test.py

We found this one during the development of a font. The GSUB table builder seems to discard defined language systems when they have no lookups. This is a problem when we add feature variations in a later step, like we do when we compile a Designspace with rules.
When like in the test code no lookup is defined for `latn` and `dflt`, just for the `CAT ` language, the GSUB table won't have a `dflt` LangSysRecord that https://github.com/fonttools/fonttools/blob/e89d7db4f457742a03d7a07121fd7348ca3ee1ca/Lib/fontTools/varLib/featureVars.py#L394 needs to attach itself to.
TODO:

Create a dflt LangSys in a ScriptRecord when adding variations later

---

Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/spec8a.ttx
Tests/feaLib/data/spec8a_2.ttx

If a single substitution was promoted to a multiple or ligature substitutions, we would no longer add it to aalt feature (when requested) since only single and alternate substations are added there.
This can be considered a regression from lookup promotion. Since a single-looking substitution wouldn’t occurs in ligature or multiple substitution unless we promoted it, it should be safe to add these to allt feature.
Fixes https://github.com/fonttools/fonttools/issues/3845

[feaLib] Add promoted single substitutions to aalt feature

---

Lib/fontTools/feaLib/ast.py
Lib/fontTools/feaLib/builder.py
Lib/fontTools/otlLib/builder.py
Tests/feaLib/builder_test.py
Tests/feaLib/data/bug3846_1.fea
Tests/feaLib/data/bug3846_1.ttx
Tests/feaLib/data/bug3846_2.fea
Tests/feaLib/data/bug3846_2.ttx
Tests/otlLib/maxContextCalc_test.py

Move the logic down into the builder so that it is applied after lookups are split due to e.g. different lookup flags or interspersed contextual substitution rules. Arguably the builder was the right place for this all along, but I took the either route (twice!) before.
Fixes https://github.com/fonttools/fonttools/issues/3846

[feaLib] Improve single substitution promotion

---

Lib/fontTools/subset/__init__.py
Tests/subset/data/PreserveSillyNamesTest.ttx
Tests/subset/subset_test.py

Preserve select nameIDs in `fvar` and `STAT` when obfuscating names, to avoid dangling name IDs in subset fonts.
Closes https://github.com/fonttools/fonttools/issues/3773.

Copy name IDs in use before scrapping or scrambling them for webfonts

---

Lib/fontTools/ttLib/tables/_h_m_t_x.py
Tests/ttLib/tables/_h_m_t_x_test.py

Fixes #3843 
Sometimes hmtx or vmtx may appear truncated with not enough data to decompile the list of sidebearings at the end of the table. Currently an IndexError would be thrown which is confusing.
```
ERROR: An exception occurred during the decompilation of the 'vmtx' table
Traceback (most recent call last):
File "fontTools/ttLib/ttFont.py", line 468, in _readTable
table.decompile(data, self)
File "fontTools/ttLib/tables/_h_m_t_x.py", line 67, in decompile
self.metrics[glyphName] = (lastAdvance, sideBearings[i])
~~~~~~~~~~~~^^^
IndexError: array index out of range
Dumping 'vmtx' table...
```
This PR makes it so we raise the same TTLibError(f"not enough {tableTag} data") that we already raise when we don't have enough table data to decompile the "long" metrics.

Improve {v,h}mtx error when not enough data to decompile sidebearings

---

.github/workflows/test.yml
Lib/fontTools/cu2qu/cu2qu.py
Tests/cu2qu/cu2qu_test.py

@cmyr noticed that sometimes with some degenerate cubic curves (e.g. those where control points are on the same line), cu2qu can produce different number of quadratic off-curves depending on whether it is running in compiled cython mode (as one would get when installing from the wheels that we publish to PyPI) vs pure-python mode (e.g. when pip installing fonttools in editable from a local git checkout inside a python environment that doesn't have cython, or without explicitly asking for FONTTOOLS_WITH_CYTHON=1 at built time).
I isolated one of these offending curves (from BilboPro.glyphs) to create the test.
The `calc_intersect` function calls `dot` to compute the vector dot product, in this situation this is expected to be 0.0 and trigger a ZeroDivisionError.
But for some reasons …

[cu2qu] Fix incosistent approximation when run in pure-python vs cython

---

Lib/fontTools/varLib/instancer/__init__.py

This fix is the same as #2827, but in `varLib.instancer`.

Avoid negative hmtx values when creating font from variable

---

Lib/fontTools/varLib/__init__.py
Tests/varLib/data/InconsistentUseMyMetrics.designspace
Tests/varLib/data/master_ttx_interpolatable_ttf/InconsistentUseMyMetrics-Bold.ttx
Tests/varLib/data/master_ttx_interpolatable_ttf/InconsistentUseMyMetrics-Regular.ttx
Tests/varLib/data/test_results/InconsistentUseMyMetrics-VF.ttx
Tests/varLib/varLib_test.py

A VF's glyf table is copied from the default master's glyf table. If a composite glyph's component has USE_MY_METRICS set in there (because the composite happens to have the same advance width as one of its components) but the flag is not set consistently among the other masters, that's probably because the composite and component metrics aren't meant to be the same throughout the variation space. Leaving the flag set, means ignoring variations of glyf/gvar phantom points of that composite glyph (as these gets simply copied from the component glyph with USE_MY_METRICS flag on).
The issue with composite glyph metrics doesn't arise normally unless the optional HVAR table (which provides deltas for the glyph metrics irrespective of the USE_MY_METRICS_FLAG) is removed from the VF. The absence …

[varLib] Clear inconsistent USE_MY_METRICS flags across masters

---

Lib/fontTools/varLib/interpolatableHelpers.py
README.rst

While working on GlobaLeaks, we install python3-fonttools as a dependency for python3-fpd2. Our system initially pulled in python3-scipy, which significantly increased the size of our setups and of Docker releases. To reduce the footprint, we preferred installing the pure-Python Munkres implementation and prioritize reduced footprint over performance.
We appreciate that FontTools maintains both options for solving the Assignment problem:
- scipy.optimize.linear_sum_assignment for performance, and
- Munkres as a fallback for minimalistic systems.
The aim of this pull request is to extend documentation to make this duplicity clear and ensure it is maintained in future versions. This possibility is in fact considered by maintainers of the Debian and Ubuntu package python3-fonttools that have …

Clarify linear_sum_assignment backend options and minimal dependency usage

---

Lib/fontTools/misc/enumTools.py
Lib/fontTools/pens/filterPen.py
Lib/fontTools/pens/pointPen.py
Tests/pens/filterPen_test.py

Fixes the discrepancy in starting points when decomposing flipped components between fonttools and fontc (googlefonts/fontc#1633).
When decomposing composite glyphs with flipped components (negative determinant), fonttools and fontc handle the contour starting point differently:
- fonttools (via ReverseContourPointPen): Reverses the contour but keeps the same starting point (even if it's off-curve)
- fontc (via kurbo's `BezPath::reverse_subpaths()`: Reverses the contour and rotates it to start with the first on-curve point (BezPath being a collection of curve segments rather than a closed list of points; the rotation occurs well before `reverse_subpaths` while constructing the BezPaths from the UFO/Glyphs sources' outline points).
ufo2ft's uses fonttools' `DecomposingFilterPointPen` to …

DecomposePointPen: add reverseFlipped="on_curve_first" to match fontc's flipped component decomposition
